### ISSUE TITLE
Неверное время моделирования

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#101]
В трассировке и на графиках верное, модель https://github.com/aurusov/rdo-xtext-models/blob/master/models/barber_clients.rao

```
set terminateCondition() {
    return currentTime >= 7 * 12 * 60;
}
```

В `Status View` - нет.

Как повторить
- изменить условия окончания на `currentTime >= 7 * 12 * 6`
- сохранить модель
- запустить модель
- изменить условия окончания на `currentTime >= 7 * 12 * 60`
- запустить модель (без сохранения)
- сохранить модель
- запустить модель - ошибка

![2015-07-25 16 14 25](https://cloud.githubusercontent.com/assets/5585202/8889579/5212710a-32e8-11e5-81fa-4f6bb5e1fc6f.png)

**Comment by aurusov** [comment]
Кажется, что это должно полечиться после #102, но хочется понять причину. Может быть есть отдельная ошибка.

**Comment by aurusov** [comment]
Только что создал [модель](https://github.com/aurusov/rdo-xtext-models/blob/master/models/barber_simple.rao) с нуля, запустил, получил
![2015-08-09 12 10 01](https://cloud.githubusercontent.com/assets/5585202/9154276/a0ca2164-3e8f-11e5-852e-1c0aefeef7ef.png)

**Comment by bogachev-pa** [comment]
Замержено в ветку `feature/2.3.`
