### ISSUE TITLE
Заполнение дерева сериализуемых объектов

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/raox#107]
После обновления кнопки прогона модели (точнее, ее disable/enable), в плагине пятнашек могла бы отпасть необходимость в кнопке Simulation, если бы не проблема в окошке Monitoring configuration:
![screenshot from 2015-08-08 22 23 51](https://cloud.githubusercontent.com/assets/10632455/9151858/400588dc-3e1c-11e5-9540-a547b46da72e.png)
Окошко пустое, поэтому для трассировки необходимо открыть эдитор модели, поставить галочку (заполнить дерево) и только после этого трассировка будет не "пустая", а граф можно будет построить.
Кажется, есть два (?) решения:
1. Сделать по умолчанию галочку на сериализации всего-всего-всего - дополнительная кнопка не нужна.
2. При нажатии на кнопку как-то программно заполнять дерево, но как? :\

**Comment by bogachev-pa** [comment]
1. Галочка по умолчанию не решит проблему, потому что нужно сначала сформировать дерево объектов, которые можно сериализовать. Пока он формируется при открытии эдитора (плюс регистрируется листенер на изменения в эдиторе).
   Тем не менее, я думаю, галочку по умолчанию действительно стоит сделать проставленной - просто для удобства.
2. Что касается решения проблемы, кажется, правильнее всего заполнять дерево сразу из всех файлов `.rao` в проекте. А листенеры регистрировать можно уже при открытии конкретного эдитора. В идеале плагину не нужно будет придумывать ничего дополнительно.
   Я посмотрю, как это сделать.

**Comment by aurusov** [comment]
2 Поддерживаю. Если этот код будет заточен на плагин, то и разместить его надо в исходниках плагина.

**Comment by LeKaitoW** [comment]
2 Но ведь этот код не должен быть заточен на плагин (хотя для плагина эта возможность важна).
Если в проекте 3 файла `.rao`, которые описывают одну модель, то в дерево попадут объекты не всех трех файлов, а только одного, который открыт на данный момент.

**Comment by aurusov** [comment]
2 Должен, и только под плагин. Не вижу аргументов, почему это должно стать для РДО режимом по умолчанию. Такого никогда не было, даже в старом. Наоборот, модель будет тупить.

**Comment by bogachev-pa** [comment]
Здесь два принципиально разных момента. Проставление галочек и формирование дерева. Оба независимы от плагина (давайте его пока не рассматривать вообще), но их важно не путать.

1**.** Режим по умолчанию с галочками или без.

Доводы за галочки:
- позволит избавить пользователя от лишнего клика на простых моделях

Доводы против:
- заставит пользователя делать лишний клик на больших моделях, причем с чуть более тяжелыми последствиями

Хотя для студентов будет удобнее, если все уже будет заполнено, наверное, все же честнее будет не заполнять их по умолчанию.

2**.** Заполнение дерева сериализуемых объектов содержимым. Сейчас для проекта, в котором модель разбита на много файлов `.rao`, нужно прокликать по ним всем разок, чтобы заполнить дерево.
Хочется, чтобы оно заполнялось содержимым независимо от этих кликов.

Теперь, что касается плагина:
3**.** Достаточно сформировать апи для проставления галочек программным способом, чтобы всем было счастье.

**Comment by aurusov** [comment]
Ну да же. Мне нечего дополнить. Про певрое не говорил, потому что ты на него ответил полно. Не понимаю, зачем так долго это обсуждать.

**Comment by bogachev-pa** [comment]
Сделал. Подход такой:
Как только открывается новый эдитор, проверяем, в каком он находится проекте, и заносим его в мапу `<IProject, Set<IEditorPart>>` (т.е. с каждым проектом связано произвольное число эдиторов). Далее проходимся по проекту, ищем в нем все файлы `.rao` и добавляем их все в дерево, по пути занося в мапу `<IResource, SerializationNode>` (естественно, если кто в мапе уже присутствует, не заносим).
Когда закрываем эдитор, удаляем его из списка в мапе, связанной с проектом, и проверяем - последний ли это эдитор, связанный с проектом. Если последний, очищаем так же мапу всех файлов `.rao`, связанных с проектом.

Кстати, теперь не нужно хотя бы раз кликнуть по эдитору, чтобы дерево заполнилось галочками. Достаточно, чтобы он был "открыт". Тут есть странность эклипса, при открытии воркбенча, эдиторы, которые находились в фоновых вкладках, "открытыми" почему-то не считаются.
Побороть ее мне не удалось, т.е. фоновые вкладки из другого проекта не добавят ничего в дерево.
Еще один недостаток(но он был и раньше) - если файл удалить, а соответствующий ему эдитор все еще открыт (но не обновился), объекты, которые были в дереве от этого эдитора останутся.

Edit: еще косяк - аналогично удалению, если незаметно создать новый файл, не трогая никакие эдиторы, он в дерево тоже не попадет. Пока думаю, как эти вещи аккуратнее поправить.

**Comment by bogachev-pa** [comment]
Также добавил в сериализейшн конфиг вью простое апи - `checkAll()` и `uncheckAll()`.

**Comment by bogachev-pa** [comment]
> Edit: еще косяк - аналогично удалению, если незаметно создать новый файл, не трогая никакие эдиторы, он в дерево тоже не попадет. Пока думаю, как эти вещи аккуратнее поправить.

Исправил все это. Теперь даже если менять содержимое неоткрытых файлов программно (здесь ограничение эклипса - либо через апи ресурсов, либо синхронизировать воркспейс после изменений), эти изменения подтягиваются в дерево.

**Comment by aurusov** [comment]
Ты можешь резюмировать отставшиеся косяки ?

**Comment by bogachev-pa** [comment]
Заметил только один - если проект удалить целиком, содержимое его файлов из дерева не исчезнет. Пока еще разбираюсь, как лучше исправить.

**Comment by bogachev-pa** [comment]
Все починил, а также убрал апдейты и поиски файлов, когда это не нужно.
Теперь в дереве у нас отображаются все `rao`-файлы всех открытых проектов.

**Comment by bogachev-pa** [comment]
Все сделано и замержено.
