### ISSUE TITLE
Нельзя создать пустое событие

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#116]
Вот это не компилируется

``` antlr
event serviceFinished() {
}
```

с сообщением

```
required (...)+ loop did not match anything at input '}'
```

**Comment by bogachev-pa** [comment]
Да, пустые события грамматикой запрещались. Хотя, действительно, почему бы и нет, так что я разрешил (пока локально) везде пустые наборы стейтментов.

Выглядеть это будет, например, так:

``` erlang
operation emptyPattern() {
    set duration() {
    }
    set begin() {
    }
    set end() {
    }
}

rule emptyRule() {
    set execute() {
    }
}

event emptyEvent() {
}

set init() {
    emptyEvent.plan(currentTime);
}

dpt model {
    activity empty_operation_activity checks emptyPattern();
    activity empty_rule_activity checks emptyRule();
}
```

Теперь возникло несколько вопросов:
1. Можно ли разрешать паттерну жить без релевантных ресурсов? Если да, то какое ожидается поведение - всегда может выполниться?
2. Можно ли разрешать паттерну вообще не задавать методы `duration()`, `end()`, `begin()`? Теперь их можно делать пустыми, `duration` по умолчанию 0. Я на уровне валидаторов не позволяю эти методы опустить сейчас, но мб переделать и разрешить паттернам быть без них?

**Comment by aurusov** [comment]
1. Холиварная даже для меня тема. Ну пусть будет без релевантных. Всегда выполнять. Тут есть нюансы независимо от рел. ресурсов. Старое РДО проверяло не только условие запуска, но и изменится ли состояние системы после выполнения. Если не изменится, то паттерн не запускался.
2. Да. Да.

**Comment by bogachev-pa** [comment]
Основное сделал, осталось вот это:

> Старое РДО проверяло не только условие запуска, но и изменится ли состояние системы после выполнения. Если не изменится, то паттерн не запускался.

**Comment by aurusov** [comment]
> Основное сделал, осталось вот это:

https://github.com/aurusov/rdo-xtext/issues/122

**Comment by bogachev-pa** [comment]
Под прокачку рулов таска отдельная, так что закрываю эту.
