### ISSUE TITLE
Собираемые показатели

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#123]
@aurusov, @LeKaitoW, @k-alexandrovsky 

Из таски про документацию:

> Написание документации по результатам в очередной раз навело меня на мысль, какие же они у нас странные. Например, почему мы собираем статистику для watchValue только в момент удаления какого-то ресурса? Почему не с периодичностью или при каждом изменении значения? Мне кажется, их все надо очень сильно переделать. Не знаю, кому и когда, но пока я придумывал для странички результатов примеры, осознал, что ими очень неудобно пользоваться.

Вкратце мое мнение по поводу текущих собираемых показателях по отдельности:
1. `getValue()`. Ок.
2. `watchState()`. Ок.
3. `watchQuant()`. В основном ок, но вместо передачи `any` вторым параметром стоит сделать просто вызов без второго параметра вообще. А еще, наверное, надо переименовать в `watchQuantity()`. 
4. `watchValue()`. Цитирую старую справку:

> В процессе прогона собирается статистическая информация о значении указанного арифметического выражения в момент уничтожения какого-либо ресурса определенного типа, состояние которого удовлетворяет условию.

Не знаю, как остальным, но мне трудно даже распарсить эту фразу. Почему статистика собирается таким хитрым образом? В этом есть особый профит? Если есть, то показатель надо назвать явно по-другому, потому что `watchValue` слишком общее имя для него. 
5. `watchParameter()`. Ок.

Теперь по поводу показателей в целом:
1. Не хватает возможности собирать статистику по произвольному арифметическому выражению для всех моментов времени - без хитрых условий `watchValue()`.
2. Показатели `watchState()`, `watchQuant()` и `watchParameter()` после внедрения 1 окажутся ненужными, т.к. такой показатель их поглотит. Отдельного понятия `логическое выражение` у нас в языке теперь нет, это просто `Expression`, который возвращает `boolean`. То же с параметром ресурса. Для получения числа ресурсов можно ввести особую конструкцию в духе `ResourceType.quantity()`. 

Если есть еще мысли по этому поводу, дополняйте.

**Comment by k-alexandrovsky** [comment]
> Для получения числа ресурсов можно ввести особую конструкцию в духе ResourceType.quantity()

Да тут уже все есть и даже работает

```
Select(<имя_типа_ресурсов>: (<логическое_выражение> | NoCheck)).Size
```

В итоге выходит, что требуется два типа - для сбора статистики (можно назвать `continuous`), и единичный, который "выстреливает" лишь один раз (`singular`, как вариант).
Задача каждого результата - просто добавить число в последовательность. Это можно сделать по условию, либо безусловно. То же самое для единичных - по условию или без (без условия будет аналогично `getValue`). Еще можно сделать так, чтобы сбор можно было дернуть вручную (например, в паттернах).

**Comment by k-alexandrovsky** [comment]
Что нибудь такое

```
result QQQ = continuous {
    set condition() {
        return Time_now > 10;
    }

    set evaluate() {
        return barber1.whatever;
    }
}

result WWW = continuous {
    set evaluate() {
        return Select(Barbers: NoCheck).Size;
    }
}

result TTT = continuous manual {
    set evaluate(Client client) {
        return client.type;
    }
}

result EEE = singular { // getValue
    set evaluate() {
        return barberShop.numberOfPeopleCutToDeath;
    }
}

result DDD = singular manual {
    set evaluate() {
        return Time_now;
    }
}
```

Отлавливать моменты удаления через ручные (`manual`) результаты. Просто в конвертерах им кидать объекты. Либо придумать систему подписок на подобное, чтобы в десяти удаляющих паттернах не пришлось копипастить вызов. Но это еще запилить надо.

**Comment by aurusov** [comment]
Просто в виде наброса, чтобы понять разницу между данными и алгоритмом. Можно к показателям отнестись как пустым контейрам, в которые из любого места модели дописываются данные. Тип контейнера определяет, какой математический расчет (алгоритм) над добавляемыми данными выполняется. Но придется выискивать все места в модели, из которых надо дергать добавление - это неудобно.

**Comment by aurusov** [comment]
В старом РДО можно
- Объеденять показатели в группы
- У каждой группы есть команды [запуска/остановки](https://github.com/aurusov/rdo_studio/blob/master/simulator/runtime/result/result_group_i.h#L12) наблюдения. Они дергаются из паттернов.

**Comment by aurusov** [comment]
> 3 . `watchQuant()`. В основном ок, но вместо передачи `any` вторым параметром стоит сделать просто вызов без второго параметра вообще. А еще, наверное, надо переименовать в `watchQuantity()`. 

Переименовать - да.

> 4 . `watchValue()`. Цитирую старую справку:

Переименовать можно. В момент удаления, потому что
- Надо же задать в какой момент собирать данные ? Если не в момент удаления, то надо вводить еще одно условие (или дописыать в текущее через `and`). Т.е. не надо делать вид, что его нет. Иначе подсчитаем непонятно что.
- В момент удаления, потому что параметры уже больше не поменяются. М.б. не гибко, но вполне логично.

> Теперь по поводу показателей в целом:
> 1 . Не хватает возможности собирать статистику по произвольному арифметическому выражению для всех моментов времени - без хитрых условий `watchValue()`.

Можно. Но не надо путать его с показателями по временным ресурсам. Что бы от них отказаться, надо качать методы `ResoursType.getObjectsInModelCount()`, `ResoursType.getDeletedObjectsCount()`. Например, как с помощью обобщенного показателя подсчитать кол-во удаленных объектов указанного типа ?

> 2 . Показатели `watchState()`, `watchQuant()` и `watchParameter()` после внедрения 1 окажутся ненужными, т.к. такой показатель их поглотит.

Пока непонятно, см. выше

> Отдельного понятия `логическое выражение` у нас в языке теперь нет, это просто `Expression`, который возвращает `boolean`.

Ты только что его определил. Это синонимы. `Логическое выражение` мне на лекциях больше нравится, потому в нем меньше от программирования и больше от математики. Но по сути - это синонимы.

> То же с параметром ресурса. Для получения числа ресурсов можно ввести особую конструкцию в духе `ResourceType.quantity()`. 

Да, это вообще полезно. Про это и писал выше. Но это мгновенное значение, его надо еще как-то добавить к показателю.

**Comment by bogachev-pa** [comment]
@aurusov 

> У каждой группы есть команды запуска/остановки наблюдения. Они дергаются из паттернов.

В смысле их может включать/выключать пользователь кодом на РДО?

> Надо же задать в какой момент собирать данные ? Если не в момент удаления, то надо вводить еще одно условие (или дописыать в текущее через and). Т.е. не надо делать вид, что его нет. Иначе подсчитаем непонятно что.

Но мы же не задаем такое для `watchState()` или `watchParameter()`, например? Если я правильно понимаю, они пересчитываются при каждом изменении состояния системы. Почему нельзя делать так же для `watchValue`?

> В момент удаления, потому что параметры уже больше не поменяются. 

Здесь не очень понял. Мы рассчитываем произвольно арифметическое выражение, ну не поменяются уже параметры одного ресурса, зато поменяются потом другого (и мб другого типа, а он тоже участвует в арифметическом выражении!), какая нам разница?

@k-alexandrovsky 
Мне нравится концепция. Кажется довольно гибкой и не слишком сложно реализуемой.

**Comment by aurusov** [comment]
> > У каждой группы есть команды запуска/остановки наблюдения. Они дергаются из паттернов.
> 
> В смысле их может включать/выключать пользователь кодом на РДО?

Да

> Но мы же не задаем такое для `watchState()` или `watchParameter()`, например? Если я правильно понимаю, они пересчитываются при каждом изменении состояния системы. Почему нельзя делать так же для `watchValue`?

Потому что это не надо :) Этот показатель собирает данные только в момент удаления. Все остальные значения ему не нужны. Его нельзя рассматривать отдельно от этого предиката. Но предикат модно задать в явном виде (прямо сейчас нельзя). Про что и написано выше. Т.е. ему сейчас замены просто нет.

Кончено, делать так можно. Я сокрее говорю, что для обратной совместимости надо как-то вытащить удаление в виде предиката. Это позволит свести к обобщенному показателю.

> Здесь не очень понял. Мы рассчитываем произвольно арифметическое выражение, ну не поменяются уже параметры одного ресурса, зато поменяются потом другого (и мб другого типа, а он тоже участвует в арифметическом выражении!), какая нам разница?

Кто является источним данных для показателя - разницы нет. Это все `RDOValue`. Вопрос откуда конкретно они насыпаются. Для данного показателя - из удаляемого ресурса. Видимо, я не понимаю, что тебя смущает.

**Comment by bogachev-pa** [comment]
> Для данного показателя - из удаляемого ресурса.

Смущает вот это. Написано - `арифметического выражения`. А вы говорите, данные приходят из удаляемого ресурса. Но для произвольно арифметического выражения данные могут приходить из разных ресурсов, не только из удаляемого. Из ресурсов другого типа. Системные данные, да что угодно.

Предлагаю обсудить это в скайпе, я смогу примерно минут через 40.

**Comment by aurusov** [comment]
Через 40 минут не смогу, еще не дома.

**Comment by aurusov** [comment]
> Смущает вот это. Написано - `арифметического выражения`. А вы говорите, данные приходят из удаляемого ресурса. Но для произвольно арифметического выражения данные могут приходить из разных ресурсов, не только из удаляемого. Из ресурсов другого типа. Системные данные, да что угодно.

Теперь понял тебя. Это гибче, чем я писал. Главное, что это последняя возможность что-то спросить у ресурса перед удалением. Считаей, что только его параметры и константы могут использоваться в этом арифметическом выражении, например, `par1 + 2 * par2`. Но запрета на более сложное выражение тоже нет. Не вижу в этом проблемы. Главное тут тригер - удаление. Т.е. не надо лазить по паттернам и думать где расставить сбор статистики. Лучше переименовать этот показатель во что-то типа `watchValueWhenResourceDeleted`. А value пусть будет любым. Если же делать новый `watchValue`, то `WhenResourceDeleted` надо как-то задавать. Это скорее реакция на подписку об удалении, а не условие.

**Comment by aurusov** [comment]
> Отлавливать моменты удаления через ручные (`manual`) результаты. Просто в конвертерах им кидать объекты. Либо придумать систему подписок на подобное, чтобы в десяти удаляющих паттернах не пришлось копипастить вызов. Но это еще запилить надо.

Удаление - только через подписку. Иначе отчеты могут содержать ошибки из-за невниматеольности разработчика.

Сама идея с ручным набросом данных в собираемые показатели мне нравится.

**Comment by aurusov** [comment]
Подход Кирилла мне тоже нравится. Давай те придумаем еще пары `continuous`/`singular`. Может `dataset`/`value` ?

**Comment by AlexChernov** [comment]
Итого, как это будет выглядеть в грамматике:

```
singular/continuous manual/auto resultType T(resourceType a ) {
    set evaluate() {
        ...
    }

    set condition() {
        ...
    }
}
```

или

```
 manual/auto  dataset/value T(resourceType a ) {
    set evaluate() {
        ...
    }

    set condition() {
        ...
    }
}
```

```
result r = new T(barber1);
```

**Comment by aurusov** [comment]
Что означают `manual/auto` ?
Составить таблицу или просто пять примеров для старых пяти типов собираемых показателей.

**Comment by aurusov** [comment]
Что с задачей ?
