### ISSUE TITLE
Синтаксис функций

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#124]
@aurusov, @LeKaitoW, @k-alexandrovsky 

Пока писал страничку документации по функциям, возникли некоторые мысли по поводу функций типа `list` и `table`. Когда я переделывал грамматику рдо, их внутренний синтаксис я не менял. В итоге:

1**.** `list`
Из старой справки:

> Пользователь описывает все возможные значения функции и соответствующие им комбинации значений параметров. При вычислении функции определяются значения параметров, ищется соответствующая комбинация из описанных в теле функции, и функция принимает значение, указанное для данных значений параметров. 

Выглядит сейчас вот так:

``` erlang
int list example_xor(int a, int b) {
    0 0 = 0
    0 1 = 1
    1 0 = 1
    1 1 = 0
}
```

Смысл, я думаю, понятен.

Вот еще магия из старой справки:

> Если тело функции не содержит комбинацию значений параметров, вычисленных при данном вызове функции, то функция принимает значение, указанное как значение по умолчанию при описании типа значений функции. По этой причине указание значения по умолчанию при описании типа значения функции-списка является обязательным.

Надо бы проверить, как это вообще работает.

Вместо возможных улучшений синтаксиса этой функции, я предлагаю спилить ее вообще и заменить ее возможности какой-нибудь конструкцией для обычных функций. Например, мульти-свитч:

``` java
int example_xor(int a, int b) {
    mswitch(a, b) {
    case 0, 0:
        return 0;
    case 0, 1:
        return 1;
    case 1, 0:
        return 1;
    case 1, 1:
        return 0;
    }

    return -1;
```

Код стал объемнее, зато это можно использовать где угодно и читается это все гораздо лучше (понятно, что `xor` можно вообще намного проще написать, но он тут просто для примера). Обскурная проблема со значением по умолчанию тоже решится сама собой.

2**.** `table`

> При описании функции типа таблица все параметры должны иметь либо целый тип с обязательным указанием диапазона, либо перечислимый тип, причем для целых параметров значение нижней границы диапазона обязательно должно быть равно 1. Это необходимо для определения количества значений в таблице и правильного вычисления линейного номера значения.

Ужас! Инты с диапазоном. Зачем они вообще нужны там сейчас, может вообще спилить их? Я даже не уверен, что новое рдо полностью их поддерживает.

> Тело функции-таблицы представляет собой множество значений функции для каждой комбинации значений параметров. Значения в теле функции задают целой или вещественной численной константой либо именем значения в соответствии с типом значения функции и разделяют по крайней мере одним разделителем. В многомерных таблицах (количество параметров функции больше одного) значения располагают следующим образом: сначала указывают значения, соответствующие возрастающим значениям первого параметра-индекса, затем второго и так далее.

Выглядит сейчас вот так:

``` erlang
int table example_xor(int a[0..1], int b[0..1]) {
    0    1
    1    0
}
```

(надеюсь, не ошибся)

Во-первых, читается это все дело без комментариев довольно трудно (они даже добавлены в примеры в старую справку).
Во-вторых, кажется, что если не считать особые ограничения `table`, листы и таблицы полностью взаимозаменяемы. Различаться будет только синтаксис.
Но таблицы в теории могут выглядеть более компактно. Отсюда вопрос, хотим ли мы их сохранить как особые функции? Если да, то надо продумать для них более читаемый и, желательно, не намного более громоздкий синтаксис. Так вот сразу у меня идей нет.

Edit: вообще профит во внешнем виде таблиц есть только для двумерного случая. Таблицы большей размерности более удобными, чем те же списки, мне не кажутся.

**Comment by aurusov** [comment]
Список и таблица - не взаимозаменяемы. Список может иметь пропуски, таблица - нет.
1. `list`. Придумаывать `mswitch` не стоит. Он сводится к обыкновенному свичу над [tuple](http://en.cppreference.com/w/cpp/utility/tuple)

``` antlr
int example_xor(int a, int b) {
    switch(tuple(a, b)) {
    case tuple(0, 0):
        return 0;
    case tuple(0, 1):
        return 1;
    case tuple(1, 0):
        return 1;
    case tuple(1, 1):
        return 0;
    }
    return -1;
}
```

Можно свести к контейнеру

``` antlr
int example_xor(int a, int b) {
    static map<tuple(int, int), int> xor = {
        {tuple(0, 0), 0},
        {tuple(0, 1), 1},
        {tuple(1, 0), 0},
        {tuple(1, 1), 1},
    };
    return xor.find(tuple(a, b));
}
```
1. `table`. Табличная функция - это по сути многомерная матрица, доступная по чтению.

``` antlr
int example_xor(int a, int b) {
    matrix[2][2]<int> table = {
        {0, 1},
        {1, 0},
    }
    return table[a][b];
}
```

Ну или вложенный массив

``` antlr
int example_xor(int a, int b) {
    array<array<int>> table = {
        {0, 1},
        {1, 0},
    }
    return table[a][b];
}
```

**Comment by bogachev-pa** [comment]
> Список и таблица - не взаимозаменяемы. Список может иметь пропуски, таблица - нет.

Точно, упустил это. Точнее будет сказать, `table` - частный случай `list` (в терминах РДО).
1. Мне нравится `switch(tuple())`. Боюсь, правда, с джава-подобным синтаксисом придется все в явном виде параметризовать, но посмотрим.
2. Кажется, таблицы должны иметь смысл только для енумов. Рэнжед инты мне очень не нравятся как концепция, а как-то понимать, какие значения вообще подразумеваются для таблиц нужно. Однако в любом случае приходится прикидывать в уме, какие параметры соотносятся с каким результатом. Придумать, как улучшить читаемость, сохранив компактность, у меня не получается, все сводится к тем же спискам.

Видимо, с такими конструкциями нам сильно поможет `xbase`. Я рассчитываю начать работать над его внедрением где-то с сентября.
Пока его нет, нужно ли нам какое-то временное, не слишком трудозатратное решение, упрощающее синтаксис этих типов функций? Например, если эти функции нужны для лекций или лаб по РДО, хочется все-таки сделать их немного красивее уже сейчас.

**Comment by aurusov** [comment]
Времени осталось мало. Я бы не стал распыляться и закончил текущие задачи.

**Comment by bogachev-pa** [comment]
Уже неактуально, т.к. в `xbase` это все из коробки.
