### ISSUE TITLE
Сбор статистики

### ISSUE THREAD

**Issue by k-alexandrovsky** [LeKaitoW/raox#13]
Связан с:
- [x] #12 
- [x] #14 

<hr>  

Реализовать все методы в разделе Results.

**Comment by aurusov** [comment]
@k-alexandrovsky
Не понимаю про что задача. Поясни.

**Comment by k-alexandrovsky** [comment]
не хватало всяких watch_quant, watch_value. сейчас вроде есть уже все. это скорее к @bogachev-pa вопрос

**Comment by bogachev-pa** [comment]
Все виды сбора статистики из старого РДО уже реализованы.
