### ISSUE TITLE
Сборка проекта через maven

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#130]
Цель - получить набор `*.jar` - файлов
Текущие подзадачи
- [x] Настроить открытие перспективы `Rao` (https://github.com/aurusov/rdo-xtext/issues/175)
- [x] Актуально для Убунты, возможно и для Мака. В корне архива лежит eclipse, который потерял флаг, что он запускаемый. Т.е. разархивировав, не смог его запустить.
- [x] Сравнил папки архива с исходным эклипсом. Не понял, почему поменялись конфиги и т.д. Леша посмотри, обсудим голосом.
- [x] ~~После `mvn org.eclipse.tycho:tycho-versions-plugin:update-pom -Dtycho.mode=maven` гит показывает измененные файлы. Можно ли от них избавиться ?~~ Нет
- [x] После `mvn package` + `mnv clean` гит показывает много измененных файлов. Их или совсем не должно быть или только те, которые появились из-за `mvn org.eclipse.tycho:tycho-versions-plugin:update-pom -Dtycho.mode=maven`
- [x] ~~В помах проектов, например для ui, лежат настройки x-text'а. Зачем ? Если копипаста, то надо почистить.~~ Копипасты нет
- [x] Если есть копипаста в помах, то её надо почистить. Копипасту x-text'а вынес в отдельных пункт. Этот пункт для всего остального.
- [x] Добавить в сборку атрибут, указывающий на путь до eclipse.
- [x] Дописать смену версии в [gitflow](https://github.com/aurusov/rdo-xtext/blob/release/current/gitflow.md)
- [x] Убрать ru.bmstu.rk9.rao.tests-*.jar из архива
- [x] Добавить `properties` `target-os` и `target-bitness`

**Comment by aurusov** [comment]
У меня получилось скомпилять `rao.lib`, а `xtext` - нет. Свой опыт с grade'ом выложил тут
https://sites.google.com/site/raoxgradle/

**Comment by aurusov** [comment]
Задача довольно срочная, прошу продолжить.

**Comment by AlexChernov** [comment]
Вместо gradle используется maven. https://github.com/AlexChernov/rdo-xtext/tree/feature/maven

**Comment by AlexChernov** [comment]
```
mvn org.eclipse.tycho:tycho-versions-plugin:update-pom -Dtycho.mode=maven
mvn install
```

ru.bmstu.rk9.rao\target\ru.bmstu.rk9.rao-[version].jar
ru.bmstu.rk9.rao.lib\target\ru.bmstu.rk9.rao.lib-[version].jar
ru.bmstu.rk9.rao.tests\target\ru.bmstu.rk9.rao.tests-[version].jar
ru.bmstu.rk9.rao.ui\target\ru.bmstu.rk9.rao.ui-[version].jar

**Comment by aurusov** [comment]
Обновил шапку

**Comment by AlexChernov** [comment]
>Настроить открытие перспективы Rao (#175)

Пока два варианта:
1. Скопировать файл eclipse.ini из папки eclipse, лежащей рядом, дописать в него перспективу. Если нет такого файла/папки, сборка закончится с ошибкой(раньше создавался архив с папкой ```dropins```)
2. Хранить файл ```eclipse.ini``` так же как и ```eclipse``` рядом с исходниками. В исходниках хранить не получится, потому что в ```eclipse.ini``` есть платформозависимая строчка ```plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.300.v20150602-1417``` поэтому для каждой сборки понадобится создавать такой файл. Зато если его не создать, сборка, как и раньше , создаст архив с папкой ```dropins```

**Comment by aurusov** [comment]
>Пока два варианта:
Для перспективы есть же отдельная задача. Перенеси это сообщение туда.

**Comment by aurusov** [comment]
Обновил шапку

**Comment by aurusov** [comment]
В папке dropins оказывается джарник с тестами (ru.bmstu.rk9.rao.tests-*.jar). Он не нужен. Если это быстро делать, то лучше в этой таске, если нет, то заведи отдельную.

**Comment by AlexChernov** [comment]
> Добавить профиль, например, jars_only: Собрать все jar, перенести их в одну папку. Никаких архивов, никакого эклипса.

ru.bmstu.rk9.rao.tests-*.jar там я так понимаю быть не должно?

**Comment by aurusov** [comment]
Да
