### ISSUE TITLE
Настроить автосборку

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#131]
Шаги
- [x] завести задачу на дженкинсе
- [x] выкачать исходники `rdo-xtext`
- [x] собрать исходники через maven (https://github.com/aurusov/rdo-xtext/issues/130)
- [x] ~~выкачать архив с Эклипсом (Eclipse IDE for Java and DSL Developers)~~
- [x] ~~разархивировать его~~
- [x] перенести бинарники rdo в папку с плагинами
- [x] заархивировать папку с Эклипсом
- [x] выложить в инет
- [x] настроить несколько задач на дженкинсе для сборки
  - [x] win-x86
  - [x] win-x64
  - [x] ubuntu-x86
  - [x] ubuntu-x64
- [x] отразить в имени архива версию, разрядность и платформу в формате `raox-<version>-<win|linux|mac>-<x64|x86>.<zip|tar.gz>`, например `raox-2.7.1-win-x64.zip`. Вычисление версии можно подсмотреть в старом [РДО](https://github.com/aurusov/rdo_studio/blob/release/current/CMakeLists.txt#L132). Должно получиться что-то типа `2.2-298-g3583202`.

**Comment by AlexChernov** [comment]
https://github.com/AlexChernov/rdo-xtext/commit/2a235b94900a7c4e394c00e9e3ac22ebce24aa6c

**Comment by AlexChernov** [comment]
1. Выкачать исходники

```
mkdir rdo-xtext-mvn
cd rdo-xtext-mvn
git clone -b feature/maven-git-version-osgi https://github.com/AlexChernov/rdo-xtext.git
```

.
2. `cd rdo-xtext`
3. Запустить сборку

```
[mvn initialize -N -Pset-git-version]
mvn package
```

После этого в папке  rdo-xtext-mvn/rdo-xtext/assembly/target появится zip архив с собранными jar'никами
Для получения готового к развертыванию архива необходимо 
4. Скачать Eclipse IDE for Java and DSL Developers и распаковать его
5. Запустить сборку с параметром `-Declipse-path`

```
mvn clean package [-Declipse-path=PathToEclipseRoot] [-Dtarget-os=win] [-Dtarget-bitness=x64]
```

PathToEclipseRoot задается в абсолютном значении или относительно папки assembly
Если путь содержит пробелы, то кавычки ставятся вокруг параметра целиком, т.е.

```
mvn clean package "-Declipse-path=C:\Path with spaces\eclipse"
```

**Comment by AlexChernov** [comment]
По поводу автоматизации скачки eclipse
1. Мавен умеет скачивать файлы по url, и умеет их распаковывать в нужное место, а так же умеет создавать профили

```
<profiles>
  <profile>
    <id>Windows</id>
    <activation>
      <os>
        <family>Windows</family>
      </os>
    </activation>
    <properties>
      <eclipse-url>...</eclipse-url>
    </properties>
  </profile>
  ...
```

Но пока не знаю умеет ли в таком случае maven скачивать архив только в первый раз, как он это делает через `dependencies`
2. Мавен умеет копировать необходимые зависимости в нужное место, проблема в том чтобы указать eclipse, как зависимость. Я вроде даже нашел репозиторий, в котором хранятся все сборки eclipse, в том числе необходимая нам, но пока не смог заставить maven скачать эту сборку

```
  <groupId>org.eclipse.epp</groupId>
  <artifactId>org.eclipse.epp.package.dsl</artifactId>
  <version>4.5.1-SNAPSHOT</version>
  <packaging>eclipse-plugin</packaging>
```

**Comment by aurusov** [comment]
Проверил сборку под убунтой. Ну во-первых, она прошла удачно, архив получен. Теперь замечания
1. В корне архива лежит eclipse, который потерял флаг, что он запускаемый. Т.е. разархивировав я не смог его запустить.
2. Физар создал модель, но продолбался шаблон. Т.е. выбрав простейшую СМО получил пустую модель. Видимо не скопировались шаблоны.
3. Сравнил папки архива с исходным эклипсом. Не понял, почему поменялись кониги и т.д. Леша посмотри, обсудим голосом.

**Comment by aurusov** [comment]
Не понял, как правильно задавать версию.

**Comment by aurusov** [comment]
Задачи про мавен перенес в его таску https://github.com/aurusov/rdo-xtext/issues/130
