### ISSUE TITLE
Настроить юнит-тесты

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#132]
- добавить 1-2 фейковых `JUnit`-теста
- обернуть их сборку и запуск в maven

**Comment by aurusov** [comment]
@bogachev-pa 
Ты можешь написать 1-2 нормальных `JUnit`-теста ? Или подсказать какие можно сделать ?

**Comment by bogachev-pa** [comment]
Могу, но сейчас занят чуть более приоритетными задачами (имя проекта в всплывающей подсказке и иксбейз), так что не уверен, что сделаю к субботе (или мне и не нужно их интегрировать и коммитить?).

Как бы там ни было, простейший тест на корректность работы трассировщика будет выглядеть как-то так:

``` java
Tracer tracer = new Tracer();

final ByteBuffer header = ByteBuffer.allocate(EntryType.SYSTEM.HEADER_SIZE);
header.put((byte) EntryType.SYSTEM.ordinal())
                .putDouble(0).put((byte) SystemEntryType.TRACE_START.ordinal());
Entry entry = new Entry(header, null);

TraceOutput output = tracer.parseSerializedData(entry);

assertEquals("test_1", "ES 0.0 Tracing started", output.content());
assertEquals("test_2", TraceType.SYSTEM, output.type());
```

**Comment by aurusov** [comment]
Отлично, благодарю.
