### ISSUE TITLE
Строить граф при клике на трассироку ресурсов при поиске по графу

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#135]
Клик на специальные записи об изменениях ресурсов (`SRK`, `SRE`, `SRC`) тоже должен приводить к построению графа.

**Comment by aurusov** [comment]
Если с задачей все, то ставь пул-реквест.

**Comment by bogachev-pa** [comment]
Планировал залить вместе с остальными исправлениями по графу, т.к. она сделана в той же ветке.
