### ISSUE TITLE
Стиль кода моделей

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#139]
Открыл модель `game5`, нажал `Ctrl+Shift+F`, получил
![2015-09-05 23 00 18](https://cloud.githubusercontent.com/assets/5585202/9701045/e7a8e10e-5421-11e5-9043-893c6e45bb2e.png)
Надо или настроить его или отключить.

**Подробнее**:

Настройка форматирования производится в методе `configureFormatting()` класса `/ru.bmstu.rk9.rao/src/ru/bmstu/rk9/rao/formatting/RaoFormatter.xtend`. 

Пример того, как это делается, можно посмотреть [здесь](https://github.com/mn-mikke/Model-driven-Pretty-Printer-for-Xtext-Framework/wiki/Standard-Way-of-Code-Formatting-in-Xtext-Framework).

Пример проблем, аналогий которых не удалось найти в примере, т.е. нужно разбираться глубже:
- добавлять перенос строк после фигурных скобок вида:

``` java
type a {
    int b;
}
```

но при этом разрешить не переносить таким образом строки для енумов:

``` java
enum a {x, y, z}
```

и перед `else`: 

``` java
if (a > b) {
   ...
} else {
   ...
}
```
- Не ставить пробел между функциями и скобками, но ставить между `if` и скобками.

На данный момент локально удалось добиться такого поведения:
![formatting](https://cloud.githubusercontent.com/assets/6528492/10000719/9a3deb58-60a6-11e5-8316-6c9514662572.png)

Код, который это делает, можно посмотреть здесь: http://pastebin.com/wfhc9aGz

**Comment by bogachev-pa** [comment]
Я немного повозился с этим, в целом, все делается довольно просто, но есть некоторые тонкости, надо которыми надо подумать. Может быть неплохой задачей на практику новым студентам.

**Comment by aurusov** [comment]
Отпишись о том, что накопал. Лучше прямо в первом сообщении.

**Comment by bogachev-pa** [comment]
Обновил шапку.

**Comment by aurusov** [comment]
> На данный момент локально удалось добиться такого поведения:

Промежуточный результат куда-то закоммичен ?

**Comment by bogachev-pa** [comment]
Нет, только локально, т.к. не доведен до ума. Никаких особых откровений там нет, по примеру в шапке можно быстро научиться такое написать, но, если надо, могу выложить в том или ином виде.

**Comment by aurusov** [comment]
Лучше выложить. Проще всего в виде текста конфига прямо в сообщении imho.

**Comment by bogachev-pa** [comment]
Залил на `pastebin`, кажется, так удобнее.

**Comment by bogachev-pa** [comment]
Забыл про эту таску, так что случайно создал дубликат.
https://github.com/aurusov/raox/issues/377
Так или иначе, это сделано.

**Comment by aurusov** [comment]
1. покажи скрины
2. как настраивать ?

**Comment by bogachev-pa** [comment]
1**.** Удалил из модели все переносы строк и табы:
![formatting_1](https://cloud.githubusercontent.com/assets/6528492/15329735/d6d18c52-1c6a-11e6-90fc-d84730da7862.png)

`Ctrl + Shift + F`

![formatting_2](https://cloud.githubusercontent.com/assets/6528492/15329744/df0aa5a2-1c6a-11e6-9cde-9c1f22584c3c.png)

2**.** Пользователю ничего настраивать не надо, просто `Ctrl + Shift + F`

**Comment by aurusov** [comment]
1. Хорошо смотрится
2. Как мне изменить стиль кода ? Например, добавить перенос длиный строк. Или вставить пустую строку между событием и операцией.

**Comment by bogachev-pa** [comment]
2**.** в [RaoFormatter.xtend](https://github.com/bogachev-pa/raox/blob/d3163d56aea075a6f3edcb17879b3917b279d19b/ru.bmstu.rk9.rao/src/ru/bmstu/rk9/rao/formatting2/RaoFormatter.xtend) описываются эти правила, там они могут быть свои для каждого элемента грамматики.

Где изменить максимальную длину строки - не знаю, надо смотреть исходники классов, которые мы наследуем, кажется, сейчас есть некоторая величина по умолчанию. Я все делал на основе того, что видел `XbaseFormatter`, собственно. Какого-то универсального туториала у меня нет.
