### ISSUE TITLE
Отображение графиков

### ISSUE THREAD

**Issue by k-alexandrovsky** [LeKaitoW/raox#14]
Зависит от:
- [x] #11 

<hr>

Связан с:
- [x] #12 
- [x] #13

<hr>

Разобраться в доступных java-библиотеках отрисовки графиков. Интегрировать графики в интерфейс среды, через трассировку или напрямую.

**Comment by aurusov** [comment]
Наткнулся на [jFreeChart](http://www.jfree.org/jfreechart/index.html)

**Comment by k-alexandrovsky** [comment]
Да, выглядит круто, особенно секция с примерами. Я, правда, так и не разобрался, какие библиотеки он использует для отрисовки (в мире Java, оказывается, идет холивар между библиотекой `AWT/Swing` от Sun и  `SWT` из Eclipse), но скриншоты с графиками в эклипсе всюду есть, так что надо попробовать.

**Comment by aurusov** [comment]
В чем сильные и слабые стороны библиотек ?

**Comment by k-alexandrovsky** [comment]
Swing дает интерфейс как в NetBeans, то есть выглядит не очень нативно, но зато входит в состав JRE. SWT выглядит вполне нативно, но это отдельная библиотека, которая тоже полагается на платформозависимый нативный код, но не входит в состав виртуальной машины. Зато она входит в состав Eclipse, он весь на ней написан. Совмещать библиотеки можно через SWT_AWT Bridge, но он на линуксе и маке падает с завидной периодичностью. Я сейчас посмотрел, у jfree все же есть SWT-версия, так что можно пока оставаться в рамках либы эклипса.

**Comment by aurusov** [comment]
Требования к системе отображения графиков
1. Прореживание данных
2. Масштабирование
3. Убедиться, что работает на больших объёмах данных (не хуже, чем текущее РДО)
4. Умеет накладывать несколько графиков на один
5. Умеет показывать изменения, произошедшие в один и тот же момент времени
6. Умеет стоить график на лету

**Comment by aurusov** [comment]
@AlexChernov

**Comment by k-alexandrovsky** [comment]
В продолжение темы:

http://www.swtchart.org/
- Прореживание

> High Performance
> SWTChart provides an ability to handle large data size of series. Even if showing 1,000,000 data points, repainting or resizing chart panel doesn't take long time. The internal algorithm is not to simply sample the data with a certain interval but to **thin out only the data which doesn't make sense to show in current screen resolution**. Therefore, even if there are prominent peaks in large data points, the **peaks won't be lost in the screen**.
- Маcштабирование

> SWTChart Extension has an ability to zoom with mouse or to scroll with arrow keys.
- Большие объемы и реальное время:

> Fast enough for real time is swtchart, at least in my experience. Even with lots of data. Don't be scared away by the version number, yes it is a rather new API, but I use it successfully without problems.
> 
> > http://stackoverflow.com/a/558548
- Несколько графиков:

![screen1](http://www.swtchart.org/screenshots/img/multiple_axes.png)
![screen2](http://www.swtchart.org/img/chart.png)
- Изменения в один момент времени

Вроде решили, что никто не умеет и надо пилить самим.

<hr>

В любом случае, надо бы оттестировать. Выглядит спартански, конечно, но попробовать стоит.

**Comment by k-alexandrovsky** [comment]
![](http://i.gyazo.com/a212b92156975d9a81381190f67f4b02.png) ![](http://i.gyazo.com/ec536c820c7f1e19a6c30192891d9878.png)
Как то так. 10^5 точек отрисовывает за 1.5 секунды, 10^6 уже за 5 секунд. Все, что меньше на порядок, можно сказать, что мгновенно. Но это все если включен режим отображения step.
Если его отключить, то отрисовка даже 10^6 очень быстрая. На большее количество данных не хватает памяти. Единственный минус в том, что библиотека принимает только массивы double в качестве данных. И непонятно, как скармливать ей данные в реальном времени.

**Comment by aurusov** [comment]
Почему решили отказаться от http://www.jfree.org/jfreechart/ ?

@AlexChernov
Леша, можешь сравнить быстродействие со старыми графиками ? Или это неактуально, т.к. надо переезжать на новые полюбому ?
