### ISSUE TITLE
Перенести форматирование Луны на Марс

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#147]
Попробовал применить стиль Луны на Марс и Неон. Файл стиля переносится без проблем, но результаты форматирования отличаются. В обоих случаях (Луна -> Марс и Луна -> Неон) результат одинаковый.
![2015-09-13 14 17 45](https://cloud.githubusercontent.com/assets/5585202/9836432/3bb7b346-5a22-11e5-867a-5ee5fd0950d8.png)

Т.е. даже собственный стиль не решит проблему, потому что у эклипса поменялась логика, которая не вытащена в файль стиля.

Фалы со стилями отличаются незначительно
- [Луна](https://drive.google.com/file/d/0B-tnm4ER5l74RGlUSmhmMDkydzA/view?usp=sharing)
- [Марс](https://drive.google.com/file/d/0B-tnm4ER5l74RVE0WGEyV0Vja3M/view?usp=sharing)
- [Неон](https://drive.google.com/file/d/0B-tnm4ER5l74ZWZaZi1BS3BTWmM/view?usp=sharing)

Не вижу, как можно сделать задуманное. Подбирать параметры и надеяться, что результат совпадет ? Не хочется, т.к. долго и нет никакой гарантии, что получится. Кажется, что надо переформатировать всё под Марс/Неон и жить со стандартным форматерром дальше.

**Comment by aurusov** [comment]
@bogachev-pa @LeKaitoW
Кто что думает ?

**Comment by bogachev-pa** [comment]
Раз хорошего решения нет, то я готов смириться с длиной строк в 120 символов.
Давайте в субботу снова организованно проведем полное форматирование проекта.

**Comment by LeKaitoW** [comment]
А меня и 120 символов устраивает. Удобно,что из коробки, хотя минусом является blame.

**Comment by aurusov** [comment]
Обсудили с Пашей. Решили после мержа [анимации](https://github.com/aurusov/rdo-xtext/issues/145) переформатировать под Неон.

**Comment by bogachev-pa** [comment]
Готово.
