### ISSUE TITLE
Точка с запятой после enum

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#156]
Перастало компилиться

``` erlang
enum Положение {станок_1, станок_2, станок_3, накопитель_1, накопитель_2, тележка_1_н, тележка_1_к, тележка_2_н, тележка_2_к, нигде};
```

Если убрать точку с запятой, то все ok

**Comment by aurusov** [comment]
В документации точка с запятой есть. Чему верить ?

**Comment by bogachev-pa** [comment]
В документации неправильно написано, выходит.

В таком случае, как мы хотим сделать?
1. Обязательно без `;`. Так сейчас.
2. Обязательно с `;`. Не очень хочется, потому что типы их не имеют.
3. Ставить `;` опционально. Так в джаве. Давайте тоже так сделаем тогда?

**Comment by aurusov** [comment]
Пусть будет без `;`. Обновлю документацию.
