### ISSUE TITLE
Средства для графического редактора моделей

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#16]
В таску призываются @yulek1 и @AlexChernov.

В идеальном мире мы найдем удобную библиотеку для решения нескольких задач

<ol>
<li>Графический редактор модели.</li>
<li>Халявная анимация - a-la Arena, где очень клёво перемещались транзакты между блоками. Было удобно отлаживаться, не хватает такого в AnyLogic. Халявная - потому что разработчик ничего не делает для её получения.</li>
<li>Полноценная анимация - созданная ручками.</li>
<li>Размещение на экране элементов управления (кнопок, списков и т.д.), чтобы через них влиять на процесс моделирования.</li>
</ol>

Насколько я вижу пути решения, то для первой необходим графический движок
- простой 2d-движок или мощный OpenGL - не важно, главное чтобы с аффинными преобразования
- вложенные объекты, пересчет их координат относительно родителя
- только вектор, в идеале вообще никакого растра
- поиск объекта по координатам мыши (или даже ближайшего)
- рисовать связи между объектами с обходом препятствий (кто сказал, что модель будет в одну строку, без переносов блоков на следующую ? к примеру, Арена с этим справлялась, AnyLogic - нифига)

Для второй задачи необходимо всё, что и для первой. Плюс:
- ну не хочется заниматься расчетом координат транзакта при движении между блоками. Хочется сказать откуда, куда (по какой ломаной) и с какой скорость. Чтобы начать думать _актерами_, для которых режиссер описывает поведение на сцене, лучше воспользоваться игровыми движками. Да, да, и это давно решенная задача.

Третья задача. Тут сложнее. Фантазия разработчика и всё такое. Это не процессный подход анимировать. Даже не знаю какие требования. Будем вдохновляться AnyLogic - это место у них отличное. Тем более по сравнению с нашими FRM и упомянутой выше Ареной.

Четверая - тоже фиг знает на чем основаться. Хочется, чтобы кнопочки выглядели нативными на разных платформах. В игровых движках этих элементов или вообще нет или они кастомные. Qt выглядит неплохо, но это C++. Думаю, что обойдемся контролами Java, но понятия не имею как их совместить с движком. Будем разбираться по ходу - первые две задачи приоритетные и дают максимальный профит системе.

Что нарыто на текущий момент (присоединяйтесь к поиску)
- ~~[jgraphx](https://github.com/jgraph/jgraphx) - первая задача покрывается идеально, вторая - никак~~
- [libGDX](http://libgdx.badlogicgames.com/) - первая частично, вторая - идеально

**Comment by aurusov** [comment]
@yulek1
Юля, ты можешь совместить libGDX и jgraphx ? Не представляю как заставить одно рисоваться поверх другого. Допускаю, что это очень сложно. Хочется, чтобы ты исследовала этот момент. Начни с кейса, когда главный libGDX.

**Comment by yulek1** [comment]
Сделаю, ориентировочно к среде.(11.06). Jgraphx пробовала, хороший.

**Comment by yulek1** [comment]
Таска лежит в https://github.com/yulek1/TestLibGDX/
Совместились координаты, но как-то странно.

**Comment by yulek1** [comment]
Библиотека, кот может помочь сделать движение: http://www.aurelienribon.com/blog/projects/universal-tween-engine/

**Comment by aurusov** [comment]
призывается @robotxet

**Comment by LeKaitoW** [comment]
Выбранная библиотека: https://eclipse.org/gef/
