### ISSUE TITLE
Отображать информацию о вершине в пятнашках

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#162]
Сейчас появилось отдельное окошко. Его надо доработать
- Статистику по графу ([левая часть](https://github.com/aurusov/rdo-xtext/pull/152#issuecomment-139915116)) вынести в отдельное окно или научиться скрывать. Если второе, то по умолчанию должно быть скрыто.

**Comment by bogachev-pa** [comment]
> Добавить вывод поля с фишками

В основном РДО этого быть не должно, а для плагина уже есть отдельная таска (https://github.com/LeKaitoW/rdo-game5/issues/8).

> Статистику по графу

Когда будет время, хочу сделать из этого красивую таблицу, в которой в том числе можно будет скрывать информацию по графу/вершине.

**Comment by aurusov** [comment]
Да, таска есть. Неудобно, что часть тасок там, часть [тут](https://github.com/aurusov/rdo-xtext/milestones/%D0%9A%D0%BE%20%D0%B2%D1%82%D0%BE%D1%80%D0%BE%D0%B9%20%D0%BB%D0%B0%D0%B1%D0%B5). Прям хоть дубли со ссылками заводи.

Насчет таблицы не понял.

**Comment by aurusov** [comment]
Обновил шапку

**Comment by bogachev-pa** [comment]
Насчет таблицы тогда попробую сделать сначала и потом отпишу.
