### ISSUE TITLE
Добавить валидатор на совпадение идентификаторов с именем модели

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#173]

**Comment by bogachev-pa** [comment]
@aurusov, @LeKaitoW 
Добавил валидацию, но осталась такая проблема: что, если пользователь при выборе шаблона в визарде назовет модель так же, как назван один из элементов в модели? Получается, только что созданная визардом модель не будет валидной.

Мне пока приходит в голову только один вариант: при генерации модели из шаблонов задавать им фиксированные имена. Но вроде планировалось давать пользователю возможность задавать имя модели самому? Если так, можно разрешать задавать имя модели самому только для пустой модели.

Я не в восторге от такого решения, если у вас будут идеи получше, давайте обсудим.

**Comment by aurusov** [comment]
Можно и фиксированные. Отсюда вывод: имя модели не должно жить в одном скопе с идентификаторами. Я всю дорогу говорю, но вы игнорите простой подход, который изначально не позволяет накосячить таким образом:
- пусть модель называется `model`
- если все ресурсы разместить в `model.DB.*`
- а паттерны в `model.KB.*`
- то конфликтов имен вида `model.DB.model.parametr`, где второй `model` - это имя ресурса, быть не должно.

Напомните, почему так не сделано ? Это просто невозможноь или надо таску ставить, чтобы не забывалось ?

**Comment by bogachev-pa** [comment]
Мисклик.

Там есть несколько проблем, попозже распишу их подробно. Отдельную таску не нужно.

**Comment by aurusov** [comment]
Готово ?

**Comment by bogachev-pa** [comment]
Обсудили на консультации, резюмируя:
1. Валидатор готов.
2. [Есть проблема](https://github.com/aurusov/rdo-xtext/issues/173#issuecomment-141895055). Возможное решение: завести фиксированные таблицы недопустимых имен для моделей с шаблонами и проверять их в визарде.
3. Более правильное радикальное решение: по-другому расположить файлы проектов, возможно так, как описано [здесь](https://github.com/aurusov/rdo-xtext/issues/173#issuecomment-141919606). Возможная проблема: придется обращаться к именам идентификаторов на языке `rao` по неудобным путям.

Предлагаю забить на 2 и завести отдельную таску для 3, а эту закрыть.

**Comment by aurusov** [comment]
Эту закрыть полюбому. А вот 2 и 3 про разное
- 2 - Про визард
- 3 - Про то, чтобы разделить объекты модели по **удобный** скопам. Если это решит и (2), то только как бонус. Если для решения 2 через 3 придется сделать неудобные пути - это не то, что нам нужно.

Есть еще и 4
- 4 - скомпилить модель из визарда в фоне, проверить введенное имя с индентификаторами модели

**Comment by aurusov** [comment]
https://github.com/aurusov/rdo-xtext/issues/201
https://github.com/aurusov/rdo-xtext/issues/202
