### ISSUE TITLE
Автоматическое открытие перспективы Rao

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#175]
При запуске Эклипса с РДО

**Comment by LeKaitoW** [comment]
Решение: http://blog.vogella.com/2011/11/02/eclipse-setting-the-default-perspective-via-config-ini/
В нашем случае нужно в файл `eclipse.ini` писать:

```
-perspective
ru.bmstu.rk9.rao.ui.perspective
```

Работает и на Луне, и на двух Марсах. :)

Если дописать в конец файла, то не срабатывает (по ссылке об этом упоминается).
Я пишу перед строчкой:

```
-product
```

**Comment by aurusov** [comment]
Отлично, надо добавить это в мавен

**Comment by LeKaitoW** [comment]
Тогда таска переходит на Лёшу?

**Comment by aurusov** [comment]
Да. А ты хотела бонус ?

**Comment by LeKaitoW** [comment]
Конечно. ;)

**Comment by AlexChernov** [comment]
Пока два варианта:
1. Скопировать файл eclipse.ini из папки eclipse, лежащей рядом, дописать в него перспективу. Если нет такого файла/папки, сборка закончится с ошибкой(раньше создавался архив с папкой `dropins`)
2. Хранить файл `eclipse.ini` так же как и `eclipse` рядом с исходниками. В исходниках хранить не получится, потому что в `eclipse.ini` есть платформозависимая строчка `plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.300.v20150602-1417` поэтому для каждой сборки понадобится создавать такой файл. Зато если его не создать, сборка, как и раньше , создаст архив с папкой `dropins`

**Comment by aurusov** [comment]
Мне нравится первый вариант

**Comment by aurusov** [comment]
Оставь возможность создавать архив только с РДО. Ведь можно завести отдельную задачу в мавене типа `mvb raox-jars` ?
