### ISSUE TITLE
Прореживание в графиках

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#176]
Создаем модель простейшей СМО через визард. Увеличиваем условие остановки по времени на два порядка: `return currentTime >= 7 * 12 * 6000;`. Пытаемся построить график длины очереди.

**Comment by ViktorRakhmatulin** [comment]
Включаюсь в решение бонусной задачи. НАшел в исходниках "PlotFrame.java"
Читаю книгу,смотрю основы синтаксиса. ПОд ночь распишу подробнее этапы выполнения.

**Comment by aurusov** [comment]
ok

**Comment by ViktorRakhmatulin** [comment]
ПРо этапы было громко сказано. Пока затыков нет.

**Comment by ViktorRakhmatulin** [comment]
Не пропал. Книга "философия ява" мала помогла. Базу синтаксиса и понимание классов, методов,обьектов дал сайт: http://study-java.ru/uroki-java/urok-5-sozdanie-i-vyzov-klassa-v-java/
Продолжаю двигаться.

**Comment by aurusov** [comment]
Хорошо

**Comment by ViktorRakhmatulin** [comment]
ПРодолжаю читать книгу. Все изложено последовательно, поэтому скакать по главам не получается. Должен успеть ухватить контейнеры. В принципе весь список тем почти охвачен. Недопонимания будут всплывать по ходу практики. ВРоде все понятно.

**Comment by ViktorRakhmatulin** [comment]
Хинт при наведении мышки на точку графика #343 .Эта задача мне нравится больше.

**Comment by aurusov** [comment]
Этой задачи недостаточно для курсового. Оно идет в комплекте с другими. Посмотреть можно тут https://github.com/aurusov/raox/projects/7#card-237426

**Comment by ViktorRakhmatulin** [comment]
Переменные и сущности

1) Шаг фильтрации(по сколько точек выбираю)
2) Предельное Число точек в отображаемом Dataset
3) индекс последней обработанной точки
4) Dataset для фильтрованного графика
5)  Dataset при переключении графиков
6) Флаг, указывающий на используемый для построения Dataset
7) метод ,реализующий прореживание
  

Проблемы: 
1. «Временное окно» образуется ,когда dataset достиг предельного числа точек и требуется перестроить график.
2. Точность при масштабировании графиков (какие точки должны выводиться?)
Ведь будут же несовпадения с реальными точками,но хинт выведет виртуальную точку.

Предполагаемые методы:
1) Брать кучками и считать среднее значение по точкам
2) Брать кучками и слепливать соседние точки с одинаковыми значениями  по оси Y.

**Comment by aurusov** [comment]
Текущие задачи
- залить код
- пофиксить хинт
- добавить в график 3.000.000 значение, протестировать и понять узкие места, предложить решения
- хочется прореживать только видимые порции исходных данных, а не все

**Comment by ViktorRakhmatulin** [comment]
Протестировал с 3млн точками. Первое построение может занять 3-4 минуты 
Относительно быстро работает,когда график уже построился. И прокрутка ,и масштабирование.
ПОчти не лагает ,когда меняется размер экрана.
Хинт сильно тормозит систему, но я его еще не подправил.

**Comment by ViktorRakhmatulin** [comment]
- настроен Хинт
-поиск идет только среди видимых точек
- исправлены мелкие ошибки
- предложен вариант оформления кода (переименованы переменные)
- убрал код, который не использовался для построения графиков
--URLgenerator
--Неиспользуемый ToolTip ,
--Дополнительный прогон отрисовщика для нанесения специальных меток на точки  

В итоге подсистема работает еще шустрее и кушает меньше памяти.
