### ISSUE TITLE
Вывод чисел и перечислений в команде text

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#181]
Сейчас только через [явное](https://github.com/aurusov/rdo-xtext-models/commit/3b81f096cfe564796e76df670bf8ad10a3935ef8#diff-f16bf73f68231cfe1f7b2f14eca97a02R420) преобразование в строку

``` erlang
text(60, 5, 150, 25, color(255, 255, 255), color(0, 0, 0), Double.toString(currentTime));
```

Хочется

``` erlang
text(60, 5, 150, 25, color(255, 255, 255), color(0, 0, 0), currentTime);
```

В том числе для перечислений. Сейчас для них приходится писать [вот такое](https://github.com/aurusov/rdo-xtext-models/commit/3b81f096cfe564796e76df670bf8ad10a3935ef8#diff-f16bf73f68231cfe1f7b2f14eca97a02R340).

**Comment by bogachev-pa** [comment]
`Done`
