### ISSUE TITLE
Добавить компоненты в палетту инструментов 

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#187]
Нам нужна паллета, состоящая из
- `Select`
- `Marquee`
- `Connection`
- Закладки компонент с элементами процессного подхода
  - `Generate`
  - `Seize`
  - `Advance`
  - `Release`
  - `Terminate`
  - `Resources`

**Comment by LeKaitoW** [comment]
Заготовка палитры:
![screenshot from 2015-10-10 17 29 43](https://cloud.githubusercontent.com/assets/10632455/10411630/88eb1cd6-6f74-11e5-9996-23596645f68e.png)

Не хватает: `Connection`

**Comment by aurusov** [comment]
Кажется, что с палеттой всё. Предлагаю закрыть задачу. `Connection` и блоки лучше делать в отдельных тасках.

**Comment by LeKaitoW** [comment]
Окей.
Тогда буду заводить таски по блокам.
