### ISSUE TITLE
Нельзя запустить модель из анимации

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#189]
Если активно окно анимации, то вываливается довольно ожидаемая для разработчика ошибка. Но она нифига не очевидна для пользователя. Если зачинить сложно, то оставим так. Прошу посмотреть срочно, т.к. блочит [Руководство пользователя](https://github.com/aurusov/rdo-xtext/issues/26).
![2015-09-26 20-17-26 2](https://cloud.githubusercontent.com/assets/5585202/10118837/11a1dd06-648c-11e5-9fc8-24c5ac9830c8.png)

**Comment by bogachev-pa** [comment]
Тут все сложнее. Как понять, какой проект запускать, если активным является окно анимации, ведь оно может относиться к любому проекту?

Сейчас запускается проект активного эдитора, для этого проверка и сделана.

**Comment by aurusov** [comment]
Да, в общем случае решить сложно. Но решение есть в частных случаях
- если только одна модель, то все просто
- если несколько, то
  - последнюю запущенную
  - выбранную в проекте
  - ту, от которой текущий фрейм в анимации (этот вариант покрывает все imho)

Сейчас хотя бы сделать для одной модели. Это сложно ?

**Comment by bogachev-pa** [comment]
Не правильнее ли будет анимацию сделать эдитором (как графики)?

Только тогда встает проблема, как его правильнее открывать.

**Comment by aurusov** [comment]
Мне не совсем понятны сложности едитор/не едитор. По сути это не редактор, как и графики, но окно, которое должно быть большим, а не ютиться в доках. Я так понимаю, что это термин эклипса для всех `больших` окон ? Странное название, попахивает ошибкой проектирования. ~~И открываются они не через View, а через файлы проекта ?~~ Можно ли открыть такое окно через view ? Если нет, то можно сделать кнопку на тулбаре.

**Comment by bogachev-pa** [comment]
Еще одно отличие эдитора - он имеет привязку к проекту. По-хорошему, он должен соответствовать какому-то файлу в этом проекте (не уверен, что использовать его без файла - хороший стиль), плюс, да, он может быть помещен в отдельную область.

Открываются либо через файлы проекта либо программно.

Вообще, наверное, стоит оставить его в качестве `View`.
Я предлагаю сделать так:
- если открыт один проект, запускать его
- если открыто несколько, запускать последний запущенный (как-то придется его запоминать, похоже), но сначала выводить пользователю сообщение `No editor opened, cannot choose project to run. Run "<project_name>"?` с кнопками `ok` и `cancel`

Почему именно последнюю запущенную:
- выбранную в проекте - непонятно, что это значит. Запускается проект, а не модель.
- ту, от которой текущий фрейм в анимации - это всегда последняя запущенная, в анимации не будет фреймов от прошлых запусков

**Comment by aurusov** [comment]
Хорошо
