### ISSUE TITLE
Некорретно работает автоматическое переименование

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#194]
1_._ С енумами

``` erlang
enum Положение {
    станок_1,
    станок_2,
    станок_3,
}
```

Если встать на `станок_1` и нажать `Shift + Alt + R`, то переименование не активизируется.

2_._ С ресурсами
Имя ресурса можно переименовать с помощью `Shift + Alt + R`.
Встаем на `Накопитель_2` -> `накопитель_2`

``` erlang
resource Накопитель_2 = Накопители.create(2, Положение.накопитель_2, *, *);
```

В релевантных ресурсах всё хорошо

``` erlang
relevant накопитель = накопитель_2.select(any);
```

В других местах плохо

``` erlang
set terminateCondition() {
    return Накопитель_2.текущее_количество == 10 or currentTime >= 1000;
}
```

``` erlang
text(Накопитель_2.текущее_количество, 350, 235, Color.BLACK);
```

**Comment by bogachev-pa** [comment]
Я, честно говоря, даже не знал, что оно работает.

Так или иначе, сейчас проверил, оно работает только вне языка выражений, т.е. там, где у нас честна описана грамматика. Еще одна проблема, которую решит только `xbase`.

**Comment by aurusov** [comment]
Ну значит у них с https://github.com/aurusov/rdo-xtext/issues/195 одна проблема

**Comment by bogachev-pa** [comment]
Отредактировал заголовок и первое сообщение, чтобы обобщить таску.

**Comment by bogachev-pa** [comment]
Неактуально в связи с `xbase`.
