### ISSUE TITLE
Переименование ресурса

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#195]
Имя ресурса можно переименовать с помощью `Shift + Alt + R`.
Встаем на `Накопитель_2` -> `накопитель_2`

``` erlang
resource Накопитель_2 = Накопители.create(2, Положение.накопитель_2, *, *);
```

В релевантных ресурсах всё хорошо

``` erlang
relevant накопитель = накопитель_2.select(any);
```

В других местах плохо

``` erlang
set terminateCondition() {
    return Накопитель_2.текущее_количество == 10 or currentTime >= 1000;
}
```

``` erlang
text(Накопитель_2.текущее_количество, 350, 235, Color.BLACK);
```

**Comment by bogachev-pa** [comment]
Ответил в другой таске, это общая проблема:
https://github.com/aurusov/rdo-xtext/issues/194#issuecomment-144537624
