### ISSUE TITLE
Добавить совместимый со старым РДО способ отображения номеров временных ресурсов в трассировке

### ISSUE THREAD

**Issue by k-alexandrovsky** [LeKaitoW/raox#20]
Связан с:
- [ ] #12

**Comment by aurusov** [comment]
Черкани пару мыслей о том как это сделать. То, что было в #12.

**Comment by k-alexandrovsky** [comment]
Все индексы с недавнего времени хранят номера записей в общем списке `Database`. Для каждого временного ресурса берется номер последней записи (при условии, что она `Erase`) и первой (она всегда `Create`). Берутся пары `<Номер ресурса, номер записи>` и заносятся в массив. Массив сортируется по номерам записей (хронология!). Потом итерируем этот массив, каждая `Create` увеличивает каунтер, если список вакантных номеров свободен, или берет номер из их очереди (как в РДО). Каждая `Erase` предоставляет вакантный номер. В итоговую мапу заносится связка `<Номер по порядку, легаси-номер>`. В конце трассировщик пользуется этим соответствием для генерации совместимого вывода.

**Comment by bogachev-pa** [comment]
Надо обратить внимание вот на [этот](https://github.com/bogachev-pa/rdo_studio/commit/a00a498998cdf8f5276ae4d5d9797baadc9d05c4) коммит в моем форке rdo_studio и комментарии в нем.
Я правильно понимаю, что именно такую схему мы реализуем в качестве легаси (новосозданный ресурс получает наименьший из свободных айдишников) и не стремимся получить совсем-совсем легаси?

**Comment by aurusov** [comment]
Нам нужна совместимость в каждом символе трассировки, чтобы прошли тесты.

**Comment by bogachev-pa** [comment]
Дело в том, что номера временных ресурсов в моем и вашем форке отличаются.
Если вкратце, то в вашем номер нового ресурса это номер последнего освободившегося ресурса, а в моем это наименьший свободный номер на данный момент.

Если воспроизводим схему из моего форка, то мне нужно смержиться с вашим, а вам затем принять пул реквест.

**Comment by aurusov** [comment]
Лучше твою, мержись.

**Comment by bogachev-pa** [comment]
Задача решена в рамках коммита https://github.com/bogachev-pa/rdo-xtext/commit/7d85808d9290b964fbbc9b87c772bc11fe5239a2

**Comment by aurusov** [comment]
https://github.com/bogachev-pa/rdo-xtext/issues/6#issuecomment-63021267

**Comment by bogachev-pa** [comment]
Возможно, рано закрыл, я еще не тестировал на heidel и барже.
Как протестирую, сюда напишу.

**Comment by k-alexandrovsky** [comment]
Да я как то решил, что у этой issue узкая формулировка, а основной будем считать https://github.com/bogachev-pa/rdo-xtext/issues/6
