### ISSUE TITLE
Расположить объеты с своих скопах

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#202]
Предположим, что у нас работает code completion. Тогда все объекты модели вываливаются одним списокм. Кажется, что это неудобно. Предлагается размещать объекты в своих скопах, например
- `model.resources.*`
- `model.events.*`
- `model.operations.*`
- `model.results.*`
- `model.frames.*`

Как бонус, это станет альтернативным решением для https://github.com/aurusov/rdo-xtext/issues/201. Например,
- пусть модель называется `model`
- если все ресурсы разместить в `model.resources.*`
- то конфликтов имен вида `model.resources.model.parameter`, где второй `model` - это имя ресурса, быть не должно

Будет ли этим удобно пользоваться ? Чтобы проверить, надо запилить нормальный язык выражений, чтобы заработал code completion.

**Comment by bogachev-pa** [comment]
Чтобы потом не забыть: это решено в ветке с интеграцией `xbase`.
