### ISSUE TITLE
Упростить смену версии

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#206]
Кажется, что будет проще всего настроить команду

```
mvn release <release_number>
```

, которая будет изменять номер релиза в поме и всех манифестах.

**Comment by AlexChernov** [comment]
```
mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=2.9.0 -Dartifacts=parent,ru.bmstu.rk9.rao,ru.bmstu.rk9.rao.lib,ru.bmstu.rk9.rao.tests,ru.bmstu.rk9.rao.ui
```

Эта команда автоматически меняет версию во всех `pom.xml` и `MANIFEST.MF`. Из минусов: придется отказаться от переменной `${rao-version}`, которой сейчас задается версия, из-за чего при изменении версии будут меняться 10 файлов.

**Comment by aurusov** [comment]
Это что ?

**Comment by AlexChernov** [comment]
Обновил комментарий выше

**Comment by aurusov** [comment]
Круто. Пул-реквест ?

**Comment by AlexChernov** [comment]
Сейчас уберу ${rao-version}, обновлю `gitflow.md` и сделаю пул-реквест

**Comment by aurusov** [comment]
> Из минусов: придется отказаться от переменной `${rao-version}`, которой сейчас задается версия, из-за чего при изменении версии будут меняться 10 файлов.

Поясни всетаки, как правильно работать с версиями. Я думал, что запуская `mvn package` версия определится через гит. Если так, то зачем торчать наружу `mvn release <release_number>` ?

**Comment by AlexChernov** [comment]
```
mvn release <release_number>
```

Имелась в виду команда

```
mvn release:update-versions -DdevelopmentVersion=[version]
```

Это запуск команды плагина `maven-release-plugin`, суть которой поменять pom.xml, MANIFEST.MF, т.е. **назначить** версию (автоматизировать `release/version` в https://github.com/aurusov/rdo-xtext/blob/release/current/gitflow.md)
Вместо нее будет использоваться команда

```
mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=2.9.0 -Dartifacts=parent,ru.bmstu.rk9.rao,ru.bmstu.rk9.rao.lib,ru.bmstu.rk9.rao.tests,ru.bmstu.rk9.rao.ui
```

Просто другой плагин, суть таже
В `mvn package` версия **определятся** на основе `git describe --tags`, т.е. версия, которой называется архив. И она может не совпадать с версией в манифесте.

**Comment by aurusov** [comment]
Т.е. вызывая `mvn package` я получу только версию для _имени архива_. Она не будет применена к помам и манифестам ?

**Comment by AlexChernov** [comment]
Да, но можно вызывать этот плагин на каком-либо шаге сборки, тогда версия будет назначаться и для */pom.xml */MANIFEST.MF, а следовательно и для *.jar

**Comment by aurusov** [comment]
Это не можно, а нужно сделать. Понимаешь разницу ?
Как я вижу ситуацию
_1. `mvn package` собирает архив с плагинами
- Имя архива содержит версию из гита
- Сами плагины тоже, обязательно, содержат версию из гита. Как может быть по другому ? Сейчас в этом месте ошибка ?

_2. `mvn package -Declipse-path -Dtarget-os -Dtarget-bitness` собирает Эклипс с плагином
- Имя архива содержит версию из гита
- Сами плагины тоже, обязательно, содержат версию из гита

И все. `mvn release` торчать наружу не должен. Он может быть для внутреннего удобства, например, чтобы продвинуть версию для нового релиза. Новый [релиз](https://github.com/aurusov/rdo-xtext/releases) _исходников_ у нас выпускается руками. Не путай с автосборкой и деплоем _бинарников_.

**Comment by AlexChernov** [comment]
Версия не ставится в манифесте:
[ERROR] Version 2.3.1-201-g30ca097 is not valid for MANIFEST.MF
[Bundle-Version: 1.2.3.four](http://wiki.osgi.org/wiki/Bundle-Version)

**Comment by aurusov** [comment]
А если через точки `2.3.1.201.g30ca097` ?

**Comment by bogachev-pa** [comment]
Исходя из того, что я читал о версиях эклипсовских плагинов, может сработать что-то вроде `2.3.1.201-g30ca097`

**Comment by AlexChernov** [comment]
Попробую завтра

пятница, 23 октября 2015 г. пользователь Pavel Bogachev написал:

**Comment by AlexChernov** [comment]
`2.3.1.201-g30ca097` - можно
`2.3.1.201.g30ca097` - нельзя
`2.3.1.g30ca097` - можно

**Comment by aurusov** [comment]
Первый отлично смотрится.

**Comment by aurusov** [comment]
Сейчас выпускал релиз 2.8. Не получилось изменить версию ни через
`mvn release <release_number>`
ни через
`mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=2.9.0 -Dartifacts=parent,ru.bmstu.rk9.rao,ru.bmstu.rk9.rao.lib,ru.bmstu.rk9.rao.tests,ru.bmstu.rk9.rao.ui`

Вместо манифестов меняются помы:

``` bash
drobus@drobus-P55-UD3R:~/git/rdo-xtext$ git status
    изменено:      assembly/pom.xml
    изменено:      pom.xml
    изменено:      ru.bmstu.rk9.rao.lib/pom.xml
    изменено:      ru.bmstu.rk9.rao.tests/pom.xml
    изменено:      ru.bmstu.rk9.rao.ui/pom.xml
    изменено:      ru.bmstu.rk9.rao/pom.xml
```

Причем `git diff` довольно странный.

**Comment by AlexChernov** [comment]
Потому что
1. Эта ветка не полита, чтобы diff был не странный
2. Версии помов и манифестов были разные. Они меняются вместе, только если до изменения были одинаковые, что тоже произошло, потому что эта ветка не подлита
