### ISSUE TITLE
Предлагать перспективу

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#207]
При создании нового проекта лучше спросить нужно ли открыть перспективу `Rao`. Поведение должно напоминать создание Java-проекта.

**Comment by asquad** [comment]
![xkpyvxw](https://cloud.githubusercontent.com/assets/1443857/11019681/8a82f940-8614-11e5-8d0f-b95b42c04df4.png)
Прикрутил стандартное окошко. Все работает.
Есть вопрос: я достаю из настроек среды значение, показывающее, прожимал ли пользователь чекбокс "Запомнить моё решение" ранее. Делаю это также, как делал визард создания ява-проекта - через internal-библиотеки. При этом вешается варнинг, говорящий, что данная либа не принадлежит api. Это потенциально опасно? Вечером поглубже поковыряю стаковерфлоу и документацию, но беглым просмотром не нашёл возможность получить настройки через апишные классы.

**Comment by bogachev-pa** [comment]
Без кода трудно что-то ответить. Поребейзись на последний `release/current` и открывай пул-реквест на ветку `release/2.11`.

В сообщении к коммиту укажи имя таски:
`<описание коммита> (aurusov/rdo-xtext#207)`

**Comment by asquad** [comment]
Окей, как до дома доберусь.

**Comment by aurusov** [comment]
> Это потенциально опасно?

Эклипс в любой момент может поменять internal-библиотеку. Скорее всего, ворниг предупреждает об этом (не читал его). Конечно, лучше найти api-решение. Если поиск ничего не даст, то оставим так.
