### ISSUE TITLE
Включить Xbase в грамматику

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#208]
После включения можно будет писать выражения на xbase, должен заработать code complete, но сломается компиляция в Java-код.

**Comment by bogachev-pa** [comment]
Готово.

**Comment by aurusov** [comment]
Заработал `code complete` ? Можешь скинуть пару скринов с примерами ?

**Comment by bogachev-pa** [comment]
Т.к. никаких маппингов в джава-код я на тот момент еще не делал, то он был довольно пустой, подсказывал только ключевые слова самого `xbase`.

Сейчас (после https://github.com/bogachev-pa/rdo-xtext/commit/c4f7f5301894e9df27e52e7aba8346024f6b79ed) работает уже вот так:
![2015-10-19-204809_1366x768_scrot](https://cloud.githubusercontent.com/assets/6528492/10586054/13969038-76a3-11e5-9d8c-a158113d4641.png)

**Comment by aurusov** [comment]
Хорошо
