### ISSUE TITLE
Сбор статистики через watchParameter для параметров, тип которых определен через enum

### ISSUE THREAD

**Issue by zvedenyuk** [LeKaitoW/raox#210]
Модель `bggt`:

``` erlang
enum Состояние_станка {СВОБОДЕН, РАБОТАЕТ}
type Станок {
    int номер;
    Состояние_станка состояние;
}
resource станок_1 = Станок.create(1, Состояние_станка.СВОБОДЕН);
result номерстанка = watchParameter(станок_1.номер);
result состояниестанка = watchParameter(станок_1.состояние);
```

В данном случае строка:

``` erlang
result номерстанка = watchParameter(станок_1.номер);
```

Срабатывает нормально. В то время как строка:

``` erlang
result состояниестанка = watchParameter(станок_1.состояние);
```

Даёт ошибку:

```
An internal error occurred during: "Building Rao model".
java.lang.NullPointerException
```

**Comment by aurusov** [comment]
Включите оформление тасок, как у https://github.com/aurusov/rdo-xtext/issues/209. Таску можно редактировать.

**Comment by zvedenyuk** [comment]
Сделал

**Comment by bogachev-pa** [comment]
Сбор статистики по параметрами типа `enum` уже обсуждали (https://github.com/bogachev-pa/rdo-xtext/issues/11), это нужно имплементить как отдельную фичу.

На данный момент можно сделать валидатор, запрещающий использование енумов в `watchParameter()`.

**Comment by aurusov** [comment]
> нужно имплементить как отдельную фичу.
> можно сделать валидатор

Что-же не завел таски ?

Эту закрываю, потому что распилил на
- https://github.com/aurusov/rdo-xtext/issues/217
- https://github.com/aurusov/rdo-xtext/issues/218
