### ISSUE TITLE
Настроить свойства rao-плагинов

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#212]
![2015-10-12 23-13-45 eclipse installation details](https://cloud.githubusercontent.com/assets/5585202/10437642/24b7757e-7137-11e5-82b2-1d1a91ccf8c8.png)

**Comment by bogachev-pa** [comment]
Настраиваются [здесь](https://github.com/aurusov/rdo-xtext/blob/release/current/ru.bmstu.rk9.rao.ui/META-INF/MANIFEST.MF#L4) и в аналогичных местах. А что там должно быть?

**Comment by aurusov** [comment]
Главное не что, а как: единообразно для левого столбца. Сейчас в _этом_ ошибка. В нём лучше написать `rdostudio.com`. В правом - _краткое_ описание каждого плагина.

**Comment by aurusov** [comment]
Название продукта `Rao X`
Название компании `rdostudio.com`
Название бинарников/исходников/репы гитхаба/задач на Дженкинсе `raox`
Название языка `Rao` или `РДО`
