### ISSUE TITLE
Ошибка инициализации double целочисленным значением

### ISSUE THREAD

**Issue by GavrilenkovRK9** [LeKaitoW/raox#220]
Если завести параметр ресурса типа `double`

``` erlang
double времяЗагрузки = 0;
```

или константу

``` erlang
constant double qqq = 12;
```

, а инициализировать ее как целое число, то вылетит ошибка типа
![typemismatch](https://cloud.githubusercontent.com/assets/15154787/10547418/79014766-7445-11e5-9049-701ac9e0d08c.png)
В тоже время, инициализация переменной типа `double` целым значением не вызывает ошибок, если написать это, например, в теле события `Событие_прихода_клиента`.

``` erlang
enum Состояние_парикмахера {Свободен, Занят}

type Парикмахерские {
    Состояние_парикмахера состояние_парикмахера;
    int количество_в_очереди;
    int количество_обслуженных;
    //система выдает ошибку о несоответствии типов:
        double времяЗагрузки = 0;
        //ошибка исчезает:
        //double времяЗагрузки = 0.0;
}

resource Парикмахерская = Парикмахерские.create(Состояние_парикмахера.Свободен, 0, 0, *);

event Событие_прихода_клиента() {
    double qqq = 2;// ошибки нет
    Событие_прихода_клиента.plan(currentTime + Интервал_прихода.next());
    Парикмахерская.количество_в_очереди++;
}

operation Образец_обслуживания_клиента() {
    relevant _Парикмахерская = Парикмахерская.select(_Парикмахерская.состояние_парикмахера == Состояние_парикмахера.Свободен
            and _Парикмахерская.количество_в_очереди > 0);
    set duration() {
        return Длительность_обслуживания.next();
    }
    set begin() {
        _Парикмахерская.количество_в_очереди--;
        _Парикмахерская.состояние_парикмахера = Состояние_парикмахера.Занят;
    }
    set end() {
        _Парикмахерская.состояние_парикмахера = Состояние_парикмахера.Свободен;
        _Парикмахерская.количество_обслуженных++;
    }
}

dpt model {
    activity Обслуживание_клиента checks Образец_обслуживания_клиента();
}

sequence Интервал_прихода = double legacy exponential(123456789, 1/30.0);
sequence Длительность_обслуживания = double legacy uniform(123456789, 20, 40);

set init() {
    Событие_прихода_клиента.plan(currentTime + Интервал_прихода.next());
}

set terminateCondition() {
    return currentTime >= 7 * 12 * 60;
}

result Занятость_парикмахера = watchState(Парикмахерская.состояние_парикмахера == Состояние_парикмахера.Занят);
result Длина_очереди = watchParameter(Парикмахерская.количество_в_очереди);
result Всего_обслужено = getValue(Парикмахерская.количество_обслуженных);
result Пропускная_способность = getValue(Парикмахерская.количество_обслуженных / currentTime * 60);
result Длительность_работы = getValue(currentTime / 60);
```

**Comment by aurusov** [comment]
Текст модели лучше приводить полностью. Потому что
- меньше делать и думать, чтобы повторить ошибку
- модель в визарде может поменяться

**Comment by GavrilenkovRK9** [comment]
Полный текст модели с ошибкой:

enum Состояние_парикмахера {Свободен, Занят}

type Парикмахерские {
	Состояние_парикмахера состояние_парикмахера;
	int количество_в_очереди;
	int количество_обслуженных;
	double времяЗагрузки = 0;
}

resource Парикмахерская = Парикмахерские.create(Состояние_парикмахера.Свободен, 0, 0, *);

event Событие_прихода_клиента() {
	double qqq = 2;
	Событие_прихода_клиента.plan(currentTime + Интервал_прихода.next());
	Парикмахерская.количество_в_очереди++;
}

operation Образец_обслуживания_клиента() {
	relevant _Парикмахерская = Парикмахерская.select(_Парикмахерская.состояние_парикмахера == Состояние_парикмахера.Свободен
			and _Парикмахерская.количество_в_очереди > 0);

	set duration() {
		return Длительность_обслуживания.next();
	}
	set begin() {
		_Парикмахерская.количество_в_очереди--;
		_Парикмахерская.состояние_парикмахера = Состояние_парикмахера.Занят;
	}
	set end() {
		_Парикмахерская.состояние_парикмахера = Состояние_парикмахера.Свободен;
		_Парикмахерская.количество_обслуженных++;
	}
}

dpt model {
	activity Обслуживание_клиента checks Образец_обслуживания_клиента();
}

sequence Интервал_прихода = double legacy exponential(123456789, 1/30.0);
sequence Длительность_обслуживания = double legacy uniform(123456789, 20, 40);

set init() {
	Событие_прихода_клиента.plan(currentTime + Интервал_прихода.next());
}

set terminateCondition() {
	return currentTime >= 7 * 12 * 60;
}

result Занятость_парикмахера = watchState(Парикмахерская.состояние_парикмахера == Состояние_парикмахера.Занят);
result Длина_очереди = watchParameter(Парикмахерская.количество_в_очереди);
result Всего_обслужено = getValue(Парикмахерская.количество_обслуженных);
result Пропускная_способность = getValue(Парикмахерская.количество_обслуженных / currentTime * 60);
result Длительность_работы = getValue(currentTime / 60);

**Comment by GavrilenkovRK9** [comment]
А как сделать, чтобы весь вставленный в сообщение код отражался в особой области, а не только отдельные куски кода?

**Comment by GavrilenkovRK9** [comment]
полный текст модели с ошибками:
```
enum Состояние_парикмахера {Свободен, Занят}

type Парикмахерские {
	Состояние_парикмахера состояние_парикмахера;
	int количество_в_очереди;
	int количество_обслуженных;
	//система выдает ошибку о несоответствии типов:
        double времяЗагрузки = 0;
        //ошибка исчезает:
        //double времяЗагрузки = 0.0;
}


resource Парикмахерская = Парикмахерские.create(Состояние_парикмахера.Свободен, 0, 0, *);

event Событие_прихода_клиента() {
	double qqq = 2;// ошибки нет
	Событие_прихода_клиента.plan(currentTime + Интервал_прихода.next());
	Парикмахерская.количество_в_очереди++;
}

operation Образец_обслуживания_клиента() {
	relevant _Парикмахерская = Парикмахерская.select(_Парикмахерская.состояние_парикмахера == Состояние_парикмахера.Свободен
			and _Парикмахерская.количество_в_очереди > 0);
	set duration() {
		return Длительность_обслуживания.next();
	}
	set begin() {
		_Парикмахерская.количество_в_очереди--;
		_Парикмахерская.состояние_парикмахера = Состояние_парикмахера.Занят;
	}
	set end() {
		_Парикмахерская.состояние_парикмахера = Состояние_парикмахера.Свободен;
		_Парикмахерская.количество_обслуженных++;
	}
}

dpt model {
	activity Обслуживание_клиента checks Образец_обслуживания_клиента();
}

sequence Интервал_прихода = double legacy exponential(123456789, 1/30.0);
sequence Длительность_обслуживания = double legacy uniform(123456789, 20, 40);

set init() {
	Событие_прихода_клиента.plan(currentTime + Интервал_прихода.next());
}

set terminateCondition() {
	return currentTime >= 7 * 12 * 60;
}

result Занятость_парикмахера = watchState(Парикмахерская.состояние_парикмахера == Состояние_парикмахера.Занят);
result Длина_очереди = watchParameter(Парикмахерская.количество_в_очереди);
result Всего_обслужено = getValue(Парикмахерская.количество_обслуженных);
result Пропускная_способность = getValue(Парикмахерская.количество_обслуженных / currentTime * 60);
result Длительность_работы = getValue(currentTime / 60);
```

**Comment by bogachev-pa** [comment]
Кажется, в качестве теста компиляции достаточного этого:
```erlang
enum Состояние_парикмахера {Свободен, Занят}

type Парикмахерские {
	Состояние_парикмахера состояние_парикмахера;
	int количество_в_очереди;
	int количество_обслуженных;
	//система выдает ошибку о несоответствии типов:
	double времяЗагрузки = 0;
	//ошибка исчезает:
	//double времяЗагрузки = 0.0;
}
```

Точнее, даже так:
```erlang
type 
```

**Comment by bogachev-pa** [comment]
Чтобы потом не забыть: это исправлено в ветке с `xbase`.
