### ISSUE TITLE
Добавить блок Generate

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#224]
- [x] Задать геометрию/форму (shape) отличную от квадрата
  - Arena Simulatiuon System Create
  - Gensym ReThink blocks
  - Anylogic Source
- [x] Вывести имя блока
- [x] Вывод имени блока сделать опциональным
- [x] Добавить смену цвета

**Comment by LeKaitoW** [comment]
Пример:
![screenshot from 2015-10-19 22 55 11](https://cloud.githubusercontent.com/assets/10632455/10589533/816b6d02-76b4-11e5-9508-adecaf6b8d4a.png)

Необходимо задать элементам постоянные размеры (запретить resize) и затем отцентрировать имя блока.

**Comment by aurusov** [comment]
1. Почему надо запретить `resize` ?
2. Почему бы не отцентрировать независимо от первого утверждения ?

**Comment by aurusov** [comment]
Надеюсь, это не картинки, а полигон ?

**Comment by LeKaitoW** [comment]
> Почему надо запретить resize ?

А зачем нам блоки на весь экран? Можно ведь добавить опцию а-ля "Отображать блоки: большие/средние/маленькие", но разрешенный ресайз выглядит странно. :/

> Почему бы не отцентрировать независимо от первого утверждения ?

Потому что с фиксированными значениями это удобнее делать.

> Надеюсь, это не картинки, а полигон ?

Полигон.

**Comment by aurusov** [comment]
> А зачем нам блоки на весь экран? Можно ведь добавить опцию а-ля "Отображать блоки: большие/средние/маленькие", но разрешенный ресайз выглядит странно. :/

Это зависит от пожелания юзера. Не вижу причин ограничивать его в этом месте. Движок нам это дает из коробки. Нужны веские причины для обратного.

> Потому что с фиксированными значениями это удобнее делать.

Т.е. твой алгоритм будет заточен на фиксированную ширину блока, например, 100 пикселей ?
