### ISSUE TITLE
Добавить сборку только джарников

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#226]
- [x] Изменить сборку по умолчанию: Собрать все jar, перенести их в одну папку. Никаких архивов, никакого эклипса.
- [x] Завести задачу на Дженкинсе, которая заканчивается выгрузкой архива. Имя плагина не должно зависеть ни от платформы, ни от разрядности, например, `raox-2.7.1-plugins.zip`.
- [x] Завести новый профиль `package-as-eclipse-dropins`,  который бы срабатывал, если параметру `-Declipse-path` присвоено какое-либо значение. Сборка описана в (aurusov/rdo-xtext#131)

**Comment by AlexChernov** [comment]
Это выглядит, как поведение по умолчанию, без профиля.  Кажется, что сборка, описанная в aurusov/rdo-xtext#131 должна быть отдельным профилем, который бы срабатывал, если параметру `-Declipse-path` присвоено какое-либо значение.

**Comment by aurusov** [comment]
Да, звучит разумно. Т.е. оно уже и так работает ? Осталось настроить Дженкинс ?

**Comment by AlexChernov** [comment]
Обновил шапку
