### ISSUE TITLE
Обновить репу

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#23]
- обновить https://github.com/LeKaitoW/rdo-xtext/tree/master до мастера https://github.com/aurusov/rdo-xtext/tree/master
- удалить https://github.com/LeKaitoW/rdo-xtext/tree/feature/plot_font
- переименовать https://github.com/LeKaitoW/rdo-xtext/tree/feature/graphic_editor -> https://github.com/LeKaitoW/rdo-xtext/tree/feature/graphic_process или во что-то со словом `process`

**Comment by aurusov** [comment]
тут же всё ?

**Comment by LeKaitoW** [comment]
Только ветка так и осталась не переименованной. Хотя мы это обсуждали на консультации, когда я мержила эту ветку с `process`

**Comment by aurusov** [comment]
Не помню до чего договорились, но переименовать ветку можно прямо через гитхаб. Минутное дело же.

**Comment by LeKaitoW** [comment]
Можно закрывать?
