### ISSUE TITLE
Неявное приведение integer к real не работает

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#23]
Если тип параметра ресурса real, а при его создании мы передаем ему интовое число, модель не собирается.
Например,
это работает:

```
$Resource_type SomeType: permanent
$Parameters
    realParam: real
$End

$Resources
   someRes = SomeType(1.0);
$End
```

А это падает:

```
$Resource_type SomeType: permanent
$Parameters
    realParam: real
$End

$Resources
   someRes = SomeType(1);
$End
```

Ошибка выводится в файле <имя_модели>Model:

```
The constructor SomeType(int) is undefined
```

Кирилл, поставь лэйбл bug, т.к. я в твоем форке не могу.

**Comment by k-alexandrovsky** [comment]
Да валидации выражений вообще нет. Еще модель умеет

``` java
someRes = SomeType(true + "something" * 4.5);
```

И это сгенерится в такую же некомпилируемую чепуху, конечно же.
Так что это не баг, это отсутствие вменяемого языка выражений. Я сейчас пытаюсь перейти на xbase, но там нужно перелопатить очень много всего, переписать грамматику и написать правила преобразования в модель на джаве, и это станет частью генератора.

**Comment by bogachev-pa** [comment]
Таска потеряла смысл, валидация выражений будет решаться средствами `xbase`.
