### ISSUE TITLE
Структура rao-проекта с использованием xbase

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#230]
Необходимо продумать и заимплементить структуру проекта: из каких он будет состоять пакетов и классов.

**Comment by aurusov** [comment]
Набросаешь своё видение или от меня ждешь ?

**Comment by bogachev-pa** [comment]
Набросаю. Ваше мнение примерно помню, если не лень, зафиксируйте тоже письменно, будет удобно.

**Comment by bogachev-pa** [comment]
Более-менее устоялась. Классы по именам файлов, в них все элементы модели представлены полями/методами/вложенными классами. Все классы в одном `package`.
