### ISSUE TITLE
Удаление старых деплоев

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#239]
- [x] Нужен питонячий скрипт, который по ftp удаляет устаревшие выкладки
- [x] Прописать его вызов на Дженкинсе

**Comment by AlexChernov** [comment]
Ок

**Comment by aurusov** [comment]
Я вот думаю, не вытащить ли этот файлик в отдельный репозитарий. Ведь после появления плагина пятнашек придется его изменять. Получится, что эта репа будет знать про соседнюю. Склоняюсь в переносу.

**Comment by aurusov** [comment]
Перенёс https://github.com/aurusov/raox-deploy

А ты `ok` для пул-реквеста написал ?
