### ISSUE TITLE
Репозиторий с джарниками РДО

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/raox#244]
Для
- сборки [Game5](https://github.com/aurusov/raox-game5)
- сборки любых плагинов в последующем
- [создания архива с Эклипсом](https://github.com/aurusov/raox-deploy/issues/1)

хочется выкачивать джарники РДО из мавен-репозитария. При этом, собирать джарники и инсталить в мавен нужно тогда, когда в мавене лежит более страя версия, чем есть в матсер-бранче гита.

**Comment by aurusov** [comment]
Зачем заводить. Джарники собираются тут
http://rdo.rk9.bmstu.ru:81/job/raox-plugins/

**Comment by aurusov** [comment]
Еще актуально ?

**Comment by LeKaitoW** [comment]
Если текущий вариант (при сборке любого плагина требуется предварительно собирать само рдо) является постоянным, то кажется неактуальным.

**Comment by aurusov** [comment]
Я только за. Леша ?

**Comment by bogachev-pa** [comment]
Мне это кажется неудобным. Сейчас получается, что чтобы собрать плагин через мавен нужно сначала самому собрать рдо (ещё и версию самому правильную найти). Вариант с выкачиванием рдо нужной версии через мавен намного правильнее, на мой взгляд. Но я не знаю, насколько сложно создать свой внешний репозиторий и включить его в мавен. Это, скорее, вопрос к Леше. Если несложно, то я за то, чтобы таска была сделана.

**Comment by aurusov** [comment]
У нас нет возможности открыть еще один порт для мавена на кафедральном сервере. Если получится повесить на 80 или 81 порт (на них уже крутятся службы), то хорошо.

**Comment by aurusov** [comment]
И да еще. На локальной машине либу РДО надо собрать один раз. Потом она и в локальном мавене и готова для копирования в Эклипс. Если только для Эклипса, то можно скачать с Дженкинса или нового сайта.
