### ISSUE TITLE
Состояние поля под графом

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#246]
@aurusov 
Перенесено из: https://github.com/LeKaitoW/rdo-game5/issues/43

Граф закрывает состояние поля. Очень неудобно, когда окно графа на весь экран.

![1_010](https://cloud.githubusercontent.com/assets/5585202/10710254/100bd64e-7a59-11e5-8a28-ca9835b6efb2.png)

Хочется, чтобы поле было всегда сверху

![1_011](https://cloud.githubusercontent.com/assets/5585202/10710255/1a98ead4-7a59-11e5-9757-f6316fd4c380.png)

**Comment by bogachev-pa** [comment]
Т.е. окно `Graph Info` должно быть поверх всех окон? Или нужно как-то привязать его к окну графа?

**Comment by bogachev-pa** [comment]
При использовании свойства `SWT.ON_TOP` эффект довольно странный:
![on_top](https://cloud.githubusercontent.com/assets/6528492/10831477/e04d9d9c-7e96-11e5-92bb-b1ac93400570.png)

Данное окно не меняется в размерах и не двигается из этого угла, а также не имеет верхней панели из-за чего возникают проблемы с тем, чтобы его закрыть (Alt+F4 закрывает заодно и диалог с графов).

Кажется, это свойство свт принципиально конфликтует с обычным поведением свт диалогов.

**Comment by aurusov** [comment]
> Т.е. окно `Graph Info` должно быть поверх всех окон? Или нужно как-то привязать его к окну графа?

Главное, чтобы поверх графа. Если будет поверх всех, тоже сойдет.

> Кажется, это свойство свт принципиально конфликтует с обычным поведением свт диалогов.

А если добавить `SWT.CLOSE | SWT.BORDER | SWT.TITLE` ?
А что сделает `SWT.MODELESS` ?

**Comment by bogachev-pa** [comment]
Все эти константы игнорируются. Везде советуют пилить собственные листенеры для перемещений и прочего (http://stackoverflow.com/questions/24959177/is-there-a-way-to-make-a-swt-shell-moveable-and-on-top). Пока что хорошего решения не нашел.

**Comment by aurusov** [comment]
Можно ли задать окно графа как парент для окна с информацией ?

**Comment by aurusov** [comment]
@bogachev-pa @LeKaitoW 
У меня валится Эклипс при отображении. Версии
- raox-game5-1.2.0
- rdo-xtext-2.9.1
- eclipse-dsl-mars-1-linux-gtk-x86_64

Получается, что на текущем релизе 2.9.1 нельзя запускать ? Проясните ситуацию.

**Comment by bogachev-pa** [comment]
Сегфолт `JRE`? Забавно.

Посмотрю, в чем дело. Это же без моих незамерженных изменений? Мб они починят.

**Comment by aurusov** [comment]
Мне хочется до среды, т.е. сегодня-завтра, выпустить архив для студентов. Только винда, архив руками, выкладка на ГуглДокс. Какая связка рабочая ?

**Comment by bogachev-pa** [comment]
Я с этой проблемой не сталкивался, я не знаю. Если мы что-то и сломали, то косвенно, т.е. спровоцировали баг в гтк. Почти уверен, что рабочей связкой будет все то же самое, но выставить в эклипсе (марс1) свойство SWT_GTK3=0 http://askubuntu.com/a/539747

**Comment by aurusov** [comment]
@bogachev-pa @LeKaitoW 
На версиях вы отлаживались в последнее время ?

**Comment by bogachev-pa** [comment]
Я после 2.8.0 рдо и 1.0.0 пятнашек не пробовал. Запускал на `eclipse luna`.

**Comment by aurusov** [comment]
Какой прогноз по срокам этой таски ?

**Comment by bogachev-pa** [comment]
Планирую во вторник-среду поставить пул-реквест.

**Comment by aurusov** [comment]
Постарайся во вторник, чтобы во вторник выкатить архив.

**Comment by aurusov** [comment]
@LeKaitoW 
На версиях ты отлаживалась в последнее время ?

**Comment by LeKaitoW** [comment]
Потестила 2.9.1 рдо с 1.2.0 пятнашками на Luna на убунте. Всё ок работает.

**Comment by aurusov** [comment]
Скачивала либы с Дженкинса или сама собирала ? Для чистоты хочется проверить на тех, которые собрал Дженкинс
- http://rdo.rk9.bmstu.ru:81/job/raox/ws/assembly/target/
- http://rdo.rk9.bmstu.ru:81/job/raox-game5/ws/assembly/target/

**Comment by LeKaitoW** [comment]
Рдо собирала сама, пятнашки качала с дженкинса.

Попробовала с джарниками рдо, скачанными с дженкинса - работает.

**Comment by aurusov** [comment]
Проверю у себя, отпишусь.

**Comment by aurusov** [comment]
Пока проверил под виндой. Не упало, но стабильно повторяется ошибка https://github.com/aurusov/raox-game5/issues/55.

**Comment by aurusov** [comment]
Падение вынес в отдельную таску https://github.com/aurusov/rdo-xtext/issues/258
Почистил обсуждение
