### ISSUE TITLE
Окно с раскладкой меняет свои размеры

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#247]
@aurusov 
Перенесено из https://github.com/LeKaitoW/rdo-game5/issues/41

При переходе к следующему состоянию изменяется _размер_ диалога, кнопки уезжают.

![1_003](https://cloud.githubusercontent.com/assets/5585202/10710224/a27770c6-7a57-11e5-856e-cbf6beac9b7f.png)
![1_004](https://cloud.githubusercontent.com/assets/5585202/10710225/a52b1f98-7a57-11e5-9987-d62107e2443e.png)

**Comment by aurusov** [comment]
Какой прогноз по срокам ?

**Comment by bogachev-pa** [comment]
Планирую во вторник-среду поставить пул-реквест.
