### ISSUE TITLE
Ошибка метода withMin

### ISSUE THREAD

**Issue by Seitenov** [LeKaitoW/raox#256]
В исходном варианте, когда подбор ресурса производится по умолчанию результаты имеют вид
![_](https://cloud.githubusercontent.com/assets/15458980/10908804/6e302812-8245-11e5-955d-43eba963382e.png)

Метод withMin не правильно работает. Он подбирает ресурсы также как withMax.
![_ _](https://cloud.githubusercontent.com/assets/15458980/10908507/6661787c-8243-11e5-9ec8-d3d439b4efcd.png)

Модель:

``` erlang
sequence Интервал_прихода = double legacy exponential(123456789, 1/15.0);
sequence Длительность_обслуживания = double uniform(123456789);
enum Состояние_клиента {Пришел, Начал_стрижку}
enum Состояние_парикмахера {Свободен, Занят}

type Клиенты {
    Состояние_клиента состояние;
}

type Парикмахеры {
    Состояние_парикмахера состояние_парикмахера = Состояние_парикмахера.Свободен;
    int длительность_min;
    int стаж_работы;
    }

resource Парикмахер_1 = Парикмахеры.create(*, 20, 3);
resource Парикмахер_2 = Парикмахеры.create(*, 15, 1);
resource Парикмахер_3 = Парикмахеры.create(*, 25, 5);

event Событие_прихода_клиента() {
    Клиенты.create(Состояние_клиента.Пришел);
    Событие_прихода_клиента.plan(currentTime + Интервал_прихода.next());
}

operation Образец_обслуживания_клиента() {
    relevant _Клиент = Клиенты.select(_Клиент.состояние == Состояние_клиента.Пришел);
    relevant _Парикмахер = Парикмахеры.select(_Парикмахер.состояние_парикмахера == Состояние_парикмахера.Свободен).withMin(_Парикмахер.стаж_работы);

    set duration() {
        return Длительность_обслуживания.next(_Парикмахер.длительность_min, _Парикмахер.стаж_работы); 
    }

    set begin() {
        _Клиент.состояние = Состояние_клиента.Начал_стрижку;
        _Парикмахер.состояние_парикмахера = Состояние_парикмахера.Занят;
    }

    set end() {
        _Парикмахер.состояние_парикмахера = Состояние_парикмахера.Свободен;
        _Клиент.erase();
    }
}

dpt model {
    activity Обслуживание_клиента checks Образец_обслуживания_клиента();
}

set init() {
    Событие_прихода_клиента.plan(currentTime + Интервал_прихода.next());
}

set terminateCondition() {
    return currentTime >= 50;
}
```

**Comment by Seitenov** [comment]
sequence Интервал_прихода = double legacy exponential(123456789, 1/15.0);
sequence Длительность_обслуживания = double uniform(123456789);
enum Состояние_клиента {Пришел, Начал_стрижку}
enum Состояние_парикмахера {Свободен, Занят}

type Клиенты {
	Состояние_клиента состояние;
}

type Парикмахеры {
	Состояние_парикмахера состояние_парикмахера = Состояние_парикмахера.Свободен;
	int длительность_min;
	int стаж_работы;
	}

resource Парикмахер_1 = Парикмахеры.create(*, 20, 3);
resource Парикмахер_2 = Парикмахеры.create(*, 15, 1);
resource Парикмахер_3 = Парикмахеры.create(*, 25, 5);
 
event Событие_прихода_клиента() {
	Клиенты.create(Состояние_клиента.Пришел);
	Событие_прихода_клиента.plan(currentTime + Интервал_прихода.next());
}

operation Образец_обслуживания_клиента() {
	relevant _Клиент = Клиенты.select(_Клиент.состояние == Состояние_клиента.Пришел);
	relevant _Парикмахер = Парикмахеры.select(_Парикмахер.состояние_парикмахера == Состояние_парикмахера.Свободен).withMin(_Парикмахер.стаж_работы);

	set duration() {
		return Длительность_обслуживания.next(_Парикмахер.длительность_min, _Парикмахер.стаж_работы);	
	}

	set begin() {
		_Клиент.состояние = Состояние_клиента.Начал_стрижку;
		_Парикмахер.состояние_парикмахера = Состояние_парикмахера.Занят;
	}

	set end() {
		_Парикмахер.состояние_парикмахера = Состояние_парикмахера.Свободен;
		_Клиент.erase();
	}
}

dpt model {
	activity Обслуживание_клиента checks Образец_обслуживания_клиента();
}

set init() {
	Событие_прихода_клиента.plan(currentTime + Интервал_прихода.next());
}

set terminateCondition() {
	return currentTime >= 50;
}

**Comment by aurusov** [comment]
Спасибо за репорт. Хочется еще больше упростить модель, например, убрать из неё `Клиентов` и событие прихода.

**Comment by Seitenov** [comment]
Примерно так,

``` erlang
sequence Длительность_обслуживания = double uniform(123456789);
enum Состояние_парикмахера {Свободен, Занят}

type Парикмахеры {
    Состояние_парикмахера состояние_парикмахера = Состояние_парикмахера.Свободен;
    int длительность_min;
    int стаж_работы;
    }

resource Парикмахер_1 = Парикмахеры.create(*, 20, 3);
resource Парикмахер_2 = Парикмахеры.create(*, 15, 1);
resource Парикмахер_3 = Парикмахеры.create(*, 25, 5);

operation Образец_обслуживания_клиента() {
    relevant _Парикмахер = Парикмахеры.select(_Парикмахер.состояние_парикмахера == Состояние_парикмахера.Свободен).withMin(_Парикмахер.стаж_работы);

    set duration() {
        return Длительность_обслуживания.next(_Парикмахер.длительность_min, _Парикмахер.стаж_работы); 
    }

    set begin() {
            _Парикмахер.состояние_парикмахера = Состояние_парикмахера.Занят;
    }

    set end() {
        _Парикмахер.состояние_парикмахера = Состояние_парикмахера.Свободен;
        }
}

dpt model {
    activity Обслуживание_клиента checks Образец_обслуживания_клиента();
}

set terminateCondition() {
    return currentTime >= 50;
}
```

**Comment by bogachev-pa** [comment]
Исправил и залил отдельную тестовую модель. Пул-реквест https://github.com/aurusov/rdo-xtext/pull/257
