### ISSUE TITLE
Падение под Убунтой при отображении графа

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#258]
Валится Эклипс при отображении графа
- raox-game5-1.4.0
- rdo-xtext-2.10.0
- eclipse-dsl-mars-1-linux-gtk-x86_64
- workspace удалял
- **openjdk-8-jdk 8u66** (на 8u40 работает нормально)

Под виндой отработало нормально.

![2015-11-02 01-13-53](https://cloud.githubusercontent.com/assets/5585202/10871692/06b2b930-80ff-11e5-931f-27926e08e909.png)

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fde43a3157a, pid=8164, tid=140591112951552
#
# JRE version: OpenJDK Runtime Environment (8.0_66-b17) (build 1.8.0_66-internal-b17)
# Java VM: OpenJDK 64-Bit Server VM (25.66-b17 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libgtk-3.so.0+0x32157a]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by aurusov** [comment]
> Потестила 2.9.1 рдо с 1.2.0 пятнашками на Luna на убунте. Всё ок работает.
> На Mars-1 тоже все ок.
> Очень часто у эклипса начинаются проблемы в воркспейсе. Очень часто рандомно. Смена воркспейса помогает.

У меня не пашет никакая версия, воркспейс удалял.

**Comment by aurusov** [comment]
> Я с этой проблемой не сталкивался, я не знаю. Проблема явно не в несовместимости кода, иначе бы не скомпилилось. Если мы что-то и сломали, то косвенно, т.е. спровоцировали баг в гтк. Почти уверен, что рабочей связкой будет все то же самое, но выставить в эклипсе (марс1) свойство SWT_GTK3=0 http://askubuntu.com/a/539747

Попробовал, не помогло.

**Comment by aurusov** [comment]
@LeKaitoW 
Оля, вышли на почту или г-диск полный архив с Эклипсом, который у тебя запускается.

**Comment by LeKaitoW** [comment]
[Полный архив](https://drive.google.com/open?id=0B3RV5tRbg_npclZPQ2VRMUZtRW8)

**Comment by aurusov** [comment]
- не запускается первый прогон
- если руками собрать трассировку и показать граф, то вижу вот такое (пустое окно, которое даже не может залить свой фон). На скрине эффект из-за ресайза окошка

![2015-11-04 12-11-59](https://cloud.githubusercontent.com/assets/5585202/10933947/65cb0716-82ed-11e5-8f2c-afe8c692ba3d.png)

**Comment by LeKaitoW** [comment]
> не запускается первый прогон

Джарник пятнашек вчерашний.

Сейчас запустила эклипс из архива - всё работает.
Какая версия убунты?

**Comment by aurusov** [comment]
2.10.0 + 1.4.0 (ubuntu 15.10)
Валится сразу при запуске через `Run experiment`

**Comment by aurusov** [comment]
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
java: ../../src/xcb_io.c:274: poll_for_event: Проверочное утверждение «!xcb_xlib_threads_sequence_lost» не выполнено.
```

**Comment by aurusov** [comment]
Выглядит как ошибка интеграции awt в swt. Раньше она валилась на жмаке по вершине (открывался swt-диалог), сейчас сразу, потому что граф переделали.

**Comment by aurusov** [comment]
Ошибка повторяется и без плагина. Достаточно построить граф из трассировки.

`ProgressBar(Widget).checkWidget() line: 420`

``` java
protected void checkWidget () {
    Display display = this.display;
    if (display == null) error (SWT.ERROR_WIDGET_DISPOSED);
    if (display.thread != Thread.currentThread ()) error (SWT.ERROR_THREAD_INVALID_ACCESS); // вот тут спотыкается
    if ((state & DISPOSED) != 0) error (SWT.ERROR_WIDGET_DISPOSED);
}
```

**Comment by bogachev-pa** [comment]
При использовании `openjdk 8u66`, если создать простейший проект с вызовом метода `SWT_AWT.new_Frame()`, `jvm` падает с той же ошибкой.

Сегодня потестил `oracle jdk 8u66`. Все работает (и граф и тестовый проект). Предлагаю соответствующим образом поправить инструкцию и настройки мавена, чтобы использовать `oracle jdk` по крайней мере до тех пор, пока `openjdk` не исправят у себя эту проблему.

**Comment by aurusov** [comment]
Согласен. Поправишь (прямо в release/current) ?

**Comment by bogachev-pa** [comment]
Если это не срочно, то я бы отложил до понедельника, т.к. буду очень занят в выходные.

**Comment by aurusov** [comment]
ok

**Comment by bogachev-pa** [comment]
Ридми поправилен, думаю, можно закрыть.
