### ISSUE TITLE
Ошибка в модели fms.rao

### ISSUE THREAD

**Issue by abelozerov93** [LeKaitoW/raox#261]
В операции

``` erlang
operation Перегрузка_со_станка_на_тележку(Положение положение_станка) {
    relevant станок = Станки.select(станок.положение == положение_станка
        and станок.состояние == Состояние_станка.ЗАКОНЧИЛ_ОБРАБОТКУ);

    relevant робот = Роботы.select(робот.состояние == Состояние_робота.СВОБОДЕН
        and робот_связан_со_станком(робот.номер, станок.номер));

    relevant тележка = Тележки.select(тележка.номер == 2
        and тележка.состояние == Состояние_тележки.СВОБОДНА
        and тележка.положение == Положение.ТЕЛЕЖКА_2_Н);

    relevant деталь = Детали.select(деталь.положение == положение_станка);
```

при подборе релевантных ресурсов не указано положение робота. Его необходимо указать, поскольку в момент начала операции необходимо, чтобы робот находился в том же положении, что и станок. 
( операция Возврат_робота() будет всегда возвращать робота в положение Тележка.1К, как только он станет свободным, отсюда видно,что в момент начала операции Перегрузка_со_станка_на_тележку робот будет находиться в положении Тележка.1К, а не в положении Станок1 или Станок2, что противоречит логике поставленной задачи)

**Comment by aurusov** [comment]
Да что же такое. В какой репе живет указанная модель ?

**Comment by aurusov** [comment]
@abelozerov93, ошибка заведена не в том репозитарии. Вы понимаете, куда её надо перенести ?

**Comment by abelozerov93** [comment]
В rdo-text-models

**Comment by abelozerov93** [comment]
Все перенес

**Comment by aurusov** [comment]
Переехало сюда https://github.com/aurusov/rdo-xtext-models/issues/4
