### ISSUE TITLE
Ошибка поиска по графу

### ISSUE THREAD

**Issue by AlexChernov** [LeKaitoW/raox#263]
Нужно исправить алгоритм поиска.

Должен быть такой:
- корневая вершина помещается в список Open
- достается очередная вершина из списока Open, с минимальной `f`
- она проверятеся с конечной, если да, то выход (**ничего больше делать не надо**)
- вершина порождает потомков или сразу списком или по одному (это не важно)
- потомки еще на стеке, их нет ни в одном из списков
- для каждого потомка запускает процедура смены родителя, после чего он или пропускается или кладется в список Open (видимо, тут есть какое-то непонимание)
- переход на начало

Наблюдаемые на данный момент проблемы:
1. Если конечная вершина, является дочерней для исходной, то она не проверится и граф откроется полностью, так и не найдя решение
   ![1_1_](https://cloud.githubusercontent.com/assets/7085247/11015123/ecebf514-856a-11e5-840f-a6843861b644.png)
   ![2_1_](https://cloud.githubusercontent.com/assets/7085247/11015124/ed063546-856a-11e5-9b01-9bea7b4f1b64.png)
2. Допустим мы породили двух потомков, текущая `g = 1`, стоимость пути до первого потомка `2`, стоимость пути до второго потомка `1`. Пусть они оба ведут к решению (в пятнашках это невозможно, но `A*` не запрещает). Сейчас мы будем последовательно проверять их на решение никак не сортируя по значению `f`. И выберем первого потомка в качестве решения, хотя оно дороже, чем решение через второго потомка.

**Comment by aurusov** [comment]
Паша предложил годное решение https://github.com/aurusov/rdo-xtext/pull/253#issuecomment-154731783

**Comment by bogachev-pa** [comment]
Ещё проблема:
Проверять потомков при их порождении неправильно, т.к. если стоимость шагов будет неодинаковой и более одного потомка с разной стоимостью приводят к решению, мы можем выбрать не того. Именно поэтому проверка и осуществлялась раньше при раскрытии вершины. Надо переделать по-другому.

**Comment by aurusov** [comment]
Ты говоришь про смену родителя. Если этой процедуры нет, то это вообще залет. Нужно ставить БАГУ.

**Comment by bogachev-pa** [comment]
Нет, я говорю про проверку на решение. Смена родителя есть. Пишу здесь, потому что это связанные проблемы, и алгоритм надо в целом переработать.

**Comment by aurusov** [comment]
Хм.. Смена родителя подразумевает сравнение со всеми вершинами из списков Open и Closed. Или ты говоришь, что надо сначала породить всех непосредтсвенных потомков, а только потом проверять на решение ?

**Comment by bogachev-pa** [comment]
Допустим мы породили двух потомков, текущая `g = 1`, стоимость пути до первого потомка `2`, стоимость пути до второго потомка `1`. Пусть они оба ведут к решению (в пятнашках это невозможно, но `A*` не запрещает). Сейчас мы будем последовательно проверять их на решение никак не сортируя по значению `f`. И выберем первого потомка в качестве решения, хотя оно дороже, чем решение через второго потомка.

В алгоритме `A*` по стоимости сортируется именно список открытых вершин и именно из него вершины и проверялись на решение в момент их открытия, т.к. мы гарантируем, что открываем их начиная с наиболее дешевых. Надо вернуть проверку с момент открытия вершины, а не в момент порождения, но делать проверку на решение сразу после ее открытия, не дожидаясь порождения ее потомков.

Для референса: http://cs.stackexchange.com/a/16089

**Comment by aurusov** [comment]
Пример понятен, остальное путано. Всё же просто
- достается очередная вершина из списока Open, с минимальной `f`
- она проверятеся с конечной, если да, то выход (**ничего больше делать не надо**)
- вершина порождает потомков или сразу списком или по одному (это не важно)
- потомки еще на стеке, их нет ни в одном из списков
- для каждого потомка запускает процедура смены родителя, после чего он или пропускается или кладется в список Open (видимо, тут есть какое-то непонимание)
- переход на начало

**Comment by bogachev-pa** [comment]
Вы все описали правильно, а заимплеменчено сейчас не так. Это я и пытался сказать.

**Comment by aurusov** [comment]
Заведешь задачу ?

**Comment by bogachev-pa** [comment]
Предлагаю решать в рамках этой таски, обновил шапку.

**Comment by aurusov** [comment]
Ведь всё исправлено ?

**Comment by bogachev-pa** [comment]
Да.
