### ISSUE TITLE
Новая грамматика языка

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#27]
@aurusov
@k-alexandrovsky

Предлагаю в этой теме обсуждать варианты новой грамматики.

Вкратце идеи по моему варианту:
- функции `initialize()`, `terminate_condition()` и `finish()` определяют, что происходит до запуска модели, терминальное условие и вывод результатов, соответственно
- ключевое слово `resource` служит для добавления ресурса в базу данных, имя можно задавать, а можно и не задавать
- оператор `is` служит для присваивания функций (в противоположность получению возвращаемого значения функции оператором `=`)
- ключевое слово `set` служит для переопределения стандартных вложенных функций (см. паттерны)
- остальное вроде должно быть очевидно

Пример модели парикмахерской:

``` erlang
enum enumOrigin {Тип1, Тип2};

type Парикмахерские
{
    double количество_в_очереди;
};

type Клиенты
{
    enum состояние_клиента {Пришел, Начал_стрижку};

    enumOrigin тип;
    состояние_клиента состояние;
};

type Парикмахеры
{
    enum состояние_парикмахера {Свободен, Занят};

    состояние_парикмахера состояние = Свободен;
    int количество_обслуженных;
    int длительность_min;
    int длительность_max;
    Клиенты.тип.type тип_клиента; //если мы хотим сохранить such_as
};

resource Парикмахерская = Парикмахерские(0.0);
resource Парикмахер_1 = Парикмахеры(*, 0, 25, 70, Тип2);
resource Парикмахеры(*, 0, 30, 60, Тип2);

output Занятость_парикмахера_1 = watch_state(Парикмахер_1.состояние_парикмахера == Занят);
output Занятость_парикмахера_2 = watch_state(Парикмахер_2.состояние_парикмахера == Занят);
output Обслужено_парикмахером_1 = get_value(Парикмахер_1.количество_обслуженных);
output Длина_очереди = watch_par(Парикмахерская.количество_в_очереди);

set initialize()
{
    Образец_прихода_клиента.planning(Time_now + 40.6);
}

set terminate_сondition()
{
    return Time_now >= 8 * 60;
}

Образец_прихода_клиента() is event()
{
    relevant _Парикмахерская = Парикмахерская;
    relevant _Клиент = Клиенты.create();

    set execute()
    {
        Образец_прихода_клиента.planning( Time_now + 40 );
        Парикмахерская.количество_в_очереди++;
        if (_Парикмахерская.количество_в_очереди > 3)
            _Клиент.тип = Тип1;
        else
            _Клиент.тип = Тип2;
        _Клиент.состояние = Пришел;
    }
}

Образец_обслуживания_клиента(double param_1) is operation(time = 42)
{
    relevant _Парикмахерская = Парикмахерская.check(Парикмахерская.количество_в_очереди > param_1);
    relevant _Клиент = Клиенты.find(_Клиент.состояние == Пришел).first();
    relevant _Парикмахер = Парикмахеры.find(_Парикмахер.состояние_парикмахера == Свободен and _Парикмахер.тип_клиента == _Клиент.тип).with_min( _Парикмахер.количество_обслуженных);

    set begin()
    {
        Парикмахерская.количество_в_очереди--;
        Клиент.состояние = Начал_стрижку;
        Парикмахер.состояние = Занят;
    }

    set end()
    {
        _Клиент.erase();
        _Парикмахер.состояние_парикмахера = Свободен;
        _Парикмахер.количество_обслуженных++;
    }
}

model is some(NoCheck)
{
    Обслуживание_клиента is Образец_обслуживания_клиента();
}

Интервал_прихода is exponential(123456789);

Длительность_обслуживания is uniform(seed = 123456789);

Тип_клиента is by_hist(123456789)
{
    return {(Тип1, 1.0), (Тип2, 5.0)};
}
```

**Comment by aurusov** [comment]
Сегодня обсудили синтаксис паттернов, жду от тебя новый синтаксис по релевантным ресурсам. Теперь общие замечания от меня
- `<-` непонятный символ. Выглядит как `is`. Но ты говорил, что он несёт смысл перегрузки в каких-то местах. (наш разговор во вторник). Или не ?. А еще лучше прокомментируй, что это за символ. Ему надо придумать название, а то очень не удобно.
- `set` - почему он перекрывает внутри паттерна, но не перекрывает `init`, к примеру
- сокращения режут глаз
- стараемся не использовать ключевых слов, состоящих из двух и более. Еще непонятно, как лучше писать `terminateCondition`, `terminate_condition` или `TerminateCondition`

**Comment by bogachev-pa** [comment]
> Сегодня обсудили синтаксис паттернов, жду от тебя новый синтаксис по релевантным ресурсам.

Сделал.

> <-  непонятный символ. Выглядит как  is . Но ты говорил, что он несёт смысл перегрузки в каких-то местах. (наш разговор во вторник). Или не ?. А еще лучше прокомментируй, что это за символ. Ему надо придумать название, а то очень не удобно.

Я решил, что символ имел слишком много смыслов, и частично заменил его использование на `set`. Идея `<-` состоит в задании алиасов для функций, последовательностей, паттернов и т.п. Возможно, мне надо его еще чуть лучше продумать.
Согласен насчет `is`, вполне можно использовать это слово, оно везде смотрится неплохо. (Кроме точек принятия решений, возможно там нужен какой-то другой синтаксис для установления соответствия между активностями и паттернами. Надо подумать над физическим смыслом этого процесса).

Edit: Кажется, более последовательным будет такой синтаксис паттернов:

``` erlang
Образец_обслуживания_клиента(double param_1) is operation(42, first)
{
   ...
}
```

Здесь параметры мы объявляем непосредственно после имени операции, а в `operation` передаем нечто вроде параметров конструктора (в данном случае 42 это `duration`, также можно передать, например, first). Такой вариант точнее соответствует синтаксису последовательностей. 
И он позволит не задавать `set duration()` внутри операции. 

Еще остается какая-то непоследовательность с `planning()`, над этим мне надо еще подумать.

> set  - почему он перекрывает внутри паттерна, но не перекрывает  init , к примеру

`set` имеет смысл `override` и позволяет опускать сигнатуру функций при их  определении. Используется только для стандартных функций, относящихся к движку имитационного моделирования. Насчет `init()` - да, нужно быть последовательным, поправил.

> сокращения режут глаз

Поправил. Хотя мне лично намного больше нравится `init`, чем `initialize`.

> стараемся не использовать ключевых слов, состоящих из двух и более. Еще непонятно, как лучше писать  terminateCondition ,  terminate_condition  или  TerminateCondition 

Все-таки не использовать их довольно сложно, название некоторых функций одним словом не описать. Давайте просто договоримся, использовать ли для стандартных функций snake_case или camelCase. В первом случае сразу отличаем стандартные функции РДО от остальных, во втором получаем единообразие. Пока в примере сделал в snake_case.

Поправил пример в сообщении выше.

**Comment by k-alexandrovsky** [comment]
Ну мой вариант мне уже самому не нравится, потому что я уже решил, что идеального варианта быть не может, но вот пример кода для грамматики, где сделано все до паттернов: 

``` erlang
type Парикмахерские[
    Integer количествоВОчереди = 0
];

enum ТипКлиента
    [Мальчик, Девочка];

enum СостояниеПарикмахера
    [Свободен, Занят];

enum СостояниеКлиента
    [Пришел, НачалСтрижку];

type Парикмахер[
    СостояниеПарикмахера состояние = СостояниеПарикмахера.Свободен,
    ТипКлиента типКлиента = ТипКлиента.Мальчик,
    Integer длительностьМин,
    Integer длительностьMакс,
    Integer КоличествоОбслуженных
];

type Клиент[
    ТипКлиента тип = ТипКлиента.Мальчик,
    СостояниеКлиента состояние = СостояниеКлиента.Пришел
];

resources[
    Парикмахерская = Парикмахерские(0)
];

resources[
    Парикмахер1 = Парикмахер(СостояниеПарикмахера.Свободен, ТипКлиента.Мальчик, 20, 30, 0),
    Парикмахер2 = Парикмахер(СостояниеПарикмахера.Свободен, ТипКлиента.Девочка, 40, 50, 0),
    Парикмахер3 = Парикмахер(СостояниеПарикмахера.Свободен, ТипКлиента.Девочка, 35, 65, 0)
];

sequence Интервал_прихода returns Double
    is exponential seed 123456789;

sequence Длительность_обслуживания returns Double
    is uniform seed 123456789;

sequence Тип_клиента returns ТипКлиента is historgam [
    ТипКлиента.Мальчик : 1.0,
    ТипКлиента.Девочка : 5.0
] seed 123456789;

function someFun(String someParam) returns Integer
{
    return 42;
}

pattern eventPattern with [
    RELRES1 = check Парикмахерская for RELRES1.количествоВОчереди > 0,
    R2 = find Парикмахер minimize R2.количествоОбслуженных,
    R3 = create Клиент
] is event
{
    // SOME CODE
};

pattern opPattern with [
    RELRES1 = check Парикмахерская for RELRES1.количествоВОчереди > 0,
    R2 = find Парикмахер with R2.количествоОбслуженных minimal,
    R3 = create Клиент
] is operation(/* DURATION */ 42.0)
{
    // SOME CODE
}
then
{
    // SOME CODE AGAIN
};
```

**Comment by bogachev-pa** [comment]
Предлагаю это тему закрыть и продолжить обсуждение в https://github.com/bogachev-pa/rdo-xtext/issues/20.

**Comment by aurusov** [comment]
А в чём смысл ?

**Comment by bogachev-pa** [comment]
Мне удобнее референсить коммиты, например. Асайни можно меня поставить.

Все-таки уже решили, что задачей занимаюсь я.

**Comment by aurusov** [comment]
Точно, не заметил, что мы у Кирилла.

**Comment by k-alexandrovsky** [comment]
И кстати, насчет референсов на ишью в коммитах, можно всегда делать вот так:
`username/rdo-xtext/#N`
Пример коммита - https://github.com/k-alexandrovsky/rdo-xtext/commit/0995d86559f967452f35dc7859d6b439608b209c
И тогда при мерже друг у друга нам не будут прилетать левые референсы.

**Comment by bogachev-pa** [comment]
Ну да, я так и делаю для референсов в другие репозитарии. В принципе, предлагаю взять за правило всегда писать референсы полностью, даже если они в твой репозитарий, чтобы избежать тупняков гитхаба на мержах.

**Comment by bogachev-pa** [comment]
Собственно,
@aurusov 
@kstrizhov
@LeKaitoW 

Обратите внимание на два сообщения выше. Думаю, всем стоит всегда так делать.

**Comment by aurusov** [comment]
Поддерживаю
