### ISSUE TITLE
Лаб раб Пятнашки

### ISSUE THREAD

**Issue by AnanasCocos** [LeKaitoW/raox#271]
.evaluate() работает только с int, когда я использовала double в своей эвристике, модель выдавала эту ошибку. Я конвертировала double в int, ошибка не исчезла. Последний шаг - ввод в окно Heuristic Code кода из программы c измененным названием и ошибка не исчезла (фото прикреплены):

``` erlang
int Расстояние_фишки_до_места_2(int Откуда, int Куда) {
    return Math.abs(Ряд(Откуда)-Ряд(Куда)) + Math.abs(Столбец(Откуда)-Столбец(Куда));
}

int Расстояния_фишек_до_мест_2() {
    return Расстояние_фишки_до_места(Фишка1.Номер, Фишка1.Местоположение)+
           Расстояние_фишки_до_места(Фишка2.Номер, Фишка2.Местоположение)+
           Расстояние_фишки_до_места(Фишка3.Номер, Фишка3.Местоположение)+
           Расстояние_фишки_до_места(Фишка4.Номер, Фишка4.Местоположение)+
           Расстояние_фишки_до_места(Фишка5.Номер, Фишка5.Местоположение);
}
```

![rdo1](https://cloud.githubusercontent.com/assets/15844161/11162883/870bcd30-8ac6-11e5-8097-a09a850c59e9.png)
![rdo2](https://cloud.githubusercontent.com/assets/15844161/11162881/8708e3d6-8ac6-11e5-9d04-964df064da65.png)
![rdo3](https://cloud.githubusercontent.com/assets/15844161/11162882/870b1c82-8ac6-11e5-8492-eb8a6ba7f870.png)

**Comment by bogachev-pa** [comment]
Не видно полностью поля `Heuristic`, что там?

**Comment by AnanasCocos** [comment]
То, что я написала в прикрепленном коде, то и в окошке.

**Comment by bogachev-pa** [comment]
Поле `Heuristic`, не `Heurisric code`. Там, где эвристика выбирается, а не описывается.

**Comment by AnanasCocos** [comment]
Расстояние_фишки_до_места_2()

**Comment by AnanasCocos** [comment]
Расстояние_фишки_до_места_2()

**Comment by bogachev-pa** [comment]
Функция 

``` java
int Расстояние_фишки_до_места_2(int Откуда, int Куда) {
    ...
}
```

принимает два параметра.

Ошибка возникает из-за того, что в поле выбора эвристики ей не передается ни одного:

``` java
Расстояние_фишки_до_места_2()
```

Ошибка исчезнет, если написать, например, так:

``` java
Расстояние_фишки_до_места_2(0, 0)
```

**Comment by AnanasCocos** [comment]
Спасибо. Извини, можешь удалить

**Comment by bogachev-pa** [comment]
нп
