### ISSUE TITLE
Докумертация на поднятие мавер-репозитория

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#278]

**Comment by AlexChernov** [comment]
Добавил в [Документ](https://docs.google.com/document/d/1pM7-K6T5Ya82p6CpBetuj1xvWJZb65umPQlzBR4ddx8/edit#heading=h.nseyphn1wd59)

**Comment by aurusov** [comment]
Допиши логин и пароль в доку

**Comment by AlexChernov** [comment]
Обновил документ

**Comment by aurusov** [comment]
ok
