### ISSUE TITLE
Работа с ресурсами в Xbase

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#286]
Реализовать полноценную работу с ресурсами в `Xbase`: создание, хранение, удаление, назначение имен.

**Comment by aurusov** [comment]
С этой задачей всё ?

**Comment by bogachev-pa** [comment]
Да, пожалуй, закрою. Вопросы с менеджером ресурсов буду решать в отдельной задаче по реализации подхода сканирования активностей.
