### ISSUE TITLE
Сериализация в Xbase

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#287]
Настроить сериализацию в `Xbase`.
Возможные вопросы:
- стоит ли использовать стороннюю библиотеку для сериализации или оставить свой формат?
- как сериализовать и выводить информацию о произвольных типах?

**Comment by aurusov** [comment]
Зафиксируй к чему сегодня пришли. Мы не обсудили сторонние библиотеки сериализации.

**Comment by bogachev-pa** [comment]
Обсудили два варианта:
1. Использовать метод `toString()` у всех объектов и дальше уже работать с сериализацией строк.
2. Сериализовывать объекты джававскими методами при записи в БД, десериализовывать при считывании.

Решили, что метод 2 предпочтительнее (хоть и кажется, что первого на данный момент хватит).

Также обсудили возможность добавления еще одного окна, которое позволит отобразить полный слепок ресурсов системы для каждого момента времени.

Про сторонние библиотеки погуглю.

**Comment by bogachev-pa** [comment]
Восстановил сериализацию ресурсов.
На данный момент остались:
- [x] сериализация поиска по графу
- [ ] сериализация результатов
- [ ] специальная обработка енумов при сериализации - чтобы можно было строить по ним графики

**Comment by bogachev-pa** [comment]
Результаты будут сделаны в рамках работы над их переводом на `xbase`, а для енумов завел отдельную таску: https://github.com/aurusov/raox/issues/376
