### ISSUE TITLE
Течет память

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#29]
@k-alexandrovsky 
Пока тестировал ленивого трассировщика, обнаружил, что у нас, похоже, течет память. Судя по симптомам - в базе данных (возможно, массив сериализованных данных почему-то не почищается GC между прогонами).

Я закрыл все окна трассировки, а массива с трассировкой в ленивом трассировщика нет вообще, так что, скорее всего, это не она.

Воспроизвожу так: прогон с большим количеством данных -> смотрю htop, далее прогон с малым количеством данных -> htop показывает, что количество используемой оперативы не уменьшается, хотя оно резко увеличилось при первом прогоне, например, на гигабайт.

**Comment by k-alexandrovsky** [comment]
Если мы не падаем с `OutOfMemory` через 100 прогонов, то все хорошо. Java немного себе на уме, когда речь заходит о потреблении памяти.

http://stackoverflow.com/questions/16137193/java-heap-size-grows-by-portions-up-to-some-limit?answertab=votes#tab-top

Программа начинает с `Xms` и растет до `Xmx`, при этом отдавать захваченное не собирается.

**Comment by aurusov** [comment]
У жабы нет понятия утечки памяти :) Для контроля за утечкой и нужен ГК. И да, он себе на уме.

**Comment by bogachev-pa** [comment]
> Программа начинает с Xms и растет до Xmx, при этом отдавать захваченное не собирается.

Кажется, поведение именно такое, тогда все в порядке. Дома еще раз проверю.

> У жабы нет понятия утечки памяти :) Для контроля за утечкой и нужен ГК. И да, он себе на уме.

Утечка не совсем правильный термин, но, насколько я понимаю, может быть такая ситуация, что логика программы сохраняет возможность еще использовать какой-то объект, хотя мы этого делать не собираемся. В итоге GC будет считать, что память освобождать не нужно.

**Comment by aurusov** [comment]
Конечно, нужно освобождать все умные указатели на объекты.

**Comment by k-alexandrovsky** [comment]
Ну да, потечь еще можно, если полезть в off-heap, типа direct байт-буферов и всяких быстрых off-heap коллекций. Но мы таким не занимаемся, у нас все байт-буферы обычные.

**Comment by bogachev-pa** [comment]
Я закрыл окно трассировки и запускал модель на 500к записей раз 20-30 подряд, в итоге с 2gb памяти "поднялся" до 3gb. Но дальше вроде не расту и не протормаживаю особо, так что не очень понимаю, есть проблема или нет.

Edit: Предел количества записей, на которых умираем по GC, не уменьшается, если много раз предварительно запустить модель, а, значит, все ок. Наверное, JVM просто аллоцирует себе еще память при последовательных прогонах, чтобы не ждать, пока GC сможет ее освободить, а тут уже мы ничего не сможем сделать.
