### ISSUE TITLE
Запуск процессной модели

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#293]
@LeKaitoW 
Опиши по шагам процесс запуска

**Comment by LeKaitoW** [comment]
1. Считывание файла процессного подхода
2. Считывание объекта `Model` из файла
3. Создание блоков процессного подхода в соответствии с графическими блоками (потомками объекта `Model`
4. Создание связей между блоками процессного подхода
5. Добавление созданных блоков в список `processBlocks` симулятора
