### ISSUE TITLE
Добавить структуру объекта RAOX в JSON представление

### ISSUE THREAD

**Issue by timyrka67** [LeKaitoW/raox#299]
Это вполне вроде как дополнение к #298. 
Я не совсем представляю как это должно выглядеть.

**Comment by aurusov** [comment]
@bogachev-pa 
Паша, приведи ссылку на структуру модели плиз.

**Comment by bogachev-pa** [comment]
А что именно нужно?

Вот [тут](https://github.com/bogachev-pa/raox/blob/feature/xbase/ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/ExecutionJobProvider.java#L127) можно посмотреть как выглядит ее `stub`.
Вот [тут](https://github.com/bogachev-pa/raox/blob/feature/xbase/ru.bmstu.rk9.rao.lib/src/ru/bmstu/rk9/rao/lib/database/Database.java#L88) пример того, как база данных читала структуру при своей инициализации.

Но так как я в иксбейзе пока сериализацией не занимался, то она не очень в актуальном состоянии, разве что просто как пример.

**Comment by aurusov** [comment]
@bogachev-pa 
Имел в виду вторую ссылку, спасибо

@timyrka67 
Понимаешь, откуда её взять ?
