### ISSUE TITLE
Исправить RDO Status

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#30]

**Comment by k-alexandrovsky** [comment]
![screenshot from 2015-03-06 17 59 37](https://cloud.githubusercontent.com/assets/6878143/6527294/a6ba4f5c-c42a-11e4-90d6-dcb5ca99f14d.png)
В общем, теперь `RDOStatusView` восстал из пепла, и стал мощной и удобной штукой для отображения чего угодно. И стал еще божественнее, конечно же.

@bogachev-pa @LeKaitoW 
Теперь все могут делать следующее (в целях отладки, например):

``` java
RDOStatusView.setValue(String name, int priority, String value);
```

И в статусе все сразу обновится/появится.

``` erlang
name - имя (заголовок) категории
priority - порядок отображения в списке (выше приоритет - выше в списке запись)
value - текст для отображения
```

Если хочется убрать запись, достаточно передать `null` в поле `value`.
А в правой части каждой записи (которая отображает `value`) можно выделять текст курсором и копипастить.

**Comment by aurusov** [comment]
Круто, чё.
