### ISSUE TITLE
Реализация параметров блоков процессного подхода

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/raox#303]
- [x] Интервал Generate
- [x] Длительность Advance
- [x] Ресурс Seize/Release
- [x] Условие прохода Test (вероятность)
- [x]  Вместимость Queue
- [x] Дисциплина в Queue (FIFO, LIFO)

**Comment by aurusov** [comment]
Тут всё ?

**Comment by LeKaitoW** [comment]
По списку в первом сообщении -- да.
Но достаточно ли в `Test` только вероятности?

**Comment by aurusov** [comment]
Хочется еще и по условию, которое ты пишешь руками. Сложно добавить ?

**Comment by LeKaitoW** [comment]
Условие должно быть связано с параметрами транзактов. Пока не обдумывала, как их задавать.
После этого появится необходимость как-то парсить/компилировать условие. Если только писать а-ля GPSS сравнение `A, B`. Получается не очень гибко.
TL;DR: Сложно, заслуживает отдельной таски.

**Comment by aurusov** [comment]
Главное, чтобы в условии можно было написать любое xbase-выражение, в том числе и проверка параметров транзакта.

**Comment by aurusov** [comment]
Добавление условия вынесено в отдельную таску https://github.com/aurusov/raox/issues/329.
