### ISSUE TITLE
Дизайн блоков

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/raox#304]

**Comment by LeKaitoW** [comment]
Обновление блоков:
![default](https://cloud.githubusercontent.com/assets/10632455/13743672/346e4b24-e9f4-11e5-90aa-250bb44d5e16.PNG)

**Comment by aurusov** [comment]
1. Я бы сделал всех одного цвета.
2. seize/release лучше поменять местами, м.б. обрезать до половинок
3. queue сделал бы как тут http://math.stackexchange.com/questions/424714/utilization-difference-between-a-multiple-server-single-queue-and-a-multiple-se, а то сейчас это решетка какая-то

**Comment by LeKaitoW** [comment]
Новый цвет:
![color](https://cloud.githubusercontent.com/assets/10632455/14058533/10742fb0-f334-11e5-909e-bff58a11cf27.PNG)

**Comment by aurusov** [comment]
Давай чуть темнее
![-1](https://cloud.githubusercontent.com/assets/5585202/14060122/6c89d1f2-f36a-11e5-8fef-6cc1cf3fce1a.png)
![-3](https://cloud.githubusercontent.com/assets/5585202/14060124/6cb5df04-f36a-11e5-8525-194656cea886.png)
![-2](https://cloud.githubusercontent.com/assets/5585202/14060123/6cb4272c-f36a-11e5-9503-8fba41e16392.png)

**Comment by bogachev-pa** [comment]
@aurusov 
По-моему, текущий вариант выглядит лучше.

Вообще. нам бы как-то увязать все цвета, которые мы используем в разных частях `ui` друг с другом. Мы с Лешей и Олей обсуждали сейчас цвета и пришли к выводу, что, наверное, нам нужно выбрать какую-то палитру и брать цвета для всех компонентов только оттуда.
Иначе у нас сейчас все вразнобой и выглядит не очень серьезно.

**Comment by aurusov** [comment]
Идея с палитрой норм. Только делать её точно не надо, поищите в инете, накидайте ссылок прям сюда.
