### ISSUE TITLE
Реализовать анимацию с Xbase

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#305]

**Comment by bogachev-pa** [comment]
Все сделано.

**Comment by aurusov** [comment]
Отлично. Приаттач скрин плиз.

**Comment by bogachev-pa** [comment]
Визуально ничего не изменилось.
![anim](https://cloud.githubusercontent.com/assets/6528492/14575440/db1082fc-0372-11e6-9572-7742882230b2.png)
