### ISSUE TITLE
Трассировка процессного подхода

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/raox#312]
`PR` `время` `блок` `параметры блока`

**Comment by LeKaitoW** [comment]
Пример трассировки:
![trace](https://cloud.githubusercontent.com/assets/10632455/14156156/99907f00-f6cd-11e5-940a-60a42c69faa9.PNG)

**Comment by LeKaitoW** [comment]
Упс, случайно закрыла таску.

**Comment by aurusov** [comment]
1. А цвет прям точно тот ? Кажется темнее
2. Что еще осталось по задаче ?
3. Где пул-реквест ?

**Comment by LeKaitoW** [comment]
1. Точно тот.
2. Ничего. Не хотела закрывать таску, пока не посмотрите результат.
3. Работала в основной ветке. (По привычке. Впредь буду делать новые ветки пул-реквесты.)
