### ISSUE TITLE
Вкладка процессного подхода

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#315]
1. Исправить расширение файла на `*.proc`
2. Имя вкладки должно быть как у файла
3. Открывать палитру по умолчанию
   ![2016-03-27 19-21-46 rao - barber_project barber grao - eclipse platform](https://cloud.githubusercontent.com/assets/5585202/14066396/37d51dc6-f451-11e5-8ff6-adc5892035fb.png)

**Comment by LeKaitoW** [comment]
1. Исправлено
2. Исправлено
3. Палитра теперь открывается при каждом открытии файла, не зависимо от того, закрыл пользователь палитру или нет. Если же нам необходимо только первое открытие, то это нужно прописывать в файле `.ini` эклипса.

**Comment by aurusov** [comment]
_3. пока так поживем
