### ISSUE TITLE
Изменить названия блоков

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#324]
@bogachev-pa @LeKaitoW @AlexChernov 
- `Advance` -> `Delay`. Потому что второе намного ближе к сути. Проще думать транзактом, который создается, удаляется, задерживается и т.д. Не все блоки этому соотвествуют, например, Advance.
- `Test` -> `?`. Потому что Test для меня несет образ ассемблера, особенного его GPSS версия, со всякими G, L, E и т.д., а не языка высокого уровня. Что посоветуете ?
  - https://translate.yandex.ru/?text=%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%B8%D1%82%D1%8C&lang=ru-en
  - https://translate.yandex.ru/?text=%D0%BF%D0%B5%D1%80%D0%B5%D0%B9%D1%82%D0%B8&lang=ru-en
  - https://translate.yandex.ru/?text=%D1%80%D0%B5%D1%88%D0%B8%D1%82%D1%8C&lang=ru-en

Вот пример из Арены, блок назывется `Decide`, имеет 4-ре режима работы, в том числе и как if и как switch из Java.
![2016-03-30 17 55 28](https://cloud.githubusercontent.com/assets/5585202/14146538/0ef33cbc-f6a9-11e5-8fbc-a7ddd05af121.png)
В AnyLogic называется SelectOutput.
![2016-03-30 18 08 27](https://cloud.githubusercontent.com/assets/5585202/14146993/d11e834a-f6aa-11e5-8a81-3ccf48eb4ace.png)

**Comment by bogachev-pa** [comment]
Некоторые мысли:
Если мы рассуждаем от лица транзакта, то `Test` превращается в `Decide`/`Decision`, `Choose`/`Choice` или `Select`.
Если от лица системы, которая транзактов распределяет, то это `Route` (в принципе, `Select` с этой точно зрения тоже имеет смысл).
Можно еще нейтральные названия, которые отражают то, что это развилка: `Fork`, `Junction`.

Честно говоря, не знаю, какой из вариантов предпочтительнее.

**Comment by aurusov** [comment]
Мне хотелось бы от лица транзакта. Хотя в той же Арене были и блок `Decide` и `Route` (что-то типа телепорта на блок `Station`)

**Comment by aurusov** [comment]
Мне больше нравится слово `Select`, но без существительного как-то не то, поэтому.
`Test` -> `SelectOutput`, `SelectPath`, `SelectRoute` или `ChooseOutput`, `ChoosePath`, `ChooseRoute`

**Comment by bogachev-pa** [comment]
Из этих вариантов мне нравится `SelectRoute`.

Насчет `Delay` - мне, в принципе, нравится, в качестве альтернативы могу предложить `Wait`.

**Comment by LeKaitoW** [comment]
- `Advance`. Вариант `Delay` хороший, но если нужны ещё варианты: `Wait`, `Hold` (второй вариант имеет много значений: https://translate.yandex.ru/?text=hold&lang=en-ru).
- `Test`. Нравится `Decision`, но он не очень описывает блок, как мне кажется. Лучшие варианты -- `SelectPath`/`SelectRoute`

**Comment by bogachev-pa** [comment]
`Hold`, кстати, хорош тем, что он ближе к процессу обслуживания, в отличие от `Delay` и `Wait`, которые говорят только о времени. Так что этот вариант мне тоже нравится.

**Comment by aurusov** [comment]
Ага, тогда предлагаю
- `Advance` -> `Hold`
- `Test` -> `SelectPath`

ok ?

**Comment by bogachev-pa** [comment]
Слово `Route` на мой взгляд чуть ближе к "направлению", чем `Path`, но я не против `SelectPath` тоже.

**Comment by aurusov** [comment]
Удалил это сообщение, потому что еще думаю.

**Comment by LeKaitoW** [comment]
Ок!
Лучшие варианты, имхо.

**Comment by aurusov** [comment]
На работе меня убеждают, что лучше `Choose`, чем `Select`. Потому что первое про выбор пути, а второе скорее про выбор из множества. Я не носитель языка, мне `Select` больше нравится. Но спрашивал у чела, который шпрехает норм. Т.е.
- `Advance` -> `Hold`
- `Test` -> `ChoosePath`

Что думаете ?

**Comment by bogachev-pa** [comment]
`Select` в данном случае - выбор из множества вариантов дальнейшего пути, разве нет? `Choose` выглядит так, будто транзакт может пойти куда угодно, а не только в те 2 возможных выхода, которые мы ему предоставили.

Я могу ошибаться, так что если `Choose` все-таки грамотнее, то давайте его.

Upd: погуглил, тут есть определения из словаря
http://english.stackexchange.com/a/13048

> **choose**: to have a preference for or to select freely and after consideration
> **select**: to choose (as by fitness or excellence) from a number or group

Т.к. у нас всё-таки выбор из нескольких вариантов (пути), то, мне кажется, должен быть `Select`. Другое дело, что это слово может плохо сочетаться со словом "Path", вот тут я уже не знаю.

**Comment by aurusov** [comment]
Слова оперделены друг через друга :) Короче, пофиг. По поводу `SelectPath`/`SelectRoute`, мне кажется они по сути одинаковы, но `SelectPath` проще говорить на лекции. Поэтому я за него. Ну и никто не мешает нам переделать после обстерла системы в боевый условиях (на студентах и лабах).

**Comment by aurusov** [comment]
- `Advance` -> `Hold`
- `Test` -> `SelectPath`

ok ? (Для меня ok)

**Comment by LeKaitoW** [comment]
Повторюсь -- ок! (Рада, что `Hold` пришелся кстати.)
И `Select` кажется приятнее, чем `Choose` по звучанию. :)

**Comment by bogachev-pa** [comment]
Согласен с последними вариантами.
