### ISSUE TITLE
Добавить привязку блоков к сетке

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#328]

**Comment by LeKaitoW** [comment]
`getGraphicalViewer().setProperty(SnapToGrid.PROPERTY_GRID_VISIBLE, true);`

**Comment by aurusov** [comment]
@LeKaitoW 

![2016-04-28_09-34-28](https://cloud.githubusercontent.com/assets/5585202/14877297/7876c06e-0d24-11e6-9424-9cb95d2560ad.png)

Почему-то конекшен рисуется под гридом. Думал, что это регулируется последовательность добавления в `pane` вот тут
https://github.com/LeKaitoW/raox/blob/feature/snap_to_grid/ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/process/ProcessEditor.java#L217
Поменял первые два местами - тот же скрин. И только если `PRIMARY_LAYER` сделать первым, то конекшены начинают рисоваться поверх всего.
1. тут есть нелогичность
2. явно не хватает отдельного слоя для grid'а

Последовательность слоев должна быть такая
- фоновый
- grid
- конекшены
- модель
