### ISSUE TITLE
Добавить превью блоков в палитру

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#335]
Результат
![2016-05-16_09-25-19](https://cloud.githubusercontent.com/assets/5585202/15281925/367cffac-1b48-11e6-9dea-f5cd6d8b7efd.png)
![2016-05-16_09-24-50 2](https://cloud.githubusercontent.com/assets/5585202/15281922/316fb766-1b48-11e6-85ef-c993376fe507.png)

**Comment by bogachev-pa** [comment]
Не пойму, а что на первом, и что на втором скрине - в чем отличие?
И как на самом деле после коммита?

**Comment by aurusov** [comment]
Там же написано - `Результат`. В палитре разные режимы просмотра. Показал два.

**Comment by bogachev-pa** [comment]
> В палитре разные режимы просмотра.

Не знал. Т.е. пользователь между ними сам переключаться?

Насчет внешнего вида, выглядит клево, но из-за несимметричности некоторых блоков, они будто скачут влево-вправо. Может быть, их стоит обвести в какие-то рамочки?
(если рамочки будут смотреться не очень, то оставим так)

**Comment by aurusov** [comment]
> Не знал. Т.е. пользователь между ними сам переключаться?

Да

> Может быть, их стоит обвести в какие-то рамочки?

Решил рамочку сделать белой, как при d&d. Её видно при выборе элемента. Можно попробовать черный цвет - это одна строчка imho, но симметрию это не исправит.

**Comment by aurusov** [comment]
Черный не очень, откатил. А вот симметрию зачинил.
