### ISSUE TITLE
Экспорт графиков в json

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/raox#341]
Для регрессионного тестирования нужно уметь сохранять dataset графиков в json. Кажется важным для проверки результатов прореживателя.

**Comment by ViktorRakhmatulin** [comment]
Хочу закрепить этот бонус. Очень много знакомых слов

**Comment by ViktorRakhmatulin** [comment]
Нужно через контекстное меню сохранять датасет графика в файл в формате JSON, верно?

**Comment by aurusov** [comment]
Да
