### ISSUE TITLE
Хинт при наведении мышки на точку графика

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/raox#343]
Задачу можно разбить на этапы
- отловить и преобразовать координаты мишки в координаты графика так, чтобы точка (0, 0) совпала с началом системы координат графика
- найти по координатам графика значения (x ,y) графика с учетом допуска
- вывести найденные значения в виде [balloon window](http://stackoverflow.com/a/8531537)

![2015-05-22 16 46 36](https://cloud.githubusercontent.com/assets/5585202/7771725/29270292-00a2-11e5-97c9-1f9e3c3a1fb1.png)

**Comment by ViktorRakhmatulin** [comment]
![2016-11-26 20-05-16](https://cloud.githubusercontent.com/assets/22197503/20640817/9b6e6e8c-b3fa-11e6-97bf-6f201e4b0a09.png)

**Comment by aurusov** [comment]
Хинт не должен появляться, если от мышки до ближайшего значения графика много пикселей. 

Хочется дизайна
- облачко вверх
- белый (светлый) фон
- форматированный вывод, не больше 5-7 символов для x и y
- хочется выводить красный кружок над тем значением графика, из которого растет хинт
- два варианта на пробу
```
x: x_value y: y_value
```
vs
```
y_value
x_value
```

**Comment by ViktorRakhmatulin** [comment]
Предыдущий ToolTip Swt.Baloon не имеет настройки стилей. Поэтому я собрал другой. ВОт как он выглядит:
![2016-11-30 23-12-46](https://cloud.githubusercontent.com/assets/22197503/20763027/7ee57cfa-b739-11e6-8a4d-1b1519f4ebb2.png)
На 50 пикселей выше точки.

**Comment by aurusov** [comment]
Уже намного лучше. Сделай тот же скрин, но с мышкой. Есть прогресс по красному кружку ?

**Comment by ViktorRakhmatulin** [comment]
В классе XYStepRenderer  org.jfree.chart.renderer.xy.XYStepRenderer.XYStepRenderer ,кажется, лежит причина bug: График из одной точки #61. 
Надо править Около  233 строчки кода. То есть я создам новый класс ,который наследует XYStepRenderer, и перепишу методы отрисовки.
ИЛи мне сделать тупое решение, и на месте точки построить обьект заполненную окружность?
И с Хинтом сделаю подобное выделение точки.

**Comment by aurusov** [comment]
Первый метод предпочтительнее, если переписывать надо не 233 строки, а пару. Если так много, то лучше вариант, который обсуждали на консультации. И лучше обсуждать задачу #61 в её ветке.

**Comment by ViktorRakhmatulin** [comment]
![2016-12-02 18-07-12](https://cloud.githubusercontent.com/assets/22197503/20833496/15b03c16-b8a1-11e6-99e2-a7b093afc856.png)
ПРозрачный кружок не годится?

**Comment by ViktorRakhmatulin** [comment]
просто У класса Ellipse2D отсутствует возможность заполнять фигуры.

**Comment by aurusov** [comment]
Не годится. Где коммит ? Он должен быть прикреплен к задаче.

**Comment by ViktorRakhmatulin** [comment]
Теперь все работает. Не смотрите последний коммит.

**Comment by aurusov** [comment]
Надо добавить ссылки на задачу ко всем коммитам

**Comment by ViktorRakhmatulin** [comment]
![2016-12-03 20-47-23](https://cloud.githubusercontent.com/assets/22197503/20860071/ac04d610-b980-11e6-8523-6933694601cd.png)

**Comment by aurusov** [comment]
1. ~Не симметричный допуск при выборе точки~ `ok`
2. ~Тултип сместить ниже, ближе к точке~ `ok`
3. ~Точку сделать с белым кружочком внутри (цвет фона графика). Использовать класс XYDrawableAnnotation. Если не получится, то XYShapeAnnotation.~ `ok`
4. Цвет точки должен браться с цвета графика. По коду берется, но надо проверить.
5. ~Сделать скрин с~ `ok`
```
y_value
x_value
```
6. Не пропадает точка если двигать мышкой вверх-вниз или вправо-влево, без диагональных перемещений.
7. При изменении масштаба точка меняется вместе с графиком. Выглядит некрасиво. Задача минорная.

**Comment by ViktorRakhmatulin** [comment]
![2016-12-08 18-00-40](https://cloud.githubusercontent.com/assets/22197503/21010125/757f5d52-bd5b-11e6-814f-32ce5e289ebd.png)
Такой вариант годится?

**Comment by aurusov** [comment]
Да, выглядит хорошо. Но сужу только по скрину, нужно еще мышкой поелозить.

**Comment by aurusov** [comment]
Вместо значения перечислимого типа выводится 0

**Comment by ViktorRakhmatulin** [comment]
@aurusov  Выводится и 0, и 1 ( занят=1 , свободен =0 ). Понимаю, что названия  перечислимого типа должны храниться в обьекте Database и ,наверное, в CollectedDataNode.  Но пока прогресса нет, я запутался. Я вывожу точки из dataset  графика.

**Comment by aurusov** [comment]
Эти значения выводятся на оси ординат графика.

**Comment by ViktorRakhmatulin** [comment]
надо закрыть

**Comment by aurusov** [comment]
Еще не выпущен релиз, жду Лёшину задачу. Сам закрою.
