### ISSUE TITLE
Путаница с ;

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#35]
В первый раз запустил новое РДО :smile: 
Обнаружил, что `;` используется довольно часто. Это ok. Тогда предлагаю дописать его куда только можно. В простейшей модели нашел два места
- Описание типа ресурса

```
$Resource_type BarberShops: permanent
$Parameters
    barberState : (Free, Busy)
    queueLength : integer
$End
```
- Собираемые показатели

```
$Results
    queue : watch_par BarberShop.queueLength
    utilization : watch_state BarberShop.barberState == Free
$End
```

**Comment by bogachev-pa** [comment]
Согласен.

Сегодня предложил другу, совершенно незнакомому с РДО, написать простейшую на новой грамматике по моему туториалу. Что его больше всего смутило - именно непоследовательность в использовании точек с запятыми. На то же постоянно жалуется Кирилл (Стрижов).

Я сделал это в своей ветке по переделыванию грамматики, а в других ветках предлагаю отдельно не трогать.

**Comment by bogachev-pa** [comment]
Думаю, можно закрыть.
