### ISSUE TITLE
В окне трассировки отсутсвует горизонтальный слайдер

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#351]
Если текст трассировки не влезает в нее целиком, должна быть возможность прокрутить содержимое окна трассировки вправо.

**Comment by vla-parfenkov** [comment]
Добрый вечер, могу сделать в пятницу вечером, если никто еще не забронировал. Владислав Парфенков РК9-81.

**Comment by aurusov** [comment]
Никто, берите. Время до субботы включительно.
