### ISSUE TITLE
Не загорается кнопка записи

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#357]
Проверялось на https://github.com/LeKaitoW/raox/commit/c3ec8556ac51f5e20a3dc583ca8c2ee2d36b88c5

Шаг 1
- загружаем Эклипс
- создаем проект визардом
- размещаем блок Generate
- сохраняем модель
- изменяем свойство интервал
- кнопка записи загорается
- закрываем Эклипс, **не сохраняя модель**

Шаг 2
- загружаем Эклипс
- **двойным кликом** выбираем блок, Generate внизу открывается окошко свойств
- изменяем свойство интервал
- кнопка записи **не загорается**
- закрываем проект (не Эклипс)
- открываем проект
- изменяем свойство интервал
- кнопка записи загорается

При этом, кнопка загорается, если подвигать фигуру.

Решил проверить на старой версии, еще до моих изменений и рефакторинга, https://github.com/LeKaitoW/raox/commit/b03ddaa32370d95cf7db5bfb816cac5bb5b444e5. Кнопка не загоралась, даже на Шаге 1.

Ошибку воспроизводил под Виндой.
- Винда `Windows 10, x64`
- Эклисп `Version: Mars.2 Release (4.5.2) Build id: 20160218-0600`
- Джава `Java(TM) SE Runtime Environment (build 1.8.0_77-b03)`

**Comment by aurusov** [comment]
Оля, попробуй половинным делением найти место, где стало лучше/хуже.

**Comment by LeKaitoW** [comment]
Ни на одной из веток воспроизвести не смогла: кнопка записи загорается при любых изменениях.
Тестила на винде.
Версия эклипса: `Version: Mars.1 Release (4.5.1)`
Java: `Version 8 Update 45`

**Comment by aurusov** [comment]
Протестил под Убунтой, не работает (https://github.com/LeKaitoW/raox/commit/c3ec8556ac51f5e20a3dc583ca8c2ee2d36b88c5)
- Убунта `Ubuntu 14.04.4 LTS`
- Эклисп `Version: Mars.2 Release (4.5.2) Build id: 20160218-0600`
- Джава `Java(TM) SE Runtime Environment (build 1.8.0_77-b03)`

Проверял на первом коммите, меняю интервал на шаге 1, не загорается. На втором шаге тоже. Начинает работает, когда делаю `Refresh`.

**Comment by bogachev-pa** [comment]
У меня работает. Тестил на ветке `feature/graphic_process`.

Убунту: `15.10`
Версия эклипса: `Version: Mars.2 Release (4.5.2) Build id: 20160218-0600`
Java: `Java(TM) SE Runtime Environment (build 1.8.0_77-b03)`

**Comment by aurusov** [comment]
> У меня работает. Тестил на ветке `feature/graphic_process`.

Проверь на другой ветке, первая ссылка.

**Comment by bogachev-pa** [comment]
> Проверь на другой ветке, первая ссылка.

То же самое. Не воспроизводится.

**Comment by aurusov** [comment]
Ошибка исправлена. Как у вас работало - непонятно.

**Comment by aurusov** [comment]
@LeKaitoW 
Думаю, что при выборе ресурса должно быть тоже самое
`PROPERTY_RESOURCE_NAME_INDEX`
и при смене
`SelectPathNode.PROPERTY_PROBABILITY`
Если да, то поставь задачу. Только меня смущает, что вы не смогли повторить пример. Стерали проект ? Создавали его заново ? Делали refresh + rebuild all перед запуском ?

**Comment by bogachev-pa** [comment]
@aurusov 

Делал четко по шагам, как вы описали в первом посте. Не воспроизводилось.
Каким образом вызов `refreshVisuals()` активирует кнопку сохранения?

**Comment by aurusov** [comment]
> Каким образом вызов `refreshVisuals()` активирует кнопку сохранения?

Не ведаю, надо смотреть исходники. М.б. Оля знает свзять. Но у меня именно это решило проблему.

**Comment by aurusov** [comment]
Погорячился, у меня до сих пор не работает :(

**Comment by LeKaitoW** [comment]
Связи между `refreshVisuals()` и кнопкой записи не должно быть.
У меня ошибка так и не воспроизводится, кнопка записи работает корректно.

**Comment by aurusov** [comment]
Надо не забыть посмотреть в субботу на ваших машинках, где не воспроизводится. У меня очень стабильно, даже на шаге 1.

**Comment by aurusov** [comment]
Получилось повторить, дополнено описание в шапке.
