### ISSUE TITLE
Процессную модель не получается остановить по кнопке

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#358]
Паша, прошу посмотреть. Кажется, что остановка не должно иметь отношение к процессной модели. Получается, что модель из одного рула, условие которого всегда истинно, тоже висит ?

**Comment by bogachev-pa** [comment]
1. В режиме `NO_ANIMATION`?
2. Трассировка включена?

**Comment by aurusov** [comment]
1. не знаю, просто создаю модель визардом
2. да

**Comment by bogachev-pa** [comment]
1. Это значки выбора скорости в тулбаре. Думаю, по умолчанию выставлен он. Это просто прогон на полной скорости.
2. Можете попробовать, сохраняется ли проблема, если сериализацию отключить?

**Comment by aurusov** [comment]
Мне кажется, что gui должен всегда адекватно реагировать на тулбар и меню, независимо от режима прогона и др. настроек.

**Comment by bogachev-pa** [comment]
Согласен. Но, если проблема проявляется только при включенной сериализации, то это дубликат вот этой таски https://github.com/aurusov/raox/issues/112
