### ISSUE TITLE
Не работает автозавершение

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#36]
- При создании ресурса после `:` не видно тип ресурса
- При создании активности в dpt после `:` не виден паттерн
- После `Choice from BarberShop_.` (это релевантный ресурс) выводится `.` и всё

**Comment by bogachev-pa** [comment]
В новой грамматике:
1, 2. Работают (точнее, аналоги этих конструкций)
3. Проблема тоже все еще есть. Но чем сейчас выдумывать какие-то дополнительные схемы валидации, мне кажется, лучше как можно раньше приступить к переходу на язык выражений и там эта проблема будет решена сама собой.

**Comment by aurusov** [comment]
Я помню, что это работало на консультациях. Или нет ?

**Comment by bogachev-pa** [comment]
Не знаю. На каких именно консультациях и на чьих исходниках?
Если я правильно помню старую грамматику обращения к параметрам ресурсов, пункт 3 вряд ли мог когда-то работать.

**Comment by aurusov** [comment]
На консультация Кирилла. Могу путать. @k-alexandrovsky ?

**Comment by k-alexandrovsky** [comment]
Увы, это никогда не работало. В choice from'ах язык выражений, а он без автодополнения в принципе. Тут нужен xbase

**Comment by aurusov** [comment]
А в теле паттерна работало ? Я же где-то видел выпадающий список с параметрами ресурса или бред ?

**Comment by k-alexandrovsky** [comment]
Это работало только в such_as, да и даже это я считаю большим везением, если честно. Слишком сложно делать scoping для каких-то вложенных конструкций.

**Comment by bogachev-pa** [comment]
Чтобы потом не забыть: это исправлено в ветке по `xbase`.
