### ISSUE TITLE
Реализовать чтение и запись состояний модели в JSON файл

### ISSUE THREAD

**Issue by timyrka67** [LeKaitoW/raox#360]
А так же выпилить лишний кол из компилятора ресурсов

**Comment by timyrka67** [comment]
Пример дампа через GSON
http://pastebin.com/dnZwNHv5
@aurusov @bogachev-pa

**Comment by aurusov** [comment]
Выглядит хорошо. Попробуй десериализовать в плеере.

**Comment by timyrka67** [comment]
Возникла проблемма:

После сериализации истинный тип ресурса нужно указывать руками чтобы правильно десериализовать.
Пока непонятно где хранить доступные нагенеренные классы.

**Comment by aurusov** [comment]
Вижу имена типов в json `ru.bmstu.rk9.rao.lib.process.Transact`. Эта значение тебе доступно как строка ?

**Comment by timyrka67** [comment]
Я встрял с десериализацией. Кроме как писать сериализацию и десериализацию полностью руками я не нашел других вариантов. Прогресса нет.

**Comment by bogachev-pa** [comment]
Каким образом ручная сериализация поможет? Опиши подробно, что делаешь, и в чем проблема.
