### ISSUE TITLE
Настроить тестирование с помощью rcptt

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#362]
Надо встроить тестирование гуи в задачу http://jenkins.raox.rk9.bmstu.ru/job/raox/ перед деплоем в локальный мавен.

**Comment by bogachev-pa** [comment]
Добавил тесты на сравнение трассировки с эталонной для моделей из визарда.

**Comment by aurusov** [comment]
Покажи пул-реквест

**Comment by bogachev-pa** [comment]
Хм, заливал это сразу в `feature/xbase`.
Коммит:
https://github.com/bogachev-pa/raox/commit/2ad53819db3236baebb7a51283a5e0af3ebadb3b

**Comment by bogachev-pa** [comment]
@aurusov 

Давайте эту таску закроем и вынесем вот это:

> Надо встроить тестирование гуи в задачу http://jenkins.raox.rk9.bmstu.ru/job/raox/ перед деплоем в локальный мавен.

в отдельную задачу?

**Comment by aurusov** [comment]
Хорошо

**Comment by aurusov** [comment]
https://github.com/aurusov/raox/issues/444
