### ISSUE TITLE
Перевести модели из репозитория raox-models на новый синтаксис

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#374]
https://github.com/aurusov/raox-models
Одна из моделей (https://github.com/aurusov/raox-models/blob/master/models/fms.rao) делается в отдельной таске https://github.com/aurusov/raox/issues/416. Многие другие - в https://github.com/aurusov/raox/issues/418.

**Comment by bogachev-pa** [comment]
@aurusov 
1. В этом репозитории есть папка `tests` для моделей, которые изначально планировались для тестирования. Теперь модели для тестирования хранятся в основном репозитории в проекте `ru.bmstu.rk9.rao.rcptt`, т.е. рядом хранятся и шаблон модели и тест для этого шаблона.
   Предлагаю тогда перенести модели из папки `tests` в основной репозиторий (если они все еще имеют смысл), а папку `tests` удалить.
2. Может быть, точно так же поступить и с моделями из папки `models` и этот репозиторий вообще удалить? Таким образом у нас будет одно место для хранения всех моделей, и, помимо этого, они еще и все будут тестироваться - что позволить точно знать, что они всегда в работоспособном состоянии.

**Comment by aurusov** [comment]
1. согласен
2. не надо, пусть останутся в https://github.com/aurusov/raox-models

**Comment by aurusov** [comment]
Многие модели используются в презентации. Кажется, что модели из https://github.com/aurusov/raox-models/tree/master/models лучше переводить мне. ~~Перенеси (1) и переводи задачу на меня.~~

**Comment by aurusov** [comment]
Завел https://github.com/aurusov/raox/issues/419 для (1)

**Comment by aurusov** [comment]
@bogachev-pa 
С моделями из  `models` закончил. А вот модели из `tests` хочу удалить. Они ведь тебе не нудны ?

**Comment by bogachev-pa** [comment]
Да, тесты у нас совершенно поменялись, давайте те грохнем.

**Comment by aurusov** [comment]
Грохнул. По задаче всё.
