### ISSUE TITLE
Добавить подписку на обновление результатов

### ISSUE THREAD

**Issue by AlexChernov** [LeKaitoW/raox#382]
Добавить подписку resultManager на STATE_CHANGED и EXECUTION_COMPLETED
В этот момент пересчитываются все результаты (которым это нужно)

**Comment by AlexChernov** [comment]
Добавил только подписку на STATE_CHANGED, так как перед EXECUTION_COMPLETED должно быть изменение. Это позволяет убрать сущности dataset и value и оставить только result,собираемые показатели при этом зависят от класса статистики

**Comment by aurusov** [comment]
Т.е. уже сделал ?

**Comment by AlexChernov** [comment]
Да
