### ISSUE TITLE
Добавить результатам метод для ручного пересчета

### ISSUE THREAD

**Issue by AlexChernov** [LeKaitoW/raox#385]
Добавить результатам метод для ручного пересчета
Этот же метод должен дергать ResultManager

**Comment by aurusov** [comment]
Это зачем ? Для юнит-тестов ?

**Comment by AlexChernov** [comment]
Речь идет о manual результатах. Нужен метод update(), который обновляет статистику dataset или запоминает значение value. Этот же метод вызывается по подписке в ResultManager для auto результатов
