### ISSUE TITLE
Добавление методов set/get для ResultMode

### ISSUE THREAD

**Issue by AlexChernov** [LeKaitoW/raox#386]
Сейчас ResultMode - protected атрибут класса `Result`, который используется в `ResultManager` в обработчике подписки на изменение состояния системы

``` java
public void fireChange() {
    for (Result<?> result : results) {
        if (result.resultMode == ResultMode.AUTO)
            result.update();
    }
}
```

**Comment by aurusov** [comment]
Надо переделать или закрыть таску, она не соответсвует действительности.

**Comment by AlexChernov** [comment]
Решено в aurusov/raox/issues/497
