### ISSUE TITLE
Выбор ресурса в блоках Seize/Release

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/raox#387]
- Выбор только из ресурсов с енумом
- Добавить выпадающие списки (название енума, исходное состояние, конечное состояние)
- Распознавание енумов (State/Состяние, Free/Свободен, Busy/Занят)

**Comment by aurusov** [comment]
С этой таской всё ? Можно ставь пул-реквест ?

**Comment by aurusov** [comment]
Посмотрел. Сразу несколько моментов
- Очень сложно задать значения, не очевидное GUI с появляющимися свойствами
- Так и не понял, что надо вбивать в поля Start/Finish value. Задал как понял, но модель остановилась в runtime-error, т.е. ведет себя неадекватно. Меняю значения для Release - почему-то меняется и для Seize. Бррр. Что это было ?
- Почему у релиза два значения ?

Предлагаю сделать выпадающий список, в формате `resource.parameter.enum_value`
- Для Seize завести два поля
  - Условие захвата (`Resource's state capture condition` ?)
  - Значение после захвата (`Resource's state after capture` ?)
- Для Release одно поле
  - Значение ресурса после освобождения (`Resource's state after release` ?)
- Сейчас в списке выводится `имя_проекта.имя_модели.resource` - очень неудобно. Можно избавиться хотя бы от имени проекта ?

**Comment by LeKaitoW** [comment]
> Для Release одно поле 

То есть релиз из любого значения может освобождать? А если у состояния есть значения типа "не загружен" и "свободен"?
Мы не упустим ошибку (неточность модели), когда состояние ресурса изменится между срабатываниями сиза и релиза?

**Comment by aurusov** [comment]
Проверка нужна, выпиливать её не надо. Но будет достаточно проверить, что ресурс _еще не свободен_. Т.е. состояние _откуда_ нас не волнует, главное, чтобы _не куда_. Если будет надо, то добавим проверку на конкретное состояние, но сейчас это выглядит как неоправданное усложние.

**Comment by LeKaitoW** [comment]
Оставили исходный вариант (возможность выбрать любой ресурс). Решили заниматься извращениями с аннотациями благодаря @k-alexandrovsky

**Comment by aurusov** [comment]
Текущая логика имеет недостаток, у которого уже есть решение в трассировщике. Завел https://github.com/aurusov/raox/issues/465.
