### ISSUE TITLE
Реализовать класс статистики для числовых значений, взвешенной по времени

### ISSUE THREAD

**Issue by AlexChernov** [LeKaitoW/raox#394]
Для модели колл-центра такой класс используется, например, для сбора статистики по очереди

**Comment by aurusov** [comment]
А где таска про большие наборы ?

**Comment by AlexChernov** [comment]
В процессе создания

**Comment by aurusov** [comment]
Лучше ссылку

**Comment by AlexChernov** [comment]
https://github.com/aurusov/raox/issues/395

**Comment by aurusov** [comment]
Разбей на две задачи и добавь примеры с первого листа курсового.
