### ISSUE TITLE
Оператор == работает некорректно для сравнения енумов

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#404]
Это проблема иксбейза, а не наша, но мб можно найти ворэраунд.
Данный код:

``` java
enum T {A, B}

int x() {
    var a = T.A;
    if (a == T.A)
        print("something");
}
```

Скомпилится в неработающий код на `Java`.
Чтобы заработало надо писать через `equals`:

``` java
enum T {A, B}

int x() {
    var a = T.A;
    if (a.equals(T.A))
        print("something");
}
```

Но лучше, если это будет работать и через `==`.

**Comment by aurusov** [comment]
Т.е. это не только для перечислений, а для всех нетривиальных типов.

**Comment by bogachev-pa** [comment]
Не уверен. Проверю - отпишу.

**Comment by aurusov** [comment]
Эта задача блочит перевод моделей.
