### ISSUE TITLE
Использование ссылок на ресурсы при объявлении последовательностей/результатов

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#405]
Если описать что-то такое:

``` java
type T {
}

resource r1 = T.create()
resource r2 = T.create()

sequence s = new Values([r1, r2]) 
```

То модель упадет при запуске, т.к. инициализация ресурсов сейчас происходит после инициализации последовательностей или результатов.

**Comment by aurusov** [comment]
Может ли ресурс использовать генератор ? Если да, то надо учитывать последовательность их описания в коде.

**Comment by bogachev-pa** [comment]
Готово.
