### ISSUE TITLE
Общие организационные вопросы

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#417]
Первым делом надо закончить текущие пул-реквесты, чтобы собрать их в Пашиной репе (https://github.com/bogachev-pa/raox, бранч `feature/xbase`). Потом можно сделать форки и продолжить исправлять ошибки и пилить фичи. Постарался отметить у каждого из вас приоритерные задачи. [Список задач](https://github.com/aurusov/raox/milestone/15) к учебному году.

@AlexChernov 
Пур-реквест https://github.com/bogachev-pa/raox/pull/43. Леша обещал приступить к реквесту через неделю. Первые выходные - 16 июля. Очень жду результат, потому что твой реквест блочит перевод моделей и первую лабу.

@bogachev-pa 
Обсудиди голосом, нашли три приоритетных задачи. Паша может заниматься задачами прямо сейчас.

@LeKaitoW 
Приоритетные задачи:
- Процессный подход. Поставить пул-реквест на Пашину репу. Оля обещала после 20-го. Для этого надо исправить https://github.com/aurusov/raox/issues/387 и поставить пул-реквест на процессный подход. Посмотрим, заопрувим, поедешь к Паше.
- Пятнашки, https://github.com/aurusov/raox/issues/414. Обещала постараться выделить пару часов до 20-го.

Кажется, что эти задачи не связаны, но пул-реквест выгоднее поставить быстрее, чтобы было меньше конфликтов.

@timyrka67 
Приоритетная задача - пул-реквест https://github.com/bogachev-pa/raox/pull/44. Тимур обещал приступить перед выходными (16-го июля).
Потом:
- Обновить текущие таски.
- Обеспечить работу симулятора с выключенным врайтером без потери ресурсов.
- Представить себя студентом-пользователем и зафиксировать недоработки и хотелки в виде новых тасок.

**Comment by AlexChernov** [comment]
#123 это старое обсуждение собираемых показателей. Можно закрывать
#307 Можно закрывать, все задачи разнесены (#394, #395 и т. д.):
#265 В прошлый раз обсуждая голосом мы остановились на том, что нужно попытаться удалить файлы проекта, но без них перестает собираться maven. В итоге ничего не удалилось. И все так же можно экспортировать в эклипс как maven проект.

**Comment by aurusov** [comment]
Обсудили задачи с Лешей.
