### ISSUE TITLE
Enum'ы в кодах выхода симулятора

### ISSUE THREAD

**Issue by k-alexandrovsky** [LeKaitoW/raox#42]
https://github.com/k-alexandrovsky/k-alexandrovsky.github.io/issues/1#issuecomment-113551504

**Comment by bogachev-pa** [comment]
Непонятно, о чем это.

@aurusov , @k-alexandrovsky 
Пока еще не все забылось, напишите, о чем тут речь.

**Comment by k-alexandrovsky** [comment]
Это вроде закрыто уже. У симулятора `run()` же больше не вываливается с волшебными константами?

**Comment by aurusov** [comment]
Кирилл, проверь это место. Если кто последний и правил, то это ты imho.

**Comment by k-alexandrovsky** [comment]
Ничего не исправил, оказывается. Но пока руки не доходят.

**Comment by aurusov** [comment]
@k-alexandrovsky
ping

**Comment by bogachev-pa** [comment]
Не думаю, что имеет смысл пинговать кирилла, он ведь уже не работает на РДО. Предлагаю просто перевести эти две таски на меня.

**Comment by aurusov** [comment]
> Не думаю, что имеет смысл пинговать кирилла, он ведь уже не работает на РДО.

Пингую, чтобы он задачу вспомнил, а не решил.
