### ISSUE TITLE
Использование типов ресурсов в собираемых показателях

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#420]

**Comment by aurusov** [comment]
@AlexChernov @bogachev-pa 
Леша утверждает, что у него не работает с типам ресурса. Паша - что с ресурсами. Что происходит ? В разных бранчах по разному ?

Паша, нужен твой ответ.

**Comment by bogachev-pa** [comment]
В данном случае Леша имел в виду, что если передавать ресурс, завернутый в лямбду, то все будет ок:

``` java
result обслужено_парикмахером_1 = new Value([парикмахер_1.количество_обслуженных]);
```

Но если передавать ресурс в качестве параметра в тип результата, то модель не скомпилится:

``` java
resultType Занятость_парикмахера<Состояние_парикмахера>(Парикмахеры парикмахер) {
    set evaluate() {
        return парикмахер.состояние_парикмахера
    }
}

result занятость_парикмахера_1 = new Занятость_парикмахера(Парикмахер_1);
```

Проблема описана в этой таске: https://github.com/aurusov/raox/issues/405

**Comment by aurusov** [comment]
Напишу вопросы в отдельных сообщениях, жду ответов.

(1) Тогда непонятно, про какой тип ресурса говорил Леша. Я - про РДОшный. Не нашел ничего про него в ответе Паши. С типом ресурса работают собираемые показатели или нет ? Леша, Паша ?

**Comment by aurusov** [comment]
(2) Правильно ли я понял, что такой вариант заработает ?

``` java
resultType Занятость_парикмахера<Состояние_парикмахера>(Парикмахеры парикмахер) {
    set evaluate() {
        return парикмахер.состояние_парикмахера
    }
}

result занятость_парикмахера_1 = new Занятость_парикмахера([Парикмахер_1]);
```

**Comment by aurusov** [comment]
(3) Покажите пример модели с собираемым показателем, который работает (или должен работать, но пока не работает) с типом ресурса.

**Comment by AlexChernov** [comment]
> Правильно ли я понял, что такой вариант заработает ?

```
resultType Занятость_парикмахера<Состояние_парикмахера>(Парикмахеры парикмахер) {
    set evaluate() {
        return парикмахер.состояние_парикмахера
    }
}

result занятость_парикмахера_1 = new Занятость_парикмахера([Парикмахер_1]);
```

Проверял сегодня с утра, такой вариант не работает

**Comment by aurusov** [comment]
(0) Самое непонятное для меня.
- нашем разговоре Леша говорил про `ресурс` vs `тип ресурса`
- в вашем разговоре получается `ресурс` vs `ресурс, завернутый в лямбду`

И второе подается как ответ на первое. Вы меня окончательно запутали. Распутайте.

**Comment by AlexChernov** [comment]
Я говорил, про то, что работает такой вариант :

```
resultType Занятость_парикмахера_1<Состояние_парикмахера>() {
    set evaluate() {
        return Парикмахер_1.состояние_парикмахера
    }
}

result занятость_парикмахера_1 = new Занятость_парикмахера_1();
```

и очень хотелось бы, чтобы заработал вариант:

```
resultType Занятость_парикмахера<Состояние_парикмахера>(Парикмахеры парикмахер) {
    set evaluate() {
        return парикмахер.состояние_парикмахера
    }
}

result занятость_парикмахера_1 = new Занятость_парикмахера(Парикмахер_1);
```

**Comment by aurusov** [comment]
>Я говорил, про то, что работает такой вариант и очень хотелось бы, чтобы заработал вариант описанный выше:

Приведи все варианты в одном ответе. Слава `такой` и `описанный выше` мне мало о чем говорят.

**Comment by aurusov** [comment]
И укажи на какой вопрос ты отвечаешь.

**Comment by aurusov** [comment]
Леша, твой ответ на вопросы (0 и 3). Продолжаем (0). Паша, поясни свой ответ с учетом Лешиного примера из https://github.com/aurusov/raox/issues/420#issuecomment-233583327. Я не понимаю, какая тут связь с лямбой.

**Comment by AlexChernov** [comment]
Я понял. Сейчас работает такой вариант:

```
resultType Состояние_операторов<Состояние_оператора>(Supplier<Операторы> оператор) {
    set evaluate() {
        return оператор.get().состояние_оператора
    }
}

result состояние_оператора_1 = new Состояние_операторов([оператор_1]);
```

Теперь по порядку:
**(0)**  и **(1)** Я называл результатом с `ресурсом` тот, который вообще не принимал параметров:

```
resultType Занятость_парикмахера_1<Состояние_парикмахера>() {
    set evaluate() {
        return Парикмахер_1.состояние_парикмахера
    }
}
```

(рабочая схема)

И результатом c `типом ресурса` тот, который принимал бы в качестве параметра ресурс, т.е. был бы результатом для типа ресурсов, а не для конкретного

```
resultType Занятость_парикмахера<Состояние_парикмахера>(Парикмахеры парикмахер) {
    set evaluate() {
        return парикмахер.состояние_парикмахера
    }
}

result занятость_парикмахера_1 = new Занятость_парикмахера(Парикмахер_1);
```

(не рабочая схема)

Если `завернуть ресурс в лямбду`, а вернее использовать Supplier, то появляется возможность
передать использовать ресурс, переданный через параметр и реализовать `результат с типом ресурса`

```
resultType Состояние_операторов<Состояние_оператора>(Supplier<Операторы> оператор) {
    set evaluate() {
        return оператор.get().состояние_оператора
    }
}

result состояние_оператора_1 = new Состояние_операторов([оператор_1]);
```

(рабочая схема)

**(2)** https://github.com/aurusov/raox/issues/420#issuecomment-233582991

**Comment by aurusov** [comment]
Ура, разобрались.

**Comment by aurusov** [comment]
Насколь понял, задача https://github.com/aurusov/raox/issues/405 упростит только создание собираемого показателя, но не уберет Supplier. Т.е. после её решения должно заработать что-то типа

``` java
type Операторы {
}

resource оператор_1 = Операторы.create()

resultType Состояние_операторов<Состояние_оператора>(Supplier<Операторы> оператор) {
    set evaluate() {
        return оператор.get().состояние_оператора
    }
}

result состояние_оператора_1 = new Состояние_операторов(оператор_1);
```

Правильно ?

**Comment by bogachev-pa** [comment]
Нет, после ее решения должно заработать следующее:

``` java
type Операторы {
}

resource оператор_1 = Операторы.create()

resultType Состояние_операторов<Состояние_оператора>(Операторы оператор) {
    set evaluate() {
        return оператор.состояние_оператора
    }
}

result состояние_оператора_1 = new Состояние_операторов(оператор_1);
```

Но:
Тонкий момент состоит в том, что такая конструкция в принципе не будет работать, если кто-то подменит ресурс оператор_1. Потому что ссылать в результате мы все еще будем на старый ресурс.
Апи для подмены ресурса мы пользователю не предоставляем. Единственное, что подменяет ресурс - поиск по графу. Насколько я понимаю, во время поиска по графу никаких результатов мы собирать не можем (да и это не имеет смысла), так что все должно быть в порядке.

**Comment by k-alexandrovsky** [comment]
@bogachev-pa 
А нельзя ли сделать ресурс статическим геттером в пространстве имен модели? И в тело вызова завернуть всю возню с менеджерами. Тогда мы сможем обращаться к ресурсам по именам и из рулов, например. Сейчас то если в руле идет подбор по инстансу, как оно реализовано?

**Comment by bogachev-pa** [comment]
@k-alexandrovsky 
Он и является статическим геттером, внутри которого завернуто обращение к менеджеру.
Но только вот в коде, который я привел, мы передаем уже `результат` вызова этого самого геттера, т.е. уже саму величину ресурса. Если завернуть в лямбду, то как раз все ок - каждый раз вызывается геттер на новое значение. В рулах сейчас как раз идет обращение к менеджерам и там все норм, во время поиска мы идем именно в то состояние, в которое нам надо.

**Comment by k-alexandrovsky** [comment]
А, все, я слоу. Вообще все эти беды все из за отсутствия указателей на указатели :grin: 
Еще можно усложнить механизм деплоев путем подмены значений полей, таким образом за счет определенного оверхеда можно остаться в рамках одного и того же инстанса. Если решаться на тотальный хардкор, есть еще [Unsafe.copyMemory](http://hg.openjdk.java.net/jdk7/jdk7/jdk/file/9b8c96f96a0f/src/share/classes/sun/misc/Unsafe.java#l545), то есть тип memcpy.

Еще один вариант - сделать все типы ресурсов врапперами, которые будут предоставлять все те же геттеры/сеттеры, но внутри будут хранить лишь инстанс типа и обращаться к нему. Вот его-то и можно спокойно подменять. То есть сделать постоянное проксирование.

Вопрос, где какой оверхед. Ну и может я еще что не учел.

**Comment by bogachev-pa** [comment]
> Еще можно усложнить механизм деплоев путем подмены значений полей, таким образом за счет определенного оверхеда можно остаться в рамках одного и того же инстанса. 

Я думал об этом, смотрел всякие либы по поводу дип-копи. Тут проблема в том, что ресурсы могут хранить в себе ресурсы и т.п., короч, я не уверен, что простой `memcpy()` на область памяти ресурсов поможет.

> Еще один вариант - сделать все типы ресурсов врапперами, которые будут предоставлять все те же геттеры/сеттеры, но внутри будут хранить лишь инстанс типа и обращаться к нему. Вот его-то и можно спокойно подменять. То есть сделать постоянное проксирование.

Не совсем понял. Какой смысл подменять инстанс типа?

**Comment by k-alexandrovsky** [comment]
Таким образом будет плевать на инстанс враппера. То есть резалт получил легкий враппер, работает с ним, и он всегда актуален, потмоу что менеджер ему будет обновлять инстанс реального ресурса в ходе деплоев. А в конструкторе/деструкторе можно регать инстансы врапперов у менеджера. То есть `getПарикмахер1()` будет оборачивать ресурс враппером и отдавать. Есть шанс, что это все очень слоу будет, хотя можно отдавать один и тот же враппер. Тут куча вариантов различной степени упоротости, но в целом механизм может быть очень гибким.

**Comment by bogachev-pa** [comment]
Готово.
