### ISSUE TITLE
rcptt-тесты на результаты моделирования

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#421]

**Comment by AlexChernov** [comment]
Так как тест должен покрывать все возможности результатов, здесь это будет выглядеть логично
@aurusov 
Общий вид определения типа результата:

``` erlang
resultType ResultType<Тип "возвращаемого" значения> ({параметры}) {
    set condition() {}
    set evaluate() {}
}
```

Общий вид объявления результата:

``` erlang
result Result = ResultType({параметры}, resultMode = manual/auto*,statistics=Statistics*)
```

"*" - значение по умолчанию
Statstics:
- CategoricalStatistics - статистика для категорий, взвешенная по вхождениям, используется по умолчанию для результатов с нечисленным возвращаемым типом
- StorelessNumericStatistics - статистика для числовых значений, взвешенная по вхождениям, -//- для числовых
- ValueStatistics - статистика возвращающая последнее значение
- WeightedStorelessNumericStatistics - статистика для числовых значений, взвешенная по времени
- _WeightedCategoricalStatistics_ - **Еще не реализованная** статистика для категорий, взвешенная по времени

Предопределенные типы результатов:
- Value

``` erlang
result someValue = Value([evaluate], [condition] = [true], resultMode = manual/auto*)
```

Тип результата, использующий статистику ValueStatistics, нужен для упрощения определения результатов типа "количество обслуженных" и т.д.
- Dataset Еще не реализован

Тип результат который не имеет evaluate и condition, и работает только в ручном режиме, а метод update имеет параметр, значние которого и записывается в статистику
