### ISSUE TITLE
Нестабильно проходят тесты на Дженкинсе

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#422]
Тесты из http://jenkins.raox.rk9.bmstu.ru/job/raox-rcptt/ могут отвалиться по timeout'у:
`Fail 19 (29) processed. 1 failed. spent: 25:18, 12:39 mins remaining. model_generator_sequence. time: 375987ms  Cause: Execution timed out after 300 seconds`
В следующий раз могут пройти. Непонятно от чего зависит. Хочется разобраться и начать доверять серверу тестирования. М.б. мало памяти на машинке.

**Comment by bogachev-pa** [comment]
Проходят.

**Comment by aurusov** [comment]
Не согласен. На дженкинсе они ведут себя рандомно, приемущественно НЕ проходят. Что делать ?

**Comment by bogachev-pa** [comment]
На дженкинсе любой тест может упасть по каким-то странным причинам. Это не проблема конкретно результатов. Тесты вели себя так и до пул-реквеста Леши.
Я думаю, эту задачу надо закрыть, и открыть новую, связанную с нестабильностью тестов на дженкинсе.

**Comment by aurusov** [comment]
Зачем открывать новую, когда можно скорректировать эту.

**Comment by aurusov** [comment]
Добавил памяти виртуалке, тест прошел.
