### ISSUE TITLE
Первое впечатление по новому синтаксису

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#427]
- Почему имя ресурса должны начинаться со строчной буквы ?
- Почему имя модели после `logic` должно начинаться с заглавной буквы ?
- Везде подобные ограничения (имена событий, операций, фреймов и др) ?
- Не хватает `++` и `--` (https://github.com/aurusov/raox/issues/403)
- Можно ли избавиться от `#` в последовательности `sequence clientInputInterval = new Values(#[14, 13, 17, 15, 16, 15, 14, 22, 19])` ? Квадратные скобки конфликтуют с другим использованием ?
- Нечитаемые сообщения об ошибке, пример для кода (https://github.com/aurusov/raox/issues/431)

``` erlang
logic Model {
    new Activity(Service.create());
}
```

![2016-09-04_21-20-11](https://cloud.githubusercontent.com/assets/5585202/18233028/96421a86-72e5-11e6-9b4c-5ac32bf26db5.png)
- После создания модели из визарда некоторые строки отмечены как ошибки, хотя она нормально запускается. Если её перезаписать, то ошибки пропадают. Под виндой и маком проявляется постоянно, под убунтой редко. (https://github.com/aurusov/raox/issues/476)
- Если создать пустую модель и скопировать в него [старую модель](https://github.com/aurusov/raox-models/blob/b75cf408e26815d713f84cb8b5eb3ab095679b18/models/barber_activity.rao), то начинают вылезать диалоги с ошибками. Лезут почти на каждое изменение символа в модели. Очень мешают работать.
- Почему бы не назвать конфигурацию запуска проще: `runtime-EclipseXtext` -> `EclipseXtext` или `raox` ? Тогда не пришлось бы корректировать _Location_ (https://github.com/aurusov/raox/issues/429)

**Comment by aurusov** [comment]
@bogachev-pa 
Еще неделю назад начал юзать новую версию. Думал продвинусь на неделе, дополнить список и только потом показать его тебе. Но не успел. Посмотрел текущие замечания и выскажи свое мнение.

**Comment by bogachev-pa** [comment]
> Почему имя ресурса должны начинаться со строчной буквы ?
> Почему имя модели после logic должно начинаться с заглавной буквы ?
> Везде подобные ограничения (имена событий, операций, фреймов и др) ?

Существует ограничение, связанное с генерацией кода. Как минимум у ресурсов, им надо генерить геттеры, а для геттеров получается: `a` -> `getA()`, т.е. часть после гет начинается с большой буквы. Тогда иксбейз распознает их как геттер. Поэтому я запретил давать имена ресурсам с большой буквы. Потом решил распространить это правило на все элементы грамматики и просто сделать строгий код стайл.

> Не хватает ++ и -- (#403)

Согласен, не хватает. Это довольно сложная задача.

> Можно ли избавиться от # в последовательности sequence clientInputInterval = new Values(#[14, 13, 17, 15, 16, 15, 14, 22, 19]) ? Квадратные скобки конфликтуют с другим использованием ?

Нельзя. Это синтаксис иксбейза. Просто квадратные скобки обозначают лямбду.

> Нечитаемые сообщения об ошибке, пример для кода

Посмотрю.

> После создания модели из визарда некоторые строки отмечены как ошибки, хотя она нормально запускается. Если её перезаписать, то ошибки пропадают. Под виндой и маком проявляется постоянно, под убунтой редко.

Можно не перезаписывать, достаточно поставить, например, пробел в модели и стереть его, главное как-то заставить иксбейз вызвать инферер заново. Противный баг, согласен, но его на данный момент не очень понятно, как исправлять.

**Comment by aurusov** [comment]
А что насчет

> Если создать пустую модель и скопировать в него старую модель, то начинают вылезать диалоги с ошибками. Лезут почти на каждое изменение символа в модели. Очень мешают работать.

?

**Comment by bogachev-pa** [comment]
Не встречал такое, посмотрю.

**Comment by bogachev-pa** [comment]
> Если создать пустую модель и скопировать в него старую модель, то начинают вылезать диалоги с ошибками. Лезут почти на каждое изменение символа в модели. Очень мешают работать.

Не воспроизводится. Копирую старую модель в новую пустую, подсвечивается много ошибок, но никаких диалоговых окон не появляется.
Убунту 15.10, эклипс марс р2.

**Comment by aurusov** [comment]
Делал под виндой, mars 2. Попробую воспроизвести.

**Comment by bogachev-pa** [comment]
Здесь все раскидано на отдельные задачи или что-то еще осталось?

**Comment by aurusov** [comment]
Вот теперь да, закрываю.
