### ISSUE TITLE
Упростить название конфигурации

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#429]
@k-alexandrovsky @bogachev-pa 
Почему бы не назвать конфигурацию запуска проще: `runtime-EclipseXtext` -> `EclipseXtext` или `raox` ? Тогда не пришлось бы корректировать _Location_. Вопрос в первую очередь в Кириллу. Кажется, что это было для чего-то нужно.

**Comment by bogachev-pa** [comment]
Имя конфигурации запуска не имеет значения. По-моему, `runtime-EclipseXtext` - название, которое давалось раньше по умолчанию.

**Comment by aurusov** [comment]
Тогда я упрощу описание
