### ISSUE TITLE
Изменить алгоритм ядра симулятора

### ISSUE THREAD

**Issue by k-alexandrovsky** [LeKaitoW/raox#43]
https://github.com/k-alexandrovsky/k-alexandrovsky.github.io/issues/1#issuecomment-113623550

**Comment by bogachev-pa** [comment]
Как и в таске про енумы, непонятно, о чем речь. Нужно краткое описание. По ссылке все поехало.

**Comment by aurusov** [comment]
@bogachev-pa 
https://github.com/k-alexandrovsky/k-alexandrovsky.github.io/issues/1#issuecomment-113613594
https://github.com/k-alexandrovsky/k-alexandrovsky.github.io/issues/1#issuecomment-113627685

**Comment by aurusov** [comment]
@k-alexandrovsky 
Кирилл, напомни: ты исправил код, когда делал дисты ?

**Comment by k-alexandrovsky** [comment]
Видимо, у себя в локальном репозитории, который убил после того, как был переезд. Решил, что вряд ли там были сильно важные изменения. Сейчас вот вспоминаю, что были.

**Comment by aurusov** [comment]
Фигово. Ты можешь восставновить/воспроизвести код ? Если нет, то опиши задачу нормальными словами вместо ссылки.

**Comment by aurusov** [comment]
@k-alexandrovsky
ping
