### ISSUE TITLE
Юнит-тесты

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#430]
Паша, у нас в юнит тестах только Олины процессные ? Мне казалось, что были еще какие-то.

**Comment by bogachev-pa** [comment]
Есть еще простейший тест трассировщика. Раньше был еще тест математических функций, но теперь мы берем их из либы, и я его спилил.

**Comment by aurusov** [comment]
https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao.tests/src/ru/bmstu/rk9/rao/tests/unit/TracerUnitTest.java ?

**Comment by bogachev-pa** [comment]
Да.

**Comment by aurusov** [comment]
Хорошо. В тестах есть проблема https://github.com/aurusov/raox/issues/411. Насколько я понимаю, из-за неё мы не сможем гонять тесты на сервере.

**Comment by aurusov** [comment]
Еще вопрос. Вот есть ошибка https://github.com/aurusov/raox/issues/411. Но все тесты запускаются и проходят, даже для трассировки. Как такое возможно ? Нафига тогда тут сгенеренный код ?

**Comment by bogachev-pa** [comment]
Ошибка #411 - это ошибка сборки под неон, причем тут она?
Не понял вашего вопроса.
В юнит-тестах рао не используется как плагин и никакого кода не генерится.
В отличие от тестов моделей.

**Comment by aurusov** [comment]
Генерится, посмотри сам. Это ошибка в пакете _тестов_, которые мы тут обсуждаем. Получается
- ошибка важна,она влияет на тесты, её надо править
- она неважна, не влияет на тесты, тогда зачем этот код в тестах

Вопрос важности уместно обсудить в теме про тесты - #411 может оказаться неактуальной задачей.

**Comment by bogachev-pa** [comment]
Теперь понял, о чем вы. Посмотрю.
