### ISSUE TITLE
 Indoor навигация

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#437]
Почитать про одно из решений https://habrahabr.ru/company/sap/blog/267433/
- На мобильном в фоне крутится приложение, которое чекает или Wi-Fi точки доступа или Bluetooth-маяки, как в статье выше
- Отправляет данные на сервер по HTTP. Используем [nginx](https://github.com/aurusov/raox/wiki/nginx) и [Poco HTTP server](https://github.com/aurusov/poco-http-server).
- Сервер складывает данные в базу, например, [ClickHouse](https://clickhouse.yandex/).
- Десктоп-клиент ходит на этот же сервер и отображает траекторию мобильника на карте через [API  Яндекс.Карт](https://tech.yandex.ru/maps/) или накладывает их на самодельную карту Бауманки.

**Comment by nikolayantoncev** [comment]
Застолбил курсовой. Если я правильно понимаю, навигация будет для тех кто плохо знает ГЗ?

**Comment by aurusov** [comment]
Да, отличная мысль. Можно раздавать приложение абитуриентам. На карту нанести кабинеты, где сидят кафедры во время приема. И показывать где сейчас находится мобильник. Можно даже маршрут построить. Актуально для идиотских аудиторий, к которым можно пробраться только по специальным лестницам. Но это скорее для первокурсников, и вообще довольно сложная задача. Так что пока не думаем в эту сторону. Думаем только про позиционирование внутри здания. Это уже тянет на курсовой.

**Comment by aurusov** [comment]
@nikolayantoncev, @tinka94
Как я понял, вы договорились, что эта тема будет за Никитой ? Если да, то какую тему берет Коля ?

**Comment by nikolayantoncev** [comment]
@aurusov 
Да так и есть. Если не занята тема "Трекинг мобильника" я бы взял ее.

**Comment by aurusov** [comment]
@nikolayantoncev
Я бы закрепил, но вы который день не принимаете [приглашение](https://github.com/aurusov/raox/wiki/Дорожная-карта-новичка#%D0%A7%D1%82%D0%BE%D0%B1%D1%8B-%D0%B7%D0%B0%D0%BA%D1%80%D0%B5%D0%BF%D0%B8%D1%82%D1%8C-%D1%82%D0%B5%D0%BC%D1%83).

**Comment by aurusov** [comment]
В Android Studio создать приложение с полем ввода. По нажатию на кнопку
- его значение переписывается в label
- исходное поле очищается
- значение передается poco-http-серверу
- по запросу get_value сервер отдает это значение браузеру
