### ISSUE TITLE
Апвизор

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#441]
Разработчик приложения хочет анализировать поведение пользователей своих программ. Это можно делать через отправку событий, привязанных к кнопкам и др. элементам (#436). Хочется разработать альтернативный механизм:
- Не связывать руками события с кнопками, а автоматически фиксировать нажатия на элементы управления.
- Отправлять на сервер не только факт события, но и скриншот
- На основе отправленных скриншотов иметь возможность просмотреть мультфильм действий пользователя. Смотреть мультфильм надо через браузер.

Что-то аналогичное [вебвизору](https://metrika.yandex.ru/promo/webvisor/), но только для мобильных.

Возможное упрощенное решение
- За основу берётся #436 задача.
- На сервер заранее загружаются скриншоты приложения.
- На сервере события из #436 и сриншоты склеиваются в мультфильм.

**Comment by aurusov** [comment]
- не понял 1
- не понял 2
- не понял 3

**Comment by aurusov** [comment]
1. В Android Studio разработать простейшее приложение с 2-3 экранами. Между ними надо переключаться. На экрана несколько кнопок и других элементов gui. Свойства элементов должны сохраняться при переключении между экранами. (на неделю)
2. Разработать отдельную либу, которая должна ловить нажатия на произвольное место на экране. Либа должна быть интегрирована в приложение от сторонняя SDK.

**Comment by aurusov** [comment]
Что сделано по двум разделам последнего сообщения ?

**Comment by Belka-W** [comment]
1-ое сделано полностью

2-ое Ищу способ сделать глобальный независимый слушатель для всех кнопок. чтобы библиотека не перехватывала события, а работала совместно с уже написанными слушателями.

**Comment by aurusov** [comment]
То, что не получилось сделать глобального слушателя, можно написать в записке.
