### ISSUE TITLE
Сломалось rcptt-тестирование для 3.x версий

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#443]
Локально тестирование проходит. Через Дженкинс - нет. Прошу через консоль на Дженкинсе запустить тесты.

**Comment by bogachev-pa** [comment]
Проблема в том, что тесты требуют графический интерфейс. На дженкинсе поднимаем его временно с помощью плагина `xvnc`. Руками его поднять, кажется, довольно проблематично. Поэтому руками потестить не получится.

Можно попробовать как-то почистить тот эклипс или заменить его на новый.

**Comment by aurusov** [comment]
- Для начала хочется выполнить через терминал тот же скрипт, что выполняется в задаче.
- Потом попробовать увеличить память через config.ini
- И только потом думать в сторону xvnc

**Comment by bogachev-pa** [comment]
Он не выполнится, т.к. он запускает эклипс. Эклипс не запустится, т.к. нет графического интерфейса.

**Comment by aurusov** [comment]
Не понимаю, что мешает это выполнить из консоли

``` bash
export MAVEN_OPTS="-Xmx512M"
mvn initialize -N
mvn -U clean package

rm -r /home/rdo/eclipses/to_test/eclipse/dropins/plugins/*
cp assembly/target/plugins/* /home/rdo/eclipses/to_test/eclipse/dropins/plugins/

./ru.bmstu.rk9.rao.rcptt/run_tests.sh \
    /home/rdo/rcptt/eclipse \
    /home/rdo/eclipses/to_test/eclipse
```

**Comment by bogachev-pa** [comment]
```
./ru.bmstu.rk9.rao.rcptt/run_tests.sh \
    /home/rdo/rcptt/eclipse \
    /home/rdo/eclipses/to_test/eclipse
```

Упадет на попытке запустить эклипс. Если вас это не смущает, то могу выполнить, конечно. Но не вижу в этом никакого смысла.

**Comment by aurusov** [comment]
А как эту команды выполняет Дженкинс ?

**Comment by aurusov** [comment]
Кажется понял, чуть выше есть `Run Xvnc during build`

**Comment by aurusov** [comment]
Обратил внимание на две вещи
- Первый тест проходит, http://jenkins.raox.rk9.bmstu.ru/job/raox-test/7/console. М.б. он что-то ломает в конце ?
- Содержимое скрипта `run_tests.sh` невалидно, как минимум в одном месте. `autPath=/home/rdo/eclipses/to_test/eclipse-dsl-mars-1-linux-gtk-x64` - нет такого пути. Исправил на текущее значение, не помогло. Старый скрипт переименовал в `run_tests.sh.backup`.

**Comment by aurusov** [comment]
Еще странности. Вот кусок лога

```
!ENTRY org.eclipse.rcptt.launching 2 0 2016-09-21 01:20:17.037
!MESSAGE Skip unexisted bundle: null, then resolve configuration.

!ENTRY org.eclipse.rcptt.launching 2 0 2016-09-21 01:20:17.042
!MESSAGE Skip unexisted bundle: null, then resolve configuration.

!ENTRY org.eclipse.rcptt.launching 2 0 2016-09-21 01:20:17.042
!MESSAGE Skip unexisted bundle: null, then resolve configuration.

!ENTRY org.eclipse.rcptt.launching.ext 1 0 2016-09-21 01:20:17.043
!MESSAGE RCPTT: Launching AUT: AUT_0: Detected AUT architecture is x86_64.64bit arch is selected because AUT uses launcher li
brary
        "plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417" specified in config file: eclipse.ini

!ENTRY org.eclipse.rcptt.launching.ext 1 0 2016-09-21 01:20:17.064
!MESSAGE RCPTT: Launching AUT: AUT_0: Selected JVM is /usr/lib/jvm/java-8-oracle detected architecture is x86_64

!ENTRY org.eclipse.rcptt.launching.ext 1 0 2016-09-21 01:20:17.064
!MESSAGE RCPTT: Launching AUT: AUT_0: JVM and AUT architectures are compatible: true. JVM is 64bit and support running 32bit:
 false

!ENTRY org.eclipse.pde.core 4 204 2016-09-21 01:20:18.391
!MESSAGE Error reading manifest for /home/rdo/eclipses/to_test/eclipse/dropins/plugins/ru.bmstu.rk9.rao-2.13.0.jar

!ENTRY org.eclipse.pde.core 4 204 2016-09-21 01:20:18.392
!MESSAGE Error reading manifest for /home/rdo/eclipses/to_test/eclipse/dropins/plugins/ru.bmstu.rk9.rao.lib-2.13.0.jar

!ENTRY org.eclipse.pde.core 4 204 2016-09-21 01:20:18.392
!MESSAGE Error reading manifest for /home/rdo/eclipses/to_test/eclipse/dropins/plugins/ru.bmstu.rk9.rao.ui-2.13.0.jar
```

Ну нет в этой директории таких файлов. Там лежит версия 3.1.0 !!!

**Comment by bogachev-pa** [comment]
> Первый тест проходит, http://jenkins.raox.rk9.bmstu.ru/job/raox-test/7/console. М.б. он что-то ломает в конце ?

Нет, он проходит потому что не использует плагин рдо.

> Еще странности. Вот кусок лога

Видимо, причина где-то здесь. Надо попробовать снести оттуда эклипс и положить чистый.

**Comment by bogachev-pa** [comment]
Починилось. Закрываем?

**Comment by aurusov** [comment]
Да
