### ISSUE TITLE
3.1.0 не может запустить модель

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#445]
Иногда модель запускалась по 40 секунд, иногда не запускалась и минут 5. Иногда помогала перезагрузка, иногда - нет. В консоль ничего не пишется. Проявлялось по Ubuntu 16.04. Под Виндой было нормально.

Паша предложил увеличить размер памяти в config.ini. У меня еще мысли - проверить под Неоном.

**Comment by bogachev-pa** [comment]
В эту субботу лучше себя вел?

**Comment by aurusov** [comment]
Да, все хорошо.
