### ISSUE TITLE
Ошибка компиляции if'а

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#452]
``` erlang
boolean робот_связан_со_станком(int номер_робота, int номер_станка)
{
    if (номер_робота == 2)
        return номер_станка == 1 || номер_станка == 2;
    else if (номер_робота == 3)
        return номер_станка == 3;

    return false;
}
```

line 3, warning
Missing else branch for conditional expression with primitive type

line 5, error
Multiple markers at this line - номер_робота cannot be resolved to a type. - mismatched input 'else' expecting 
 '}' - mismatched input '==' expecting ')'

line 6, error
mismatched input '==' expecting '('

Достаточно расставить фигурные скобки

``` erlang
boolean робот_связан_со_станком(int номер_робота, int номер_станка)
{
    if (номер_робота == 2) {
        return номер_станка == 1 || номер_станка == 2;
    }
    else if (номер_робота == 3) {
        return номер_станка == 3;
    }

    return false;
}
```

**Comment by aurusov** [comment]
Что-то сильно поломалось. Писать алгоритмы можно только с `{` и `}`.

**Comment by bogachev-pa** [comment]
Не понял. Что еще (помимо скобок) поломалось?

**Comment by bogachev-pa** [comment]
Посмотрел.
Уберите `;` в конце выражений.
В иксбейзе это означает, что надо закончить текущее условие.

``` java
boolean робот_связан_со_станком(int номер_робота, int номер_станка)
{
    if (номер_робота == 2)
        return номер_станка == 1 || номер_станка == 2
    else if (номер_робота == 3)
        return номер_станка == 3

    return false;
}
```

Вообще, стоит везде в примерах писать без `;`, т.к. это `xbase-style`. Точки с запятой нужны только если нужно явно указать, что это конце выражения, например:

``` java
void x(int a) {
    if (a > 0)
        return; //";" обязательна, иначе это будет return println("hello")

    println("hello")
    return // ";" не обязательна
}
```

**Comment by aurusov** [comment]
Уфф. Но хорошо, что работает.
