### ISSUE TITLE
Зачем-то требует init для кадра анимации

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#453]
``` erlang
frame Frame {
    set init() {
    }
    set draw() {
        drawText('Время:', 10, 5);
    }
}
```

Пустой метод init() обязателен. Если его убрать, то будет runtime-error
`Project contains errors:
file test.java at line 2130: The type test.Frame must implement the inherited abstract method AnimationFrame.init()`.

**Comment by bogachev-pa** [comment]
Упс, я хотел сделать под этот метод стаб, чтобы он был необязателен, и забыл.
Поправлю.

**Comment by bogachev-pa** [comment]
Сделал пул-реквест.
