### ISSUE TITLE
Неверно работает форматирование resultType

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#456]
``` erlang
resultType Длина_очереди<Integer>(Парикмахерские парикмахерская) {
    set evaluate() {
    return парикмахерская.количество_в_очереди;
}
}
```

**Comment by bogachev-pa** [comment]
Мне почему-то казалось, что Леша это делал, однако в исходниках нет.
Надо просто добавить пару правил в [форматтер](https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao/src/ru/bmstu/rk9/rao/formatting2/RaoFormatter.xtend).

Работы на 10 минут, можете поручить студенту, если еще остались те, кому нужны простые задачи.

**Comment by aurusov** [comment]
Да, работа для бонуса, но не хочется затягивать. Поэтому лучше бы Леша и до того, как студенты начнут пользоваться.

**Comment by AlexChernov** [comment]
Решено и добавлено в https://github.com/aurusov/raox/pull/527
