### ISSUE TITLE
Упростить отчет о вершине

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#458]
![2016-09-24_22-28-09](https://cloud.githubusercontent.com/assets/5585202/18810736/3fc19f6c-82a6-11e6-841d-71ba78f16688.png)

Надо делать как в трассировке (можно и методы оттуда переюзать):
- если в модели один файл - используем короткое имя `фишка2`
- если в модели более одного файла - используем полное имя `qqq.фишка2`

Имя проекта отбрасывается всегда.

**Comment by bogachev-pa** [comment]
Что если в модели более одного файла и в обоих есть ресурс `фишка2`?
Тут надо делать как в трассировке (можно и методы оттуда переюзать):
- если в модели один файл - используем короткое имя `фишка2`
- если в модели более одного файла - используем полное имя `qqq.фишка2`

Имя проекта отбрасывается всегда, тут да.

**Comment by aurusov** [comment]
Согласен. Обновил постановку.
