### ISSUE TITLE
Упростить drawText

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#459]
Для вывода числовых значений в анимации необходимо писать

``` erlang
drawText(currentTime.toString(), 60, 5);
```

Для упрощения можно запилить сигнатуру `drawText` с `Object` в качестве первого параметра и делать `toString()` внутри самого метода.

**Comment by aurusov** [comment]
Делает Георгий Емельянов

**Comment by Goga9510** [comment]
Андрей Витальевич сделал, коммиты объединил
