### ISSUE TITLE
Расставить final

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#46]
Чтобы не захламлять пул-реквест множеством однотипных комментов, решил вынести в отдельную таску.
1. `ru.bmstu.rk9.rdo.lib/src/ru/bmstu/rk9/rdo/lib/Database.java`, `Database(JSONObject modelStructure)`, очень много похожих мест

``` java
JSONObject pattern = patterns.getJSONObject(i);
String name = pattern.getString("name");
patternsByName.put(name, pattern);
```

``` java
final JSONObject pattern = patterns.getJSONObject(i);
final String name = pattern.getString("name");
patternsByName.put(name, pattern);
```

**Comment by bogachev-pa** [comment]
Сделал. Можно настроить автоматическое добавление `final` и прочие штуки в эклипсе.
`Windows -> Preferences -> Code Style` создать новый профиль, основанный на стандартном эклипсовском и настроить его нужным образом.
Потом нажать правой кнопкой в коде -> `Source -> Clean Up`.

Может отдельным рефакторингом пройтись такой штукой по всему проекту?

**Comment by aurusov** [comment]
Если честно, то не хочется захламлять код final. Не смог найти веских аргументов про final для локальных переменных. Оптимизатор и так может понять меняется ли переменная внутри метода imho. Кажется, что final **надо** указывать, когда хочешь гарантировать, что она не менятеся. Но в простом коде, как пример выше, это и так понятно.

**Comment by aurusov** [comment]
Откатывать коммит не надо. Я вслух рассуждаю. Ты как сам думаешь ?

**Comment by bogachev-pa** [comment]
Думаю, что в случае с локальными переменными это действительно только захламляет код.

Однако в случае с полями классов, на мой взгляд, надо указывать всегда. В `Code Style` можно, кстати, настроить, чтобы `final` добавлялся только перед неизменяемыми полями классов.
Насчет параметров методов не уверен, но думаю, тоже стоит всегда ставить.

**Comment by aurusov** [comment]
По политическим решениям не хочется менять стил по умолчанию. Но давай заведем таску, в которую накидаем пожелания к новому стилю. Пусть глаза мозолит, поживем с ней. Если поймем, что этого не хватает, то будем внедрять свой стиль.

**Comment by bogachev-pa** [comment]
Готово. Думаю, эту таску стоит закрыть.
