### ISSUE TITLE
Не получается задать alignment

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#463]
Не компилируется

``` erlang
drawText("text", 0, 300, RaoColor.RED, 200, Alignment.LEFT);
```

**Comment by bogachev-pa** [comment]
С какой ошибкой?

**Comment by aurusov** [comment]
Ага, он предлагает сделать импорт

``` java
import ru.bmstu.rk9.rao.lib.animation.AnimationContext.Alignment
```

После этого работает.

**Comment by aurusov** [comment]
Теперь другая проблема - чтобы я не написал, всегда выравнивает по левому краю.

**Comment by bogachev-pa** [comment]
Я вообще хотел неявные импорты для таких вещей. Так что надо поправить.
С неправильным выравниваем посмотрю, я вроде это не трогал.

**Comment by bogachev-pa** [comment]
Пул-реквест на неявный импорт сделал.

Что касается хэндлинга выравнивания, я его по каким-то причинам отложил на потом (https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/animation/AnimationContextSWT.java#L74), уже не помню по каким. Надо допиливать.
Лучше отдельным пул-реквестом.

**Comment by aurusov** [comment]
Завел бонусную задачу https://github.com/aurusov/raox/issues/487
