### ISSUE TITLE
Выбор релевантного ресурса по имени ресурса

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#466]
Модель https://github.com/aurusov/raox-models/blob/master/models/fms.rao

Вот такой код работает

``` erlang
relevant станок = станок_3.onlyif[состояние == Состояние_станка.ЗАКОНЧИЛ_ОБРАБОТКУ];
```

Но как правильно записать, если условие неважно ? Руки пишут такое

``` erlang
relevant станок = станок_3;
```

После чего перестает компилироваться. Это бага/фича ? Как правильно писать ?

**Comment by bogachev-pa** [comment]
Это фича.

Зачем вам в таком случае подбирать его как релевантный?
Просто используйте `станок_3` в коде паттернов.

**Comment by aurusov** [comment]
Чтобы видеть все ресурсы, которые требуются паттерну. Как тебе функция в Джаве, у которой только два параметра, но внутри еще три статика используются. Т.е. по сути 5 параметров, но знаешь ты только про 2. Я не про, чтобы запретить прямое использование (хотя почему нет), просто хочется иметь возможность в явном виде их указывать для чистоты кода. И еще - а как обстоит дело с accessible для них ? Оно же НЕ проверяется ?

**Comment by bogachev-pa** [comment]
Тогда попробуйте

``` erlang
relevant станок = станок_3.onlyif[accesible]
```

**Comment by aurusov** [comment]
Ты хочешь сказать, что

``` erlang
relevant станок = станок_3.onlyif[состояние == Состояние_станка.ЗАКОНЧИЛ_ОБРАБОТКУ];
```

не проверяет на accesible ?

**Comment by bogachev-pa** [comment]
Сейчас нет. Наверное, стоит это поправить.
С другой стороны, как подобрать тогда `не-только-accessible`?

**Comment by aurusov** [comment]
Ура, ты понял вторую часть моего вопроса. Т.е. нужен механизм, который ортогонально
- берёт accessible/no_accessible/any_state с одной стороны (три состояния)

**и**
- проверяет условие или берет безусловно, с другой

**Comment by bogachev-pa** [comment]
Такое у меня работает:

``` erlang
relevant станок = станок_3;
```

Что у вас за ошибка компиляции?

Насчет аксессибл, вроде придумал схему, вечером попробую заимплементить.

**Comment by aurusov** [comment]
Не получается повторить, теперь тоже все нормально. Очень странно.

**Comment by bogachev-pa** [comment]
Насчет аксессибл, я еще немного обдумал это, и в итоге текущая схема ведь все может:

``` java
// без проверки доступности и условий вообще
relevant станок = станок_3 
// по accessible, без доп. условий
relevant станок = станок_3.onlyif[accessible] 
// по !accessible, без доп. условий
relevant станок = станок_3.onlyif[!accessible]
 // по условию, не зависимо от доступности 
relevant станок = станок_3.onlyif[a > 0]
 // по условию и доступности
relevant станок = станок_3.onlyif[accessible && a > 0]
```

В принципе даже в подборе ресурсов из типа можно использовать `accessible` именно так, просто там есть удобный враппер, который можно сразу применить вместо `all`. 

Чем тогда текущая схема плоха?

**Comment by aurusov** [comment]
Мне хотелось бы безопасного использования по-умолчанию. Пример для релевантного ресурса по типу, которой не надо делать. Просто пример

``` erlang
relevant res = Type.filter[param == 2].any;
```

По умолчанию должно работать в режиме

``` erlang
relevant res = Type.accessible.filter[param == 2].any;
```

, а не

``` erlang
relevant res = Type.all.filter[param == 2].any;
```

Потому что `all` - выстрел себе в ногу. Надо сознательно такое делать. Хотелось бы такой же логики в тут. Твой вариант проще и его не надо кодить. Это подкупает. У тебя есть простой вариант для моих хотелок ?

**Comment by bogachev-pa** [comment]
Вот это

``` erlang
relevant res = Type.filter[param == 2].any;
```

в принципе можно сделать, если типу ресурса завести такой метод и сделать его враппером над `accessible.filter[]`

Вот для такого:

``` erlang
relevant станок = станок_3 
```

точно сложно придумать, т.к. здесь мы просто дергаем геттер.

Вставлять какие-то проверки в геттер точно будет странно, так как мб мы ходим его в режиме `read-only` получить. Т.е. так или иначе надо делать `onlyif[accessible]`. Можно для `onlyif[accessible]` сделать враппер типа `safe`, но принципиально это ситуацию не меняет.

**Comment by aurusov** [comment]
Ну тогда давай оставим как есть.

**Comment by aurusov** [comment]
Проблема из топика не повторилась, закрываю.
