### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#47]
@aurusov, @k-alexandrovsky, @LeKaitoW, @kstrizhov

Начало обсуждения тут: https://github.com/aurusov/rdo-xtext/issues/46, кто не видел, почитайте.

Таска про обсуждение код-стайла.
Уже обсуждали форматированием, там остановились на дефолтном форматере.
Но эклипс также позволяет автоматически править и код-стайл. В частности добавлять `final` где нужно, добавлять автоматические `@Override`, расставлять фигурные скобки в `if` блоках и тому подобное.

Настройки по умолчанию такие:

```
Change non static accesses to static members using declaring type
Change indirect accesses to static members to direct accesses (accesses through subtypes)
Remove unused imports
Add missing '@Override' annotations
Add missing '@Override' annotations to implementations of interface methods
Add missing '@Deprecated' annotations
Remove unnecessary casts
Remove unnecessary '$NON-NLS$' tags
```

Вопрос в том, хотим ли мы автоматизировать такие вещи как:
- добавление `final` к константным полям класса
- добавление `final` к константым параметрам методов
- добавление фигурных скобок вокруг всех конструкций типа `if`, `for` и т.п.
- т.п.

Мое мнение такое: не нужно делать это обязательным к использованию, но кто хочет, почему бы и не пользоваться настроенным код стайлером. Это ускорит код ревью и все такое. И, конечно, если использовать свой стиль, ничего из стиля по умолчанию убирать нельзя, только добавлять новые пункты. Т.е. свой стиль должен быть как минимум не менее строгий, чем дефолтный.

**Comment by aurusov** [comment]
> Мое мнение такое: не нужно делать это обязательным к использованию, но кто хочет, почему бы и не пользоваться настроенным код стайлером.

Не, всем надо будет настроить эклипс на единый стиль. Мы же можем поправить переносы строк и т.д.

**Comment by aurusov** [comment]
Давно не актуально, закрываю.
