### ISSUE TITLE
В логике не работает подсветка и автозавершение кода

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#472]
- Внутри методы init()
  - ни один из параметров не подсвечивается
  - ни один из параметров нельзя автозавершить
  - автозавершение вообще не вызывается внутри init(), а подсмотреть что можно написать хочется
- Внутри logic
  - не работает автозавершение при написании активности

``` erlang
logic Обработка {
    set init() {
        condition = [true];
        parent = Транспортировка;
        priority = [0.1];
    }
}
```

**Comment by bogachev-pa** [comment]
`logic` требует наличие хотя бы одной активности
т.к. вы не указали не одной, компилятор ждем кода активности и считает текущий код невалидным - потому ничего и не подсказывает

**Comment by aurusov** [comment]
Ну во первых это не логично: я же хочу внутри метода init() автозавершение. Почему на это должны влиять активности. Во вторых, все у меня в Эклипсе указано. Скопипастил только малую часть. Обновил постановку.

**Comment by bogachev-pa** [comment]
Окей, проверю.

**Comment by aurusov** [comment]
К слову, аналогично ведет себя search. Но там хотя бы параметры внутри init() подсвечены.

**Comment by bogachev-pa** [comment]
Подсветка и не должна работать, т.к. `condition` и т.п. это все просто методы. Для них особой подсветки нет (но если, например, поменяете в эклипсе цвет, которым подсвечиваются методы - увидите).
Автодополнение у меня работает:

![code_complited](https://cloud.githubusercontent.com/assets/6528492/18948322/a88101ce-8647-11e6-8774-f048c76aa261.png)

**Comment by aurusov** [comment]
Вижу, у меня - нет. Печаль. Попробую на новом воркспейсе... Появилось дополнение и внутри init и внутри logic, норм. Осталось понять с подсветкой. Она же есть для `search`
![models - rao - test-test rao - eclipse _002](https://cloud.githubusercontent.com/assets/5585202/18949482/39a6d97a-8644-11e6-8957-bb65ef18035e.png)

**Comment by bogachev-pa** [comment]
Теперь понял. Это связано с тем, что в `search` это `protected` поля, а в `Logic` это `private` поля и публичные методы. В итоге в `search` подсветка как у полей, а в `logic` как у методов.
Не помню, специально так делал `logic` через методы или просто не сравнивал с `search` и не обратил внимания на разницу.

Если можно безболезненно перевести `logic` так же на `protected` поля, то сделаю это.

**Comment by bogachev-pa** [comment]
Сделал пул-реквест.
