### ISSUE TITLE
Как задать приоритет активности ?

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#473]
Вот активность. Куда писать приоритет ?

``` erlang
logic Обработка {
    activity обработка_на_станке_1 = new Activity(Обработка_на_станке.create());
}
```

**Comment by bogachev-pa** [comment]
Вроде же обсудили? в `set init() {}`
После перечисления активностей.

**Comment by aurusov** [comment]
Да блин же. Что-то последние твои ответы выглядит как отписки. Не разобрался что-ли ? Я про приоритет каждой отдельной активности, а не логики. Раньше было так
`activity имя_активности(приоритет_активности) checks имя_образца(парамеры_образца);`

**Comment by bogachev-pa** [comment]
Не так прочитал. Просто вторым параметром.

``` erlang
logic Обработка {
    activity обработка_на_станке_1 = new Activity(Обработка_на_станке.create(), 0);
    activity обработка_на_станке_2 = new Activity(Обработка_на_станке.create(), [sequence_1.next()]);
}
```

Посмотреть конструкторы можно тут:
https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao.lib/src/ru/bmstu/rk9/rao/lib/dpt/Activity.java

**Comment by aurusov** [comment]
О, спасибо.
