### ISSUE TITLE
Что-то с медианой

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#482]
Результаты [модели](https://github.com/aurusov/raox-models/blob/master/models/barber_simple/barber_simple.rao)

```
test.test.длина_очереди: Длина_очереди
    Mean: 7.80936981684077
    Median: 0.0
    Standard deviation: 6.571400499212813
    varcoef: 552.9678518736604
```

Почему у медианы ноль ?

**Comment by bogachev-pa** [comment]
Подозреваю, что это просто не реализовано. Старая медиана, насколько я помню, считалась неправильно. Новая, видимо, еще не запилена.
Если пилить долго, предлагаю просто пока выкинуть ее из окна результатов.

**Comment by aurusov** [comment]
Тогда пусть задача станет багой. Леша, это к тебе.

**Comment by aurusov** [comment]
Дубликат https://github.com/aurusov/raox/issues/532
