### ISSUE TITLE
Alignment не выравнивает текст

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#487]
Выравнивание текста всегда по левому краю, независимо от значения alignment.

**Comment by OlgaBlu** [comment]
Здравствуйте.
Хочу взять эту задачу для бонуса.
Ольга Блудова, РК9-81.

**Comment by aurusov** [comment]
Берите

**Comment by aurusov** [comment]
![2017-04-29_13-36-50](https://cloud.githubusercontent.com/assets/5585202/25554851/eea86d96-2ce0-11e7-89a2-91229e8cd83b.png)

Это палево. Бонус снимаю у обоих.

**Comment by aurusov** [comment]
@OlgaBlu
@smirnov-vs

Смотрим коммент выше и не удивляемся ведомости.

**Comment by smirnov-vs** [comment]
неловко вышло
