### ISSUE TITLE
У графиков не появляются ползунки прокрутки

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#49]
Если вызвать приблизить/отдалить через меню, то не появляются ползунки прокрутки. Не работает для всех комманд из этих меню. Если масштабировать мышкой, то появляются.
![2015-06-27 22 19 00](https://cloud.githubusercontent.com/assets/5585202/8393495/8b5ebb14-1d1a-11e5-950d-7f4c781be90a.png)

**Comment by bogachev-pa** [comment]
Это сейчас работает?

**Comment by aurusov** [comment]
Нет, я не подливал

**Comment by bogachev-pa** [comment]
Что-то блокирует?

**Comment by aurusov** [comment]
Свободное время

**Comment by aurusov** [comment]
По задаче осталось неблокирующая курсач подзадача. Почему-то не работает ограничение на масштаб (чтобы не уходить в точку, к примеру). Подписчики есть, но текущее значение масштаба в них неадекватное. Подключаюсь, хочу сам посмотреть, на консультации не получилось понять.

**Comment by ViktorRakhmatulin** [comment]
Вроде настроено, еще на консультации проверяли.
