### ISSUE TITLE
Простейший счетчик Value делает больше, чем нужно

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#493]
Модель из визадра, показатель

``` erlang
result Пропускная_способность = new Value([парикмахерская.количество_обслуженных / currentTime * 60]);
```

В отчете _одно_ число, что ожидается

```
test.test.Пропускная_способность: Value
    Value: 1.8162890483219594
```

А на графике вся история _наблюдения_ за значением
![runtime-raox-ch - rao - eclipse platform _003](https://cloud.githubusercontent.com/assets/5585202/19019569/405cdd20-8895-11e6-84b5-a7b33db0a182.png)

Тут что-то нелогичное. Я то думал, что значение считается только в момент завершения модели. А тут получается, что это нет так. Из минусов - мы флудим в трассировку расчетами, которые _не показываем в отчете_, тратим время компа. Если бы не возможность построить графики, то это был бы мусор. Надо или прекратить их считать по ходу моделировать или выдавать какую-то статистику. Потому что график выглядит норм и может быть полезен. Но тогда нужно расширить отчет. Кажется, что надо свести к двум большим схемам
- Считаем показатель только в момент остановки модели, в трассировку приходит только одна строчка, время на расчеты не тратится.
- Считаем каждый раз, хоть `2 * 2`, хоть наблюдаем за параметром ресурса. На выходе и график и статистика.

Что думаете ?

**Comment by aurusov** [comment]
График слева по трассировке показателя (простейший Value, Карл), справа - по параметру ресурса
![runtime-raox-ch - rao - eclipse platform _004](https://cloud.githubusercontent.com/assets/5585202/19019685/3b449820-8898-11e6-9cbb-fabad8dbf256.png)

**Comment by AlexChernov** [comment]
Дело в том, что результат и статистика разные сущности. График и трассировка выводятся для результатов, отчет показывается для статистики.

**Comment by aurusov** [comment]
Обсудили, пришли к https://github.com/aurusov/raox/issues/497. Эту закрываю.
