### ISSUE TITLE
Перемещение по графику вправо-влево через колёсо мышки

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#50]
Никакие клавиши не зажаты

**Comment by Aleksandr15** [comment]
@aurusov 
Здравствуйте! Возник вопрос по исходникам . В исходнике [PlotFrame](https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/plot/PlotFrame.java) , как я правильно понимаю , horizontalSlider  и  verticalSlider - это оси координат ?

**Comment by aurusov** [comment]
Нет. Это ползуки прокрутки. https://www.google.com/search?q=org.eclipse.swt.widgets.Slider&oq=org.eclipse.swt.widgets.Slider&sourceid=chrome&ie=UTF-8. С зажатом `Ctrl` нажмите левой кнопкой на слове Slider в [этой](https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/plot/PlotFrame.java#L16) строке. Переместитесь на исходный код класса.

А вот [это](https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/plot/PlotFrame.java#L71) - оси.

**Comment by Aleksandr15** [comment]
Тогда следующий вопрос - получается нужно реализовать стандартными средствами эклипса или можно использовать библиотеку Swing (JScrollPane) ?

**Comment by aurusov** [comment]
Эклипса, возможностями SWT. Вы же видите импорты `org.eclipse.swt`. И возможностями `org.jfree`.

**Comment by Aleksandr15** [comment]
@aurusov  не могу найти точку инициализации

**Comment by aurusov** [comment]
Получилось ? Если нет, то где затык ?

**Comment by aurusov** [comment]
@Aleksandr15 
ping

**Comment by aurusov** [comment]
@ViktorRakhmatulin 
Витя, ты эту задачу не сделал в курсовом ?

**Comment by ViktorRakhmatulin** [comment]
Не сделал

**Comment by aurusov** [comment]
Сделал Владислав Смирнов
