### ISSUE TITLE
Визард создания моделей

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#53]
Обязательные функции, блокирующие первую лабу
- [x] Визард должен сам выставлять `Source folder name = src-gen`
- [x] Спрашивать имя модели
- [x] Проверять имя на допустимое (https://github.com/aurusov/rdo-xtext/issues/69)
- [x] Автоматом добавлять пустой файл модели с именем модели + `.rao`
- [x] Выставлять кодировку проекту UTF-8

Не блокирующая опция
- [x] Добавить не пустую модель, а одну из базы моделей
- [x] Выводить сообщение, если проект с таким именем уже существует
- [x] Украшательства, см. https://github.com/aurusov/rdo-xtext/issues/53#issuecomment-139914316
- [x] Удаление `srs-gen` и `bin` ведёт к [падению](https://github.com/aurusov/rdo-xtext/issues/157#issuecomment-139908354). Надо проверить, что починилось.

**Comment by LeKaitoW** [comment]
> Обязательные функции, блокирующие https://github.com/aurusov/rdo-xtext/issues/48
> - ~~Визард должен сам выставлять `Source folder name = src-gen`~~
> - ~~Спрашивать имя модели~~
> - Проверять имя на допустимое (https://github.com/aurusov/rdo-xtext/issues/69) 
> - ~~Автоматом добавлять пустой файл модели с именем модели + `.rao`~~
> - ~~Выставлять кодировку проекту UTF-8~~
> 
> Не блокирующая опция
> - ~~Добавить не пустую модель, а одну из базы моделей~~

Что ещё стоит добавить:
- Выводить сообщение, если проект с таким именем уже существует
- Украшательства (см. скрины, явно не хватает заголовка окошка, надписей как в джава-визарде про `Create a Java Project` и `Enter a project name`, картинки-иконки туда же. Может, чем-то ещё пространство под шаблонами заполнить?)
  ![wizard](https://cloud.githubusercontent.com/assets/10632455/9838826/e8c6da30-5a77-11e5-8317-e277d42b235a.png)
  ![sl5ksyfdumy](https://cloud.githubusercontent.com/assets/10632455/9838799/fbe4f85a-5a76-11e5-87bd-97022a8f8284.jpg)

**Comment by k-alexandrovsky** [comment]
А Project name == model name? Можно добавить галочку "specify model name", под ней будет текстбокс с возможностью поменять имя. При отжатой галочке текстбокс будет задизейблен, а в нем будет имя проекта. Если уж говорить об украшательствах и заполнении пустоты в визарде.

**Comment by LeKaitoW** [comment]
Сейчас пока тупо к введенному имени добавляется "_project". :(

**Comment by k-alexandrovsky** [comment]
Интересно. Но благо в эклипсе все можно переименовать потом. Вопрос, будет ли пользователь обижен до глубины души таким поведением :)

**Comment by bogachev-pa** [comment]
Можно было бы назвать их одинаково, но это лучше делать после того, как я исправлю https://github.com/aurusov/rdo-xtext/issues/33.

**Comment by aurusov** [comment]
Оля, обновил шапку. Лучше там обновлять итого, чтобы не искать потом в таске.

**Comment by aurusov** [comment]
Мой ответ на вопрос про украшательства тут https://github.com/aurusov/rdo-xtext/issues/161
Но это не сейчас.

**Comment by aurusov** [comment]
Еще раз обновил шапку

**Comment by bogachev-pa** [comment]
> Удаление srs-gen и bin ведёт к падению. Надо проверить, что починилось.

Проблема была в модел билдере. https://github.com/aurusov/rdo-xtext/pull/167

**Comment by aurusov** [comment]
> > Удаление srs-gen и bin ведёт к падению. Надо проверить, что починилось.
> 
> Проблема была в модел билдере. https://github.com/aurusov/rdo-xtext/pull/167

Проверил ?

**Comment by aurusov** [comment]
> - [x] Проверять имя на допустимое (https://github.com/aurusov/rdo-xtext/issues/69)

Разве это исправлено ?

**Comment by LeKaitoW** [comment]
Да, я ночью делала коммиты. :(

**Comment by aurusov** [comment]
Если Паша проверил, то надо ставить пул-реквест.

**Comment by bogachev-pa** [comment]
> Проверил ?

Вечером еще проверю, что нет конфликтов с визардом, но, по идее, с новым подходом не должно быть.

Edit: после исправлений в моем пул-реквесте все ок.

**Comment by bogachev-pa** [comment]
Еще момент: вероятно, надо добавить визард в `exported packages`.

**Comment by LeKaitoW** [comment]
> Еще момент: вероятно, надо добавить визард в exported packages.

Визард в экспорт добавила.

Обновила проверку на существование проекта, теперь точь-в-точь как в джава-проекте.
`enum ProjectWizardStatus` используется только для обработки ошибок при создании проекта.

> Если Паша проверил, то надо ставить пул-реквест.

Ставлю пулл-реквест.

**Comment by aurusov** [comment]
Тогда надо поставить галку у

> - [ ] Удаление `srs-gen` и `bin` ведёт к [падению](https://github.com/aurusov/rdo-xtext/issues/157#issuecomment-139908354). Надо проверить, что починилось.

**Comment by LeKaitoW** [comment]
Поставила. :(

**Comment by aurusov** [comment]
Дело же не в клике, а в ответственности за него. Лучше бы сам Паша поставил. Или он тебе делегировал ? :)

**Comment by LeKaitoW** [comment]
Я и надеялась, что он поставит, поэтому не ставила сама. :(
А перед пулл-реквестом спросила у него в контакте, проверял ли он.

**Comment by aurusov** [comment]
И что же он ответил ?

**Comment by LeKaitoW** [comment]
Дословная цитата:

> проверил, угу, там все норм

**Comment by aurusov** [comment]
Разобрались, Паша крайний.

**Comment by LeKaitoW** [comment]
Ураа.
