### ISSUE TITLE
Ошибка экспорта файла трассировки

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#531]
Если импортировать модель без копирования в `workspace`, то после `Model/Export Trace Output/Regular` возникает ошибка

![2016-10-31_01-25-22](https://cloud.githubusercontent.com/assets/5585202/19840536/ebe9aa68-9f08-11e6-8a61-8061f2734166.png)

Если импортировать модель с копированием, то все норм.

**Comment by AlexChernov** [comment]
Я вроде залезал в этот кусок в грядущем пулл реквесте, напомните как импортировать модель без копирования, пожалуйста

**Comment by aurusov** [comment]
![import _002](https://user-images.githubusercontent.com/5585202/31346774-e263a5ec-ad22-11e7-8f42-64def0718889.png)

**Comment by AlexChernov** [comment]
Ок, спасибо, сегодня ночью посмотрю заодно

**Comment by AlexChernov** [comment]
Не воспроизводится в alexchernov/raox/feature/result-tests.
pull request #588

**Comment by aurusov** [comment]
А на 3.8.0 ?

**Comment by aurusov** [comment]
Проверил твою ветку, ошибка осталась
![error _002](https://user-images.githubusercontent.com/5585202/31454124-0fdd94a6-aebd-11e7-8fd8-7495b3f16b2a.png)

**Comment by aurusov** [comment]
Увидел новый пункт меню `Model/Export Results`. Он приводит к такой же ошибке. Что странно, потому что она про `trace writer`.

**Comment by aurusov** [comment]
Теперь работает.
