### ISSUE TITLE
Листы Курсовой

### ISSUE THREAD

**Issue by ViktorRakhmatulin** [LeKaitoW/raox#552]
Буду прикреплять листы размером А1 в формате pdf.
1) постановка задачи
2) диаграмма классов
3) диаграмма последовательности вызовов
4) быть может, блок-схемы функций
5) результаты

**Comment by ViktorRakhmatulin** [comment]
[лист1.pdf](https://github.com/aurusov/raox/files/650073/1.pdf)

@aurusov Жду комментариев. В таком же стиле планирую оформить лист результатов

**Comment by ViktorRakhmatulin** [comment]
[лист5.pdf](https://github.com/aurusov/raox/files/650289/5.pdf)

**Comment by aurusov** [comment]
Посмотрите, как и где надо размещать листы https://github.com/bogachev-pa/bogachev-pa.github.io/issues/1.

**Comment by aurusov** [comment]
Лист 1
- Скрины должны быть одного размера
- Скрины должны быть четко выравнены относительно и листа и друг друга
- Никаких двоеточий
![2016-12-15_09-51-30 2](https://cloud.githubusercontent.com/assets/5585202/21214639/005edd70-c2ad-11e6-8b45-5720ac30dfc8.png)

**Comment by aurusov** [comment]
Лист 5
- Скрины должны быть одного размера
- Скрины должны быть четко выравнены относительно и листа и друг друга
- Никаких двоеточий
- Приобретенные умения
  - Изучил и применил на практике язык программирования Java
  - Провел анализ классов подсистемы графиков РДО, их взаимодействия их между собой и ядром симулятора
  - Применил паттерн проектирования Наблюдатель

![2016-12-15_09-59-20](https://cloud.githubusercontent.com/assets/5585202/21214724/a2a27344-c2ad-11e6-9053-5c2ba031fc0b.png)

**Comment by ViktorRakhmatulin** [comment]
Не могу понять, в какой момент(через какой метод) запускается метод из класса PlotView run()
Пытаюсь положить этот метод в диаграмму последовательности вызовов

**Comment by ViktorRakhmatulin** [comment]
Посмотрите,пожалуйста, диаграмму вызовов. вечером залью через github.io.

**Comment by aurusov** [comment]
Задачу договорились перенести в другую репу, не надо сюда писать.

**Comment by ViktorRakhmatulin** [comment]
![Uploading 10_6.jpg…]()

**Comment by ViktorRakhmatulin** [comment]
это не к задаче,а к листам.

**Comment by ViktorRakhmatulin** [comment]
![10_6](https://cloud.githubusercontent.com/assets/22197503/21388571/de6db05c-c78d-11e6-9719-55f4ba740def.jpg)

**Comment by aurusov** [comment]
Я знаю, именно это и имею в виду

**Comment by aurusov** [comment]
>это не к задаче,а к листам.

Я знаю, именно про эту (текущую) задачу и говорю.

**Comment by aurusov** [comment]
где задача по курсовому ?

**Comment by ViktorRakhmatulin** [comment]
В процессе создания. Я на работе был.

**Comment by ViktorRakhmatulin** [comment]
https://github.com/ViktorRakhmatulin/ViktorRakhmatulin.github.io.git
ПОчему-то ссылки на листы не открываются. Назначить Вас на issue тоже не получается с убунты

**Comment by aurusov** [comment]
>ПОчему-то ссылки на листы не открываются.

посмотрите ссылки с Пашиной страницы

>Назначить Вас на issue тоже не получается с убунты

Я должен быть в колабораторах
