### ISSUE TITLE
Неправильная обработка нулевого указателя

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#555]
```erlang
enum Состояние_парикмахера {Свободен, Занят}

type Парикмахерские {
	Состояние_парикмахера состояние_парикмахера
	int количество_в_очереди
}

event Событие_прихода_клиента(Парикмахерские парикмахерская) {
	log("event line 1")
	Событие_прихода_клиента.plan(currentTime + 1, null)
	log("event line 2")
	if (парикмахерская != null) {
		log("event line 3")
		парикмахерская.количество_в_очереди = парикмахерская.количество_в_очереди + 1
	}
}

def init() {
	Событие_прихода_клиента.plan(currentTime + 1, null)
}

def terminateCondition() {
	return currentTime >= 10
}
```
Трассировка
```
ES 0.0 Tracing started
ES 0.0 Simulation started
ES 1.0 Simulation finished: runtime error
```
Лог
```
Started model barber
event line 1
event line 2
event line 3
Execution error

Call stack:
java.lang.NullPointerException
	at barber.barber$Событие_прихода_клиента.execute(barber.java:163)
	at ru.bmstu.rk9.rao.lib.event.Event.run(Event.java:16)
	at ru.bmstu.rk9.rao.lib.simulator.Simulator.run(Simulator.java:158)
	at ru.bmstu.rk9.rao.lib.simulator.CurrentSimulator.run(CurrentSimulator.java:143)
	at ru.bmstu.rk9.rao.ui.execution.ExecutionJobProvider$1.run(ExecutionJobProvider.java:94)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Execution failed
```

**Comment by aurusov** [comment]
ping

**Comment by bogachev-pa** [comment]
Очевидно, где-то в генерированном коде не хватает проверки на `null`.

**Comment by aurusov** [comment]
Сможешь добавить ? Или подскажи где добавлять. Задача горит.

**Comment by aurusov** [comment]
Но сдается мне, что всю работу с обертками над ресурсами надо переделывать. Три бага про один и тот же класс imho.

**Comment by bogachev-pa** [comment]
Так трудно сказать, лучше всего посмотреть генеренный код
```
at barber.barber$Событие_прихода_клиента.execute(barber.java:163)
```

Выглядит так, что дело в коде эвента, а не ресурса. Но надо уточнять.

**Comment by aurusov** [comment]
Вангую, не смотря в код. В коде обертка, не ресурс, честно проверяется на нулевой указатель. Надо же пробрасывать сравнение внутрь.

**Comment by bogachev-pa** [comment]
Какая обертка? Не очень вас понял.

Если параметром сделать не ресурс, а какой-нибудь `String` и тоже передать `null`, то все будет ок?

**Comment by aurusov** [comment]
>Какая обертка? Не очень вас понял.

Кирилл еще писал обертку над ресурсами. И ты поминал её в разговорах. В ней сейчас счетчик ссылок живет.

>Если параметром сделать не ресурс, а какой-нибудь String и тоже передать null, то все будет ок?

Нет, тоже самое. Похоже дело не в обертке.
```erlang
enum Состояние_парикмахера {Свободен, Занят}

type Парикмахерские {
	Состояние_парикмахера состояние_парикмахера
	int количество_в_очереди
}

event Событие_прихода_клиента(String строка) {
	log("event line 1")
	Событие_прихода_клиента.plan(currentTime + 1, null)
	log("event line 2")
	if (строка != null) {
		log("event line 3")
	}
}

def init() {
	Событие_прихода_клиента.plan(currentTime + 1, null)
}

def terminateCondition() {
	return currentTime >= 1
}
```
```
Started model barber
event line 1
event line 2
event line 3
Stopped by terminate condition
Time elapsed: 24ms
```

**Comment by bogachev-pa** [comment]
Думаю, у вас имеется ошибочное представление об устройстве наших ресурсов.
Никаких оберток над самими ресурсами нет.
Есть специальная обработка [`set/get`](https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao/src/ru/bmstu/rk9/rao/jvmmodel/ResourceTypeCompiler.xtend#L80) параметров.
И есть, действительно, [рефкаунтеры](https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao.lib/src/ru/bmstu/rk9/rao/lib/resource/Resource.java#L26). Но они живут просто в родительском классе всех ресурсов, не в обертке. И нужны они для подбора ресурсов - чтобы работал `accessible()`. Вот [тут](https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao/src/ru/bmstu/rk9/rao/jvmmodel/PatternCompiler.xtend#L159) каунтер берется, и вот [тут](https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao/src/ru/bmstu/rk9/rao/jvmmodel/PatternCompiler.xtend#L194) отпускается.

>Нет, тоже самое. Похоже дело не в обертке.

Надо смотреть сгенерированный код.

**Comment by aurusov** [comment]
Надо использовать тройное сравнение `===` / `!==`. Полная работающая модель
```erlang
enum Состояние_парикмахера {Свободен, Занят}

type Парикмахерские {
	Состояние_парикмахера состояние_парикмахера
	int количество_в_очереди
}

event Событие_прихода_клиента(String строка) {
	log("event line 1")
	Событие_прихода_клиента.plan(currentTime + 1, null)
	log("event line 2")
	if (строка !== null) {
		log("event line 3")
	}
}

def init() {
	Событие_прихода_клиента.plan(currentTime + 1, null)
}

def terminateCondition() {
	return currentTime >= 1
}
```
```
Started model barber
event line 1
event line 2
Stopped by terminate condition
Time elapsed: 26ms
```
