### ISSUE TITLE
Добавить импорт из базы данных

### ISSUE THREAD

**Issue by mikhailmineev** [LeKaitoW/raox#578]
Добавить возможность импорта данных для моделирования из базы данных

**Comment by mikhailmineev** [comment]
@aurusov 
Попробую внедрить данную штуку, но пока не знаю, что получится
http://www.querydsl.com/static/querydsl/latest/reference/html/ch02.html#jpa_integration

**Comment by aurusov** [comment]
Выглядит вполне достойно, но меня немного смущает, что последнее обновление на гитхабе от февраля 17-го. Кажется, проект заморожен.

**Comment by mikhailmineev** [comment]
Есть ещё вариант, похожий на querydsl - https://www.jooq.org
Данный проект точно живее
Но там разные виды лицензий и у opensource скудный выбор баз https://www.jooq.org/legal/licensing#databases
Есть худший вариант, но мне не нравится, поскольку тяжело формировать запросы
http://docs.oracle.com/javaee/6/tutorial/doc/gjivm.html
Поищу ещё варианты, но не уверен, что они будут норм

**Comment by aurusov** [comment]
querydsl выглядит интереснее imho. [Google Group](https://groups.google.com/forum/#!forum/querydsl) у них живой.

**Comment by mikhailmineev** [comment]
У меня на работе в некоторых проектах используется именно querydsl, собственно и потому я на него в первую очередь посмотрел
Еще это для себя оставлю, пока не особо вник http://www.eclipse.org/eclipselink/#jpa

**Comment by mikhailmineev** [comment]
Еще вопрос возник, как добавить библиотеки в проекты raox-runtime, как это сделано с классами rao.lib
![capture](https://user-images.githubusercontent.com/6087009/30160986-84d9b06a-93d7-11e7-8f11-d89f0739fca4.PNG)
Как добавить либы в сам ru.bmstu.rk9.rao.lib я понял. По примеру commons-math3. Но чтобы она отобразилась в рантайме, я не смог добиться

**Comment by aurusov** [comment]
>Еще это для себя оставлю, пока не особо вник http://www.eclipse.org/eclipselink/#jpa

querydsl работает с jpa

**Comment by aurusov** [comment]
>Как добавить либы в сам ru.bmstu.rk9.rao.lib я понял. По примеру commons-math3. Но чтобы она отобразилась в рантайме, я не смог добиться

В какой проект надо добавить либу ? В модель ? По примеру Xtend Library не получается ?

**Comment by mikhailmineev** [comment]
Да, чтобы в модели была, по примеру Xtend Library не смог сообразить можно ли
Нашел вариант https://stackoverflow.com/questions/16918500/exporting-jar-libraries-in-an-eclipse-plugin
Пока не пробовал

**Comment by aurusov** [comment]
Вот [тут](https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java#L127) формируется class path для проекта модели.

**Comment by mikhailmineev** [comment]
Проблема с тем, что не загружались Entity решена
Оставлю, чтобы не потерять ссылку
https://stackoverflow.com/questions/27304580/mapping-entities-from-outside-classpath-loaded-dynamically

**Comment by mikhailmineev** [comment]
У меня вопрос насчет dataprovider. Данную штуку можно же просто создавать как constant и не париться. Также не очень приятна идея хранить итератор в ресурсе глобальном, при автоматическом запуске скорее всего сбросится (не проверял), возможно стоит создать аналог constant, обозвав его а ля global, который будет модифицируемым.

**Comment by aurusov** [comment]
>У меня вопрос насчет dataprovider. Данную штуку можно же просто создавать как constant 

М.б. я не понял. Хочешь отказаться от слова datasource в пользу constant ?

**Comment by aurusov** [comment]
>Также не очень приятна идея хранить итератор в ресурсе глобальном

Что за глобальный итератор ? У каждого query свой итератор же.

>аналог constant, обозвав его а ля global, который будет модифицируемым.

Какая-то странная изменяема переменная global.

Итого: нужен пример как есть, как будет. А там сравним.

**Comment by mikhailmineev** [comment]
По источнику данных
Как есть
```dataprovider data = new SqlDataProvider(...)```
Как будет 
```constant data = new SqlDataProvider(...)```
Данные варианты после компиляции всё равно представляют одинаковые поля
```public static final SqlDataProvider = ...```
Собственно зачем тогда городить лишнее?

По итератору
Как есть
```
type Orders {
	Iterator<Order> iterator
}

resource orders = Orders.create(null)

def init() {
	val query = data.getQuery()
	val order = QOrder.order
	orders.iterator = query.from(order).fetch().iterator()
	...
```
Как будет 
```
global orders

def init() {
	val query = data.getQuery()
	val order = QOrder.order
	orders = query.from(order).fetch().iterator()
	...
```
И компилироваться данная штука должна будет в что-то типа
```public static Iterator orders;```
Пока не могу утверждать, ещё не сделал, но при перезапуске, когда модель будет с изменяемыми параметрами запускаться, нужно будет менять значение какого-нибудь числа и тут 2 вопроса:
1. Не сотрется ли итератор, поскольку он внутри ресурса
2. Как менять значения изменяемого параметра, поля типа global подошли бы

**Comment by aurusov** [comment]
>По источнику данных
Как есть
```dataprovider data = new SqlDataProvider(...)```
Как будет 
```constant data = new SqlDataProvider(...)```
Данные варианты после компиляции всё равно представляют одинаковые поля
```public static final SqlDataProvider = ...```
Собственно зачем тогда городить лишнее?

~~Давай попробуем.~~
Теряется читаемость. `dataprovider` лучше доносит мысль. Мы же не стремимся всех, кто будет `public static final` назвать константами. Я бы еще понял, если бы вместо типа слева было слово `auto`.

**Comment by aurusov** [comment]
>По итератору

Какое-то странное название `global`. Предлагаю `cursor`.

**Comment by mikhailmineev** [comment]
По рестарту модели, просится что-то такое в модели
```
def experiment() {
   def setup() {
	val order = QOrder.order
	orders = data.getQuery().from(order).fetch().iterator()
    }
   def terminate() {
	return !orders.hasNext()
    }
}
```
Пока не реализовывал, но это кажется проще в реализации чем что-то вроде
```
def experiment() {
    val order = QOrder.order
    orders = data.getQuery().from(order).fetch().iterator()
    while (orders.hasNext()) {
	somethingThatInitsModel()
    }
}
```

**Comment by aurusov** [comment]
>По рестарту модели, просится что-то такое в модели

Ну тогда уж во множественном лице.
```erlang
def experiments() {
}
```
Не понимаю
- Что делает setup() ? Он вызывается один раз или перед каждым экспериментом ? Если да, то должен ли он вернуть true, чтобы эксперимент начался ?
- Что делает terminate() ? Останавливает серию экспериментов ? Если да, то будет непонятно, почему setup() запускает i-ый эксперимент, а terminate() завершает всё. Надо подумать над читаемостью.
- Рассмотрим кейс. Есть параметр ресурса, который при каждом запуске должен иметь новое значение, например, 1, 2 и 3 для трех запусков. Хотелось бы завести 'глобальную' переменную вне модели, которая будет делать +1 для себя и выставлять этот параметр перед запуском. Вопрос: если setup() перед каждым запуском, то как сохранить глобальную переменную ?

Все эти вопросы снимает второй подход. Поэтому поясни, почему он кажется сложнее ?

**Comment by mikhailmineev** [comment]
Пробую реализовать второй подход, возникла трудность, код пока не пушил
Вот фрагмент кода, отвечающий за выполнение модели https://github.com/mikhailmineev/raox/blob/release/current/ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/ExecutionJobProvider.java#L80-L129
И его, получается, надо как-то передавать модели, чтобы она его выполняла в методе experiment(), а именно в методе somethingThatInitsModel() (Вытащив данный код в отдельный класс). Передачу я как-то реализовал, но тут возник вопрос, выполнение данного кода возвращает результат, и наверное при появлении ошибки нужно прерывать метод experiment(). Это можно сделать кидая исключение, или есть более элегантное решение данной задачи?

**Comment by mikhailmineev** [comment]
Собственно в первом методе данная сложность не возникает, поскольку код перезапуска реализуется в данном классе, путем оборачивания вот [этого](https://github.com/mikhailmineev/raox/blob/release/current/ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/ExecutionJobProvider.java#L80-L129) кода циклом

**Comment by aurusov** [comment]
~~Для рестарта модели заведи другую таску.~~ Завёл https://github.com/aurusov/raox/issues/592. Бранч можно оставить этот (хотя...), но коммиты должны иметь правильные ссылки на задачи.

**Comment by aurusov** [comment]
>наверное при появлении ошибки нужно прерывать метод experiment().

Ой не факт. Зависит от ошибки. Если ошибка компиляции, то да. Если runtime, то нет. Будет 10 из 10 красных экспериментов, ничего страшного не вижу. Зато сценарий эксперимента тработает до конца.

**Comment by mikhailmineev** [comment]
> Бранч можно оставить этот (хотя...)

А мне все равно будет нужно сливать их вместе, и две ветки в итоге будут указывать на один коммит, есть ли смысл вести две ветки тогда?

**Comment by aurusov** [comment]
Вот поэтому и не хочется заводить второй бранч. Но тут есть момент - а давай мы отложим пока серию экспериментов. Ведь она не блочит твой курсач, как мне кажется. Лучше допилить интеграцию с БД и довести модель до ума.

**Comment by mikhailmineev** [comment]
Да, на данный момент не блочит, тогда на модель переключаюсь

**Comment by mikhailmineev** [comment]
Решено отказаться от данной фичи, оставить только импорт java кода(#601)
