### ISSUE TITLE
Реализация закона распределения для стандартного потока

### ISSUE THREAD

**Issue by Troideninc** [LeKaitoW/raox#580]
Необходимо реализовать закон генерации интервалов времени между событиями для потока однотипных независимых событий. Распределение для такого потока отличается от нормального.

https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D1%82%D0%BE%D0%BA_%D0%BE%D0%B4%D0%BD%D0%BE%D1%80%D0%BE%D0%B4%D0%BD%D1%8B%D1%85_%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9

Вид распределения:
![501082_html_75a14764](https://user-images.githubusercontent.com/31829477/30523360-ab4dd640-9be8-11e7-9cba-837e04b4896a.gif)

**Comment by aurusov** [comment]
@Troideninc 
Подскажи, какое это именно распределение из [списка](https://en.wikipedia.org/wiki/List_of_statistics_articles) ?

**Comment by Troideninc** [comment]
Из того, что я прочёл стационарный поток 
Описывается распределение пуассона.

**Comment by aurusov** [comment]
Т.е. вот этот https://en.wikipedia.org/wiki/Poisson_distribution ? Но Пуассон только для дискретных значений. Именно это и надо ?
