### ISSUE TITLE
Результат по временный ресурсам

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#586]
Хочется в момент удаления временного ресурса собрать о нем информацию. На уровне интерфейса дергать `update()` с параметром.

```erlang
dataSource КлиентВремяОжидания<Double>() {
    def evaluate(Клиент клиент) {
        return клиент.время_ожидания
    }
}

result клиентВремяОжидания = Result.create(new КлиентВремяОжидания(), ResultMode.MANUAL)
...
клиентВремяОжидания.update(клиент)
```

А то сейчас приходится заводить фиктивный постоянный ресурс для проксирования нужных параметров.

Сразу вдогонку на подумать
- Кажется, что надо синхронно менять интерфейс у `condition()`
или
- Кажется, что можно не менять интерфейсы, но начать относиться к параметрам по другому, например

```erlang
dataSource КлиентВремяОжидания<Double>(Клиент клиент) {
    def evaluate() {
        return клиент.время_ожидания
    }
}

result клиентВремяОжидания = Result.create(new КлиентВремяОжидания(), ResultMode.MANUAL)
...
клиентВремяОжидания.update(клиент)
```
Т.е. сейчас параметры относятся к фабрике, а предлагается относить их к update/condition

**Comment by AlexChernov** [comment]
> Хочется в момент удаления временного ресурса собрать о нем информацию. На уровне интерфейса дергать update() с параметром.

Это уже реализованно, даже документация есть http://raox.ru/docs/reference/result.html  

Предложенный кейс решается напрямую
``` java
result клиентВремяОжидания = Result.create(new StorelessNumericStatistics<Double>()) //Кстати эта статистка должна быть не взвешенна
//put your logic here
клиентВремяОжидания.update(клиент.время_ожидания)
```

Если нужно в update посложнее логику, то вместо evaluate() можно использовать просто функции, они вроде поддерживают ресурсы в качестве параметров

**Comment by aurusov** [comment]
А почему результат не `ResultMode.MANUAL` ?

**Comment by AlexChernov** [comment]
Результат без источника данных, как по мне, не может быть не ResultMode.MANUAL по определению

**Comment by aurusov** [comment]
Отлично, просто хотел уточнить. Тогда закрываю.
