### ISSUE TITLE
Продумать предоставление данных ModelStructureCache для ui

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#62]
Пришлось вкорячить https://github.com/kstrizhov/rdo-xtext/blob/abfe9376946331de32d35280bbb020a0a549bf86/ru.bmstu.rk9.rdo.lib/src/ru/bmstu/rk9/rdo/lib/ModelStructureCache.java#L49

 Надо не забыть **удалить** этот костыль.

Хочется, чтобы ui имело доступ через

```
Simulator.getModelStructureCache().getDecisionPointsInfo().get(dptNumber).getName()
```

**Comment by bogachev-pa** [comment]
В ветке с`xbase` `ModelStructureCache` больше нет.
