### ISSUE TITLE
Настроить thirdparty

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#72]
Начало тут https://github.com/aurusov/rdo-xtext/pull/64
- добавить скрипт, который
  - выкачивает либы
  - перепаковывает исходники
  - кладет в thirdparty
- обновить readme
- обновить манифест

**Comment by bogachev-pa** [comment]
Готово. Мне инструкцию по использованию этого скрипта надо куда-нибудь добавить?
Собственно, она будет выглядеть так:

``` bash
bash path_to_thirdparty_folder/get_thirparty_libraries.sh
```

**Comment by bogachev-pa** [comment]
Еще такой вопрос: если запустить скрипт 2 раза подряд, он перепакует исходники и они будут считаться `modified`.
Как тут лучше поступить?

Можно, например, впилить флажок, который будет говорить, игнорить уже существующие зипы или все перезаписать.

**Comment by aurusov** [comment]
Поставь пул-реквест

> Мне инструкцию по использованию этого скрипта надо куда-нибудь добавить?

нет

> Еще такой вопрос: если запустить скрипт 2 раза подряд, он перепакует исходники и они будут считаться `modified`.

А что отличается в новом архиве ?

**Comment by bogachev-pa** [comment]
> А что отличается в новом архиве ?

Пока не могу понять. Может, какие-то таймштампы в зиповском формате?

**Comment by bogachev-pa** [comment]
Пул реквест поставил: https://github.com/aurusov/rdo-xtext/pull/74

**Comment by aurusov** [comment]
Залил исправления
Сейчас посмотрю что там с бинарниками

**Comment by bogachev-pa** [comment]
Вроде можно закрыть.
