### ISSUE TITLE
Шрифт оси Y графиков под Виндой

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#79]
Шрифт по оси Y отличается от оси X и от шрифта в других местах Эклипса

![2015-10-04 15-07-41 rao - eclipse platform](https://cloud.githubusercontent.com/assets/5585202/10267739/c313dd1e-6aa9-11e5-8a3c-325790b796de.png)

Цифры выводятся нормальными
![2015-10-04 15-08-06 rao - eclipse platform](https://cloud.githubusercontent.com/assets/5585202/10267743/d0d790ee-6aa9-11e5-886c-71ab9d49b48a.png)

**Comment by LeKaitoW** [comment]
Шрифт такой же, как у лейбла под графиком:
![plotfont](https://cloud.githubusercontent.com/assets/10632455/10268225/1d2d42d6-6ac3-11e5-9c5b-da116887acaf.png)

**Comment by aurusov** [comment]
Думаешь я фотошопил ? Мой скрин
raox 2.7.1, windows 10, x64, mars 1

Где назначается шрифт ?

**Comment by LeKaitoW** [comment]
Я написала это после коммита!
Имела в виду, что в коммите использовала такой шрифт. :(

Назначается имя шрифта, от него уже делается `new Font()`.

**Comment by aurusov** [comment]
Ааа, коммита то я и не заметил.

**Comment by aurusov** [comment]
Все клёво, ставь пул-реквест

**Comment by LeKaitoW** [comment]
Поставила на `release/2.8`.
Заметила, что ваш пулл-реквест про документацию стоит на `release/2.7`. На какую ветку ставить?

**Comment by aurusov** [comment]
Ответь на два вопроса
1. это фича или бага ?
2. какая текущая версия ?

**Comment by LeKaitoW** [comment]
1. с меткой `bug`, значит, бага
2. 2.7

Переставила на 2.7.

**Comment by aurusov** [comment]
Да. Для полноты картины изменю тип таски. Перевел с бага, когда думал про бонусы.
