### ISSUE TITLE
Проблема с параметрами DPT activity

### ISSUE THREAD

**Issue by k-alexandrovsky** [LeKaitoW/raox#8]
@aurusov 
В РДО синтаксис имеет следующий вид:
`Имя_активности : Имя_паттерна Параметр1 Параметр2 ... Параметр N`

Правило запрещает использовать полноценные выражения для параметров, потому что разделителей нет и парсер не переносит леворекурсивные правила. Я сделал параметры атомарными. То есть идентификаторы и константы писать можно, что-либо сложнее нужно облачать в скобки.

Проблема возникает вот когда:

```
$Activities
  Перемещение_вправо: Перемещение_фишки справа   1  value after 1
  Перемещение_влево : Перемещение_фишки слева  -1 value after 1
  Перемещение_вверх : Перемещение_фишки сверху -3 value after 1
  Перемещение_вниз  : Перемещение_фишки снизу    3  value after 1
$End
```

Я превращаю это в

```
$Activities
  Перемещение_вправо: Перемещение_фишки справа   1  value after 1
  Перемещение_влево : Перемещение_фишки слева  (-1) value after 1
  Перемещение_вверх : Перемещение_фишки сверху (-3) value after 1
  Перемещение_вниз  : Перемещение_фишки снизу    3  value after 1
$End
```

Но `слева  (-1)` для него вызов функции, ибо он тоже атомарен. Скобки не работают. И это один параметр. А без скобок минус не очень желанный гость в параметрах. Я пока сделал
`Имя_активности : Имя_паттерна(Параметр1, Параметр2, ..., Параметр N)`
Но это вредит совместимости. В итоге я даже не знаю, как быть. Эти минусы даже костыльно там написать не выходит

**Comment by aurusov** [comment]
Именно так

```
Имя_активности: Имя_паттерна(Параметр1, Параметр2, ..., Параметр N);
```

Не забудь `;`, может понадобиться.
Надо обновить конвертер и справку. Поставь себе задачу.

**Comment by k-alexandrovsky** [comment]
Форкнуть РДО, создать issue, поменять конвертер, сделать pull request? А справка тоже есть в в виде репо?

**Comment by aurusov** [comment]
[Справка](https://github.com/aurusov/rdo_studio/tree/dev/app/rdo_studio/help) с исходниками.

**Comment by bogachev-pa** [comment]
Кажется, таска потеряла смысл.

**Comment by aurusov** [comment]
Нет. Это изменения для старого РДО. Если этого не сделать в старом, в то в новом нельзя будет написать конвертер из старого синтаксиса в новый.

**Comment by k-alexandrovsky** [comment]
Старое РДО не собиралось в релизе на винде (вроде как именно в такой комбинации). В общем, была какая то одна сборка, которая мешала замержиться там и закрыть эту таску. Пулл-реквест все еще висит:
https://github.com/aurusov/rdo_studio/pull/23

**Comment by aurusov** [comment]
Уже увидел непонятное место, отписался там. Надо смотреть пул-реквест. Неработающую сборку надо дебажить, но никто этого не делал. Кирилл ?

**Comment by k-alexandrovsky** [comment]
Непонятная сборка падала у меня, у Лехи, на нее было потрачено как минимум несколько десятков часов разными людьми в сумме. Повторить у себя на компьютерах никому не удавалось.
Насколько я помню, там просто консольное РДО на какой то модели виснет в конвертере.

**Comment by aurusov** [comment]
И, если не путаю, то и мной тоже. Но ошибка никуда не ушла. Предлагаю вспомнить проблему. Кажется, что не проходил конвертор конкретной модели ? Надо поднять у себя подобную сборку и подебажить. Или добавить кучу логов и запускать на сервере.

**Comment by aurusov** [comment]
Изменения в конвертере были довольно большие.

**Comment by k-alexandrovsky** [comment]
В прошлый раз уже решили, что надо брать радмин, и дебажить прямо там. Не знаю, возможно ли это сейчас и в каком состоянии и качестве сейчас сервер.

**Comment by aurusov** [comment]
Старое РДО починено.
