### ISSUE TITLE
Какая-то fancy yellowish вместо темы

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#81]
Как выглядит под Windows 8.1
![2015-07-07 23-44-57 rao - barber barber rao - eclipse platform](https://cloud.githubusercontent.com/assets/5585202/8556837/3b725a30-2502-11e5-9c91-2a7e95db784e.png)

Что получилось
- Windows 8.1
  ![2015-07-15 00-45-10 rao - barber barber rao - eclipse platform](https://cloud.githubusercontent.com/assets/5585202/8685956/da1fdaee-2a8a-11e5-86b0-fdb1dd8fa878.png)
  ![2015-07-15 00-45-22 rao - barber barber rao - eclipse platform](https://cloud.githubusercontent.com/assets/5585202/8685957/dbba48f8-2a8a-11e5-925e-0e87b6c77245.png)
  ![2015-07-15 00-45-34 rao - barber barber rao - eclipse platform](https://cloud.githubusercontent.com/assets/5585202/8685959/dcddaebe-2a8a-11e5-9eac-c22a48dd6e5e.png)

**Comment by bogachev-pa** [comment]
грубовато
тема-то стандартная

я предлагаю заставить всех пользоваться гномом, там самое красивое оформление эклипса (см. скрин из ридми)

**Comment by aurusov** [comment]
> тема-то стандартная

У меня и винда и эклипс рисуют бегущий ползунок зеленым цветом. Откуда берётся этот ?

**Comment by bogachev-pa** [comment]
Винда не позволяет настраивать цвета прогрессбара кроме как выставлением состояний (`SWT.NORMAL`, `SWT.PAUSED`, `SWT.ERROR`).

Вот что я нашел в коде:
https://github.com/aurusov/rdo-xtext/blob/release/current/ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/simulation/SpeedSelectionToolbar.java#L45

Подробности вам стоит выяснить у Кирилла.

**Comment by aurusov** [comment]
Не, название стало мерзко толерантным, а это именно поносная хрень, которую в коментах ласково назвали `fancy yellowish`.

**Comment by bogachev-pa** [comment]
Ну у вас вообще как-то эклипс страшно выглядит. Почему-то умерли все обводки и эффекты.
Под моей семеркой вот так:
![muheclipse](https://cloud.githubusercontent.com/assets/6528492/8565078/c755d006-255a-11e5-8dda-6fd3b85299ea.png)

**Comment by aurusov** [comment]
> Ну у вас вообще как-то эклипс страшно выглядит

И это ключевая фраза. У тебя хотя бы похоже на желтый, глянец по краям, как в теме винды. У меня тема плиток (8.1), т.е. никакого глянца. Обводка осталась, но она тоже плоская. Это норм, но в целом цвет ужасный. Эффект первого запуска отвратительный. С этим просто хочется что-то сделать, чтобы не травмировать психику студентам. Конечно, это повод пересадить их под убунту, но не такой ценой :)

**Comment by aurusov** [comment]
И таки да, ползунок под семеркой выглядит намного лучше, бросаться править нет желания. Но в идеальном мире и он должен быть в теме process-bar'а.

**Comment by aurusov** [comment]
Решено тут https://github.com/aurusov/rdo-xtext/pull/96
