### ISSUE TITLE
Ломается  PlotView после экспорта

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/raox#84]
Обновила ветку мастера до release/current. После экспорта при попытке закрыть эклипс отображается ошибка про PlotView, а эклипс не закрывается, пока не получит kill -9.

**Comment by bogachev-pa** [comment]
У меня такое тоже было, но теперь не могу воспроизвести.

**Comment by aurusov** [comment]
- Удали все папки `*.rdo.*` из исходников
- Удали папку `runtime-EclipseXtext`

**Comment by aurusov** [comment]
Помогло ?

**Comment by aurusov** [comment]
Будем считать, что не воспроизводится. Закрываю.

Или есть последовательность, приводящая к ошибке ?

**Comment by bogachev-pa** [comment]
Т.к. мы теперь создаем джарники только через мавен, то, наверное, она уже и не очень актуальна.
Плюс да, четкого алгоритма воспроизвестинет.
