### ISSUE TITLE
Версии rao

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#85]
@aurusov 
В `MANIFEST.MF` (вот [здесь](https://github.com/aurusov/rdo-xtext/blob/release/current/ru.bmstu.rk9.rao.ui/META-INF/MANIFEST.MF#L5)) указывается версия плагина. Я думаю, надо обновлять их в соответствии с нашими релизами.
Рекоммендации по ведению версий плагина можно найти здесь: https://wiki.eclipse.org/Version_Numbering. Они, в принципе, совпадают с правилами, которым следуем мы в нашей нумерации.
Разница только в том, что они для багфиксом для текущего релиза используют версии типа `2.4.1`, а если тот же баг будет пофикшен только к следующему релизу, то `2.4.100`, но нам это вроде не совсем подходит, так что, думаю, можно оставить, как есть.

Тогда надо в гитфлоу дописать, что когда ветка с релизом мержится в ветку мастер, надо обновить циферки в манифестах, правильно?

**Comment by aurusov** [comment]
Да, допиши прям в `release/current`.

**Comment by bogachev-pa** [comment]
Дописал.

**Comment by aurusov** [comment]
Не вижу ссылки на коммит

**Comment by bogachev-pa** [comment]
https://github.com/aurusov/rdo-xtext/commit/2500e99e3d78ddc7274ddcabe1105c8ae2424bcb
