### ISSUE TITLE
NullPointerException при двойном клике по дереву сериализованных объектов

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#87]
Происходит в том случае, если листовая вершина не содержит индекса:
![npe](https://cloud.githubusercontent.com/assets/6528492/8636817/d3930f2a-287d-11e5-8da6-e54cec778b4a.png)

Причина в том, что в методе [`isEnabled()`](https://github.com/aurusov/rdo-xtext/blob/release/current/ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/graph/GraphView.java#L20) класса `GraphView` нет проверки на `index == null`.

Проверку уже добавил. Но нужен ли нам вообще листовой элемент в дереве для пустых результатов/серчей/еще чего-то?

**Comment by aurusov** [comment]
- Пусть будет
- Проверки должны стоять на уровень выше, перед
  - https://github.com/aurusov/rdo-xtext/blob/release/current/ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/serialization/SerializedObjectsView.java#L67
  - https://github.com/aurusov/rdo-xtext/blob/release/current/ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/serialization/SerializedObjectsView.java#L76
