### ISSUE TITLE
Странная расцветка чисел

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#93]
Сейчас
- целые числа почему-то серым
- вещественные черным

Хочется их сделать одним цветом, например, черным, как в жабе эклипса.

![2015-07-12 22-07-45 rao - barber barber rao - eclipse platform](https://cloud.githubusercontent.com/assets/5585202/8639428/78f99894-28e2-11e5-971c-1adc796cd704.png)

**Comment by aurusov** [comment]
@bogachev-pa 
Паша, тебе известна история вопроса ?

**Comment by bogachev-pa** [comment]
Нет, не известна. Надо разбираться.

**Comment by bogachev-pa** [comment]
Чтобы потом не забыть: это исправлено в ветке по `xbase`.
